import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_BT02: Card[] = createCards([
  {
    name: "บุญลือ วีรบุรุษเปรต",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-001",
    rare: Rarity.SR,
    variants: [Rarity.SCR, Rarity.PR, Rarity.CBR],
    mainEffect:
      "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : หงาย LIFE Card ฝ่ายเรา 1 ใบ\n\nต่อเนื่อง การ์ดใบนี้ POWER จะเพิ่มตามจำนวน LIFE Card ของทั้ง 2 ฝ่าย ที่ถูกหงายอยู่ ใบละ 1",
    cost: 4,
    gem: 0,
    power: 0,
    symbol: Symbol.Pret,
    color: Color.Red,
  },
  {
    name: "วันชัย พ่อบุญลือ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-002",
    rare: Rarity.R,
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost ในการอัญเชิญ Avatar {Symbol เปรต} : Avatar ใบนั้นจะไม่ถูกทำลายในเทิร์นนี้",
    cost: 5,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "กัญญา แม่บุญลือ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-003",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost ในการอัญเชิญ Avatar {Symbol เปรต} : จั่วการ์ด 1 ใบ หลังจากนั้น ทิ้งการ์ด 1 ใบ",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "พี่เช 10 ล้อท่าอิฐ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-004",
    rare: Rarity.C,
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง เมื่อ Avatar ใบนี้ประกาศโจมตี ทิ้งการ์ดบนมือ 1 ใบ : การ์ดใบนี้ POWER +2 จนจบเทิร์น",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "ตำรวจไซบอร์ค จ่าคอป",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-005",
    rare: Rarity.R,
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง เมื่อ Avatar ใบนี้ประกาศโจมตี ทิ้งการ์ดบนมือ 1 ใบ : สอดแนม (แสดงการ์ดใบบนสุดของ Deck) 3 ใบ นำการ์ด Symbol เครื่องจักร 1 ใบ จากที่สอดแนม ขึ้นมือ การ์ดที่เหลือเรียงและนำไปไว้ใต้ Deck",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "คนรวย",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-006",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง ในเทิร์นใครก็ได้ เมื่ออีกฝ่ายใช้ความสามารถการ์ด นำการ์ด 1 ใบ บนมือเราให้อีกฝ่าย : ยกเลิกความสามารถของการ์ดนั้น และในเทิร์นนี้เราไม่สามารถใช้ React Magic ได้",
    cost: 5,
    gem: 4,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "อ๊บ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-007",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) เลือก Avatar บน Avatar Zone ฝ่ายเรา นอกจากใบนี้ : เซ่นไหว้ (ทำลาย Avatar จาก Avatar Zone ลงนรก)",
    cost: 1,
    gem: 2,
    power: 1,
    symbol: Symbol.Animal,
    color: Color.Red,
  },
  {
    name: "พระพรหม",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-008",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) เซ่นไหว้ (ทำลาย Avatar จาก Avatar Zone ลงนรก)  Avatar ฝ่ายเรา 1 ใบ : อัญเชิญ จุติ Avatar จากนรกของเราที่มี Symbol เดียวกับใบที่ เซ่นไหว้ ไป แต่ชื่อไม่ซ้ำกับใบที่ เซ่นไหว้ไป Cost ไม่เกิน 8 ลงบน Avatar Zone ฝ่ายเรา",
    cost: 8,
    gem: 2,
    power: 6,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "มีมมิจัง ไอดอลหน้าใหม่",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-009",
    rare: Rarity.R,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : เลือก Avatar ที่ติดชื่อ \"โอตะ\" จาก Deck 1 ใบ มาสวมใส่ให้ Avatar ใบนี้ จากนั้นสับ Deck",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "โอตะ รุ่นก่อตั้ง",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-010",
    rare: Rarity.C,
    mainEffect:
      "เทิร์นละครั้ง เลือกปฏิบัติ\n\n1) นำการ์ดใบนี้ที่อยู่ใน Avatar Zone ไปสวมใส่ให้ Avatar ชื่อ\"ไอดอล\" บน Avatar Zone ฝ่ายเรา\n\n2) อัญเชิญการ์ดใบนี้ที่อยู่ในสภาพสวมใส่ไปที่ Avatar Zone\n\nเมื่อ Avatar ชื่อ \"ไอดอล\" บนสนามจะถูกทำลายสามารถทำลายการ์ดใบนี้ที่อยู่ในสภาพสวมใส่บนสนามแทนได้",
    cost: 1,
    gem: 4,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "แม่ศรีนวล",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-011",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : นำ Avatar \"ลูกแม่ศรีนวล\" หรือ \"พ่อบุญใหญ่\" จาก Deck ขึ้นมือได้ 1ใบ หลังจากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Animal,
    color: Color.Blue,
  },
  {
    name: "แมลงปอแจ็ค",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-012",
    rare: Rarity.R,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : ทำลายการ์ด Land Magic 1 ใบบน Land Magic Zone หลังจากนั้นนำ Land Magic 1 ใบจาก Deck เรามาเล่นบน Land Magic Zone หลังจากนั้นสับ Deck",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "แมลงปอ เปื้อนรังสี",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-013",
    rare: Rarity.C,
    mainEffect: "คำสั่งเสีย (เมื่อAvatarตัวนี้ถูกทำลาย) : ทำลาย MAGIC บนสนาม 1ใบ",
    cost: 0,
    gem: 2,
    power: 1,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "ซันนี่",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-014",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง Avatar \"กุ่ย\" \"ฮอล\" \"นาย\" บน Avatar Zone ฝ่ายเรา POWER+1",
    cost: 2,
    gem: 4,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "เอเลี่ยนแสงสีฟ้า",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-015",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) ทิ้งการ์ดบนมือ 1 ใบ เลือก Avatar บนสนามอีกฝ่าย 1 ใบ : ทอยเหรียญ 1 ครั้ง ออกหัว ทำลาย Avatar ตัวนั้น , ออกก้อย ทำลาย Avatar ใบนี้",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: Symbol.Alien,
    color: Color.Blue,
  },
  {
    name: "ฤษี โคบุตร",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-016",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เมื่อมีการใช้ Magic {Symbol ฤษี}: เลือก Avatar 1 ใบบนสนาม POWER +1",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: Symbol.Hermit,
    color: Color.Blue,
  },
  {
    name: "แรงงานทาสออฟฟิศ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-017",
    rare: Rarity.C,
    mainEffect: "อัตโนมัติ ในช่วง End Phase : นำ Avatar ใบนี้จาก Avatar Zone ไปไว้ใต้ Deck",
    cost: 1,
    gem: 3,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "ธอร์ เทพเจ้าสายฟ้า แห่ง แอสการ์ด",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-018",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ หลังจากที่การ์ดใบนี้ทำลาย Avatar จากการต่อสู้สำเร็จ : ทำลาย Avatar 1 ใบบนสนามอีกฝ่ายที่มี POWER  X ( X จะเท่ากับผลต่างของ POWER ใบนี้และใบที่ถูกทำลายจากการต่อสู้ )",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: Symbol.God,
    color: Color.Purple,
  },
  {
    name: "โอดิน พ่อทุกสถาบัน แห่ง แอสการ์ด",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-019",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ(เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) ธรณีสูบ 9 ใบ : นำ Avatar {symbol เทพ} 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 5,
    gem: 4,
    power: 4,
    symbol: Symbol.God,
    color: Color.Purple,
    ex: "Only #1",
  },
  {
    name: "นินจินแมน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-020",
    rare: Rarity.C,
    mainEffect: "อัตโนมัติ ในช่วงเริ่ม Main Phase ของเรา : จั่วการ์ดตามจำนวน Modification Magic ที่่สวมใส่ให้การ์ดใบนี้",
    cost: 6,
    gem: 2,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "กัปตัน ไกร",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-021",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) ทิ้งการ์ดทั้งหมดบนมือของเรา เลือก Avatar 1 ใบบนสนามฝ่ายตรงข้าม : นำ Avatar ใบนั้นกลับขึ้นมือ",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "แบงค์ ผู้รู้ความจริง",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-022",
    rare: Rarity.R,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สอดแนม (แสดงการ์ดใบบนสุดของ Deck ) 3 ใบของเรา เรียงลำดับตามใจชอบ",
    cost: 2,
    gem: 1,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "40ดีกรีแมน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-023",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : อีกฝ่ายต้องเป็นผู้เลือกเป้าหมายในการโจมตีแทนเจ้าของการ์ด",
    cost: 4,
    gem: 1,
    power: 6,
    symbol: Symbol.Human,
    color: Color.Green,
    ex: "โดนใจ",
  },
  {
    name: "เสามงคล",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-024",
    rare: Rarity.R,
    mainEffect:
      "ต่อเนื่อง การ์ดใบนี้โจมตีไม่ได้\n\nต่อเนื่อง ในช่วง Draw Phase หลังจากการจั่วการ์ดปกติใน Draw Phase : จั่วการ์ด 1 ใบ",
    cost: 5,
    gem: 2,
    power: 3,
    symbol: Symbol.Tree,
    color: Color.Green,
  },
  {
    name: "ซินแส",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-025",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ  (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : นำ Avatar \"เสามงคล\" 1 ใบ จาก Deck เรา ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 3,
    gem: 3,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "ชุ่ย โจรสุสาน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-026",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : ผู้เล่นทุกคนเลือกการ์ดจากนรกอีกฝ่าย 5 ใบ กลับเข้า Deck เจ้าของการ์ด แล้วสับ Deck",
    cost: 5,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "พยาบาล เอ๋",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-027",
    rare: Rarity.R,
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ ไม่ถูกทำลายจากการถูกโจมตี : สุ่มคว่ำ LIFE Card ของเราได้ 1 ใบ",
    cost: 6,
    gem: 1,
    power: 5,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "สตีฟ Tank Ranger",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-028",
    rare: Rarity.C,
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ นำ Avatar ใบนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา\n\nAvatar \"รถถัง\" ที่สวมใส่การ์ดใบนี้ POWER +2\n\nใน Battle Phase: Avatar ชื่อ \"รถถัง\" ที่สวมใส่การ์ดใบนี้จะต้องโจมตี ถ้าโจมตีได้",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "รถถัง B66 - เอ็กซ์เซลเซอร์",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-029",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง ถ้าไม่มี Avatar สวมใส่ Avatar ตัวนี้ จะไม่สามารถโจมตีได้ และ ไม่สามารถใช้ Avatar ชื่อซ้ำกันในการสวมใส่การ์ดใบนี้",
    cost: 4,
    gem: 1,
    power: 5,
    symbol: Symbol.Robot,
    color: Color.Green,
  },
  {
    name: "ป้าข้างบ้าน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-030",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 1,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "ตู้เย็นเบอร์ 1",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-031",
    rare: Rarity.R,
    mainEffect: "",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "แมลงปอ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-032",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 3,
    power: 0,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "ผู้เจริญระดับ 4",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-033",
    rare: Rarity.R,
    mainEffect: "",
    cost: 5,
    gem: 0,
    power: 5,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ผีทีวี",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-034",
    rare: Rarity.C,
    mainEffect: "",
    cost: 2,
    gem: 2,
    power: 3,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "พุ่มไม้กินคน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-035",
    rare: Rarity.C,
    mainEffect: "",
    cost: 2,
    gem: 1,
    power: 2,
    symbol: Symbol.Tree,
    color: Color.Green,
  },
  {
    name: "ต้นมะม่วง",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-036",
    rare: Rarity.C,
    mainEffect: "",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Tree,
    color: Color.Green,
  },
  {
    name: "มาวิน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-037",
    rare: Rarity.R,
    mainEffect: "",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "หมาฟู",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-038",
    rare: Rarity.C,
    mainEffect: "",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: Symbol.Animal,
    color: Color.Green,
  },
  {
    name: "วานร ละโว้",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-039",
    rare: Rarity.C,
    mainEffect: "",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Green,
  },
  {
    name: "โลทัน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT02-040",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 2,
    gem: 2,
    power: 3,
    symbol: Symbol.Giant,
    color: Color.Green,
  },
  {
    name: "ช่วยโลกใบนี้ไว้",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-041",
    rare: Rarity.R,
    mainEffect:
      "หงาย LIFE ของเราทุกใบ : ในเทิร์นนี้ Avatar {symbol เปรต} ที่เราอัญเชิญลงบน Avatar Zone ฝ่ายเราจะได้รับความามารถดังต่อไปนี้\n\n-ไม่รับผลความสามารถของการ์ดทุกประเภท\n\n-ได้รับ เตะไข่ โดยที่ความสามารถ โล่มนุษย์ จะไม่สามารถใช้ได้\n\nโดยที่ความสามารถทั้ง 2 จะคงอยู่จนจบเทิร์นที่เล่นการ์ดใบนี้",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Pret,
  },
  {
    name: "ประชามติ",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-042",
    rare: Rarity.C,
    mainEffect: "เปลี่ยน Avatar ทุกใบบนสนามเราเป็นสภาพนอน เลือก Avatar 1 ใบบนสนามที่ POWER ต่ำกว่าผลรวมของ Avatar ที่อยู่ในสภาพนอน : ทำลาย Avatar ที่เลือกนั้น",
    subtype: MagicSubtype.Normal,
    cost: 0,
    symbol: Symbol.Soldier,
  },
  {
    name: "ฉุบสั่งตาย",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-043",
    rare: Rarity.UR,
    mainEffect: "เป่ายิ้งฉุบกับฝ่ายตรงข้าม : ผู้ชนะ เลือกทำลาย Avatar บนสนาม 1 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ด่านลอย",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-044",
    rare: Rarity.R,
    mainEffect: "เลือกค่า Cost 1 ค่า (0-9) : สุ่มการ์ดบนมืออีกฝ่ายถ้าใบที่เลือกนั้นเป็น Avatar ที่มีค่า Cost ตรงกับที่เลือก ส่งการ์ดใบนั้นลงนรก",
    subtype: MagicSubtype.Normal,
    cost: 0,
    symbol: Symbol.Mage,
  },
  {
    name: "ความกล้าหาญ",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-045",
    rare: Rarity.C,
    mainEffect: "เลือก Avatar บนสนามเรา 1 ใบ POWER +4 และจะถูกทำลายในตอน End Phase",
    subtype: MagicSubtype.Normal,
    cost: 4,
    symbol: Symbol.Mage,
  },
  {
    name: "ร้อนมากก็เปิดหน้าต่างสิว๊ากกกก",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-046",
    rare: Rarity.C,
    mainEffect: "เลือก Avatar อีกฝ่าย 1 ใบ : นำการ์ดใบนั้นขึ้นมือ",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "แมลงปอทอด",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-047",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เซ่นไหว้ (ทำลาย Avatar จาก Avatar Zone ลงนรก) Avatar {symbol แมลง} 1 ใบ : จั่วการ์ดจาก Deck 3 ใบ แต่เทิร์นนี้จะสั่งโจมตีได้แค่ Avatar {symbol แมลง}",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Insect,
  },
  {
    name: "กระแสอัปมงคล",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-048",
    rare: Rarity.R,
    mainEffect: "ทำให้ความสามารถการ์ดบน Avatar Zone อีกฝ่ายทั้งหมดไร้ผลจนจบเทิร์น",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "กระแสสิริมงคล",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-049",
    rare: Rarity.R,
    mainEffect: "เมื่ออีกฝ่ายประกาศโจมตี : จั่วการ์ดตามจำนวน Avatar ที่อีกฝ่ายโจมตี ทั้งหมด ตัวละ 1 ใบ",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "เคี้ยวเพื่อนเธอซะ",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-050",
    rare: Rarity.R,
    mainEffect: "เมื่อมี Avatar อัญเชิญลงมาบน Avatar Zone : เซ่นไหว้ (ทำลายจาก Avatar Zone ลงนรก) Avatar บน Avatar Zone เรากี่ใบก็ได้ อัญเชิญ Avatar จากบนมือเราตามค่า GEM ของ Avatar ที่ถูกเซ่นไหว้",
    subtype: MagicSubtype.React,
    cost: 3,
    symbol: Symbol.Animal,
  },
  {
    name: "ถวาย",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-051",
    rare: Rarity.R,
    mainEffect: "เมื่อ Avatar จะถูกทำลาย ทิ้งการ์ดทั้งหมดบนมือเรา : Avatar ใบนั้นจะไม่ถูกทำลาย",
    subtype: MagicSubtype.React,
    cost: 0,
    symbol: Symbol.Hermit,
  },
  {
    name: "เอากล้วยมานี่ย์ !!!!!!",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-052",
    rare: Rarity.C,
    mainEffect: "เมื่อ Avatar อีกฝ่ายประกาศโจมตี Avatar ฝ่ายเรา เลือก Avatar อีกฝ่าย 1 ใบ : POWER -2 จนจบเทิร์น",
    subtype: MagicSubtype.React,
    cost: 3,
    symbol: Symbol.Mage,
  },
  {
    name: "ฟ้องครู",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-053",
    rare: Rarity.C,
    mainEffect: "เมื่ออีกฝ่ายประกาศโจมตี Avatar ของเรา : เลือก Avatar ใบอื่นที่ไม่ใช้เป้าหมายการโจมตี 1 ใบ บนสนามฝ่ายเรา นำ POWER ของ Avatar ใบนั้น มาเพิ่มให้ Avatar ที่ถูกเป็นเป้าหมายโจมตีจนจบการต่อสู้",
    subtype: MagicSubtype.React,
    cost: 0,
    symbol: Symbol.Mage,
  },
  {
    name: "ไปเลยมอนตี้",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-054",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อ Avatar อีกฝ่ายประกาศโจมตี : Avatar ที่โจมตี POWER ลดลงตามจำนวนการ์ดบนสนามและบนมือฝ่ายเราใบละ 2",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Animal,
  },
  {
    name: "ประกันชั้นต่ำ",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-055",
    rare: Rarity.R,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ จะไม่ถูกทำลายจากการโจมตี 1 ครั้ง หลังจากโดนโจมตีแล้ว ส่งการ์ดใบนี้ลงนรก",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "ขวานเงิน",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-056",
    rare: Rarity.C,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ POWER +2 และ ความสามารถของ Avatar ที่สวมใส่การ์ดใบนี้ที่มีอยู่ทั้งหมดจะไร้ผล",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Human,
  },
  {
    name: "ช็อตกัน นัยนาวุธ",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-057",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อ Avatar ที่สวมใส่การ์ดใบนี้ ทำลาย Avatar ด้วยการต่อสู้สำเร็จ : หงาย LIFE Card ใบบนสุดของอีกฝ่าย",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: Symbol.Hell,
    ex: "Only #1",
  },
  {
    name: "ประตูนรก",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-058",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้ง Avatar {Symbol นรก} 1 ใบจากบนมือ : อัญเชิญ Avatar \"นายนิรยบาล\" ค่า Cost ไม่เกิน 4 จาก นรกฝ่ายเรา 1 ใบ ลงบน Avatar Zone ฝ่ายเรา",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Hell,
    ex: "Only #1",
  },
  {
    name: "เทศกาลแมลงปอบุก",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-059",
    rare: Rarity.C,
    mainEffect: "Avatar {symbol แมลง} ทุกใบ ได้รับ สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Insect,
  },
  {
    name: "แอสการ์ดคือสถานที่ไม่ใช่ผู้คน",
    type: CardType.Magic,
    soi: 1,
    print: "BT02-060",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "เปลี่ยน Symbol ของ Avatar ทุกใบบน Avatar Zone เป็น Symbol {เทพ}\n\nเทิร์นละครั้ง สั่งใช้ ทิ้งการ์ด 1 ใบ แล้วเลือก Avatar 1 ตัว บน Avatar Zone ฝั่งตรงข้ามที่ Cost ไม่เกิน 3 และมีสภาพนอน : เปลี่ยนการควบคุมมาบน Avatar Zone ฝ่ายเราในสภาพนอน จนจบเทิร์น",
    subtype: MagicSubtype.Land,
    cost: 4,
    symbol: Symbol.God,
  }
]);
