import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_BT03: Card[] = createCards([
  {
    name: "พระลักษมี",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-001",
    rare: Rarity.C,
    mainEffect:
      "เมื่อการ์ดใบนี้ถูกใช้เป็น Cost เพื่ออัญเชิญ Avatar \"พระนารายณ์\" : POWER + 3 ให้กับ Avatar ที่อัญเชิญ จนจบเทิร์น\n\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {symbol เทพ} เท่านั้น",
    cost: 1,
    gem: 4,
    gemColor: Color.Red,
    power: 1,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "นางอัปสร",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-002",
    rare: Rarity.R,
    mainEffect:
      "อัตโนมัติ เมื่อการ์ดใบนี้สั่งโจมตี : ฝ่ายตรงข้ามไม่สามารถสั่งใช้งาน React Magic จนจบการต่อสู้\n\n#การ์ดใบนี้นับเป็นชื่อ \"พระนารายณ์\"",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "อินทรีย์แมน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-003",
    rare: Rarity.R,
    mainEffect:
      "จุติ : นำ Modification Magic จากใน Deck ฝ่ายเรา 1 ใบมาสวมให้กับ Avatar ใบนี้หลังจากนั้นสับ Deck\n\nPOWER ของ Avatar ใบนี้จะเพิ่มตาม Modification Magic ทั้งหมดบนสนาม ใบละ 1",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "หุ่นนักรบผู้กล้า : ไมเกรน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-004",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ : สอดแนม 5 ใบ เลือกการ์ด \"อาวุธหุ่นนักรบผู้กล้า\" 1 ใบจากที่ สอดแนม และนำขึ้นมือ การ์ดที่เหลือเรียงและนำไว้ใต้ Deck\n\nเทิร์นละครั้ง อัตโนมัติ เมื่อมีการใช้ Modification Magic \"อาวุธหุ่นนักรบผู้กล้า\" : จั่วการ์ด 1 ใบ",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "โดรนสอดแนมผู้กล้า : เก๊าท์",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-005",
    rare: Rarity.R,
    mainEffect: "จุติ และ บน Avatar Zone ฝ่ายเรา มี Avatar {symbol หุ่นยนต์} \"ผู้กล้า\" : สอดแนม 1 ใบของ Deck อีกฝ่าย ถ้าเป็น Avatar นำใบนั้นลงนรก แต่ถ้าไม่ใช่ ให้นำไว้ใต้ Deck",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "ยานเกราะผู้กล้า : ไดบาเรีย",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-006",
    rare: Rarity.C,
    mainEffect:
      "ถ้าการ์ดใบนี้ถูกใช้เป็น Cost ในการอัญเชิญ : จั่วการ์ด 1 ใบ\n\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {Symbol หุ่นยนต์}  ที่มีสีของ Avatar เป็นสีแดงเท่านั้น",
    cost: 0,
    gem: 4,
    gemColor: Color.Red,
    power: 0,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "อากาศยานผู้กล้า : แอร์ซิด รีฟลักซ์",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-007",
    rare: Rarity.C,
    mainEffect: "อัตโนมัติ สั่งใช้ เมื่อ \"หุ่นนักรบผู้กล้า : ไม้ท์เกรน\" ที่เราควบคุมอยู่บนสนามกำลังจะถูกทำลาย : ทำลายการ์ดใบนี้แทนได้",
    cost: 1,
    gem: 2,
    power: 1,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "กาฬสินธุ์แมน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-008",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้ทำลาย Avatar อีกฝ่ายจากการต่อสู้สำเร็จ : POWER ของการ์ดใบนี้ +1",
    cost: 4,
    gem: 3,
    gemColor: Color.Red,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "จีสัส",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-009",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง การ์ดใบนี้สามารถสั่งโจมตีได้ เมื่อเราไม่มีการ์ดบนมือเหลืออยู่",
    cost: 4,
    gem: 2,
    power: 5,
    symbol: Symbol.Animal,
    color: Color.Red,
    ex: "โดนใจ",
  },
  {
    name: "ไดโนกาฬสินธุ์ - ภูเวียงสิรินเน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-010",
    rare: Rarity.R,
    mainEffect: "จุติ : เลือกหยิบการ์ด Avatar {symbol กะปอม} Cost 3 หรือต่ำกว่า สูงสุด 4 ใบจากนรกของฝ่ายเรากลับเข้า Deck แล้วสับ หลังจากนั้นจั่วการ์ด 1 ใบ และ POWER ของการ์ด ใบนี้จะเพิ่มเท่ากับจำนวนการ์ดที่นำเข้า Deck ใบละ 1 จนจบเทิร์น",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: Symbol.Lizard,
    color: Color.Blue,
  },
  {
    name: "ไดโนกาฬสินธุ์ - กินรีมิมัส",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-011",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ สอดแนม 5 ใบ : เลือก Avatar {symbol กะปอม} 1 ใบที่มี Cost 3 หรือต่ำกว่า จากที่ สอดแนม อัญเชิญลง Avatar zone ฝ่ายเรานำที่เหลือกลับเข้า Deck แล้วสับ",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Lizard,
    color: Color.Blue,
  },
  {
    name: "ไดโนกาฬสินธุ์ - อิสานโนซอรัส",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-012",
    rare: Rarity.C,
    mainEffect:
      "เมื่อถูกทิ้งเป็นค่า Cost ให้กับ Avatar {symbol กะปอม} : สอดแนม 1 ใบ แล้วสามารถเลือกได้ว่า ให้การ์ดใบนั้นอยู่ที่เดิม หรือไว้ใต้ Deck\n\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {symbol กะปอม} เท่านั้น]",
    cost: 1,
    gem: 4,
    gemColor: Color.Blue,
    power: 1,
    symbol: Symbol.Lizard,
    color: Color.Blue,
  },
  {
    name: "ไดโนกาฬสินธุ์ - สัตยาซอรัส",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-013",
    rare: Rarity.C,
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้อยู่บน Avatar Zone POWER + 1 ให้ Avatar {symbol กะปอม} ทุกใบบน Avatar Zone ฝ่ายเรา",
    cost: 1,
    gem: 2,
    power: 1,
    symbol: Symbol.Lizard,
    color: Color.Blue,
  },
  {
    name: "โอตะปุส",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-014",
    rare: Rarity.C,
    mainEffect:
      "เทิร์นละครั้ง เลือกปฏิบัติ\n\n1) นำการ์ดใบนี้ที่อยู่ใน Avatar Zone ไปสวมใส่ให้ Avatar ชื่อ\"ไอดอล\" บน Avatar Zone ฝ่ายเรา\n\n2) อัญเชิญการ์ดใบนี้ที่อยู่ในสภาพสวมใส่ไปที่ Avatar Zone\n\nคำสั่งเสีย : จั่วการ์ด 1 ใบ",
    cost: 1,
    gem: 2,
    power: 1,
    symbol: Symbol.Fish,
    color: Color.Blue,
  },
  {
    name: "ตุ๊กตารัททาทุย",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-015",
    rare: Rarity.R,
    mainEffect:
      "เมื่อการ์ดใบนี้ถูกทิ้งเป็นค่า Cost ให้กับ Avatar \"รัททาทุย\" : อัญเชิญ Avatar รัททาทุย ที่มี Cost 1 GEM 1 POWER 1 1ใบ จากใน Deck ลงบน Avatar Zone ฝ่ายเรา\n\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {symbol รัททาทุย} เท่านั้น",
    cost: 1,
    gem: 3,
    power: 0,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "รัททาทุยแม่วัว",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-016",
    rare: Rarity.C,
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้อยู่บน Avatar Zone  POWER +1 ให้ Avatar {symbol รัททาทุย}  ใบอื่นบนสนามฝ่ายเรา",
    cost: 1,
    gem: 2,
    power: 0,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "มนุษย์รัททาทุย",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-017",
    rare: Rarity.SR,
    mainEffect: "POWER ของการ์ดใบนี้จะเพิ่มขึ้นตามจำนวน Avatar {symbol รัททาทุย} บน Avatar Zone ฝ่ายเราตัวละ 1",
    cost: 4,
    gem: 1,
    power: 1,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "จ่างู อสรพิษพิฆาตจักรกล",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-018",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar {symbol หุ่นยนต์} : ทำลาย Avatar ใบที่เป็นเป้าการโจมตี",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ด็อคเตอร์แบงค์",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-019",
    rare: Rarity.C,
    mainEffect: "จุติ ทำลาย Avatar \"ศาลพระภูมิ\" บน Avatar Zone ฝ่ายเรา 1 ใบ : อัญเชิญ Avatar {Symbol ผี} จากในนรกของฝ่ายเรา 1 ใบ",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "แดรกคูลา",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-020",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ : Avatar ใบนี้ ได้รับ \"เมื่อ Avatar ใบนี้ ถูกทำลาย ในเทิร์นถัดมาของเรา อัญเชิญ Avatar ใบนี้จากนรกลงบน Avatar Zone ฝ่ายเราในช่วง Battle Phase ของเทิร์นนั้น\"",
    cost: 6,
    gem: 2,
    power: 4,
    symbol: Symbol.Ghost,
    color: Color.Purple,
    ex: "Only #1",
  },
  {
    name: "อีแป๋ม ผีกระสือ RGB",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-021",
    rare: Rarity.C,
    mainEffect: "คำสั่งเสีย จากบน Avatar Zone เลือก Avatar บนสนามอีกฝ่าย 1 ใบ : นำการ์ดใบนี้ไปสวมให้กับ Avatar ใบนั้น Avatar ใบที่สวมการ์ดใบนี้ จะถูกเปลี่ยน Symbol เป็น {Symbol ผี} และ POWER - 2",
    cost: 2,
    gem: 0,
    power: 0,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "แม่นาค พระประแดง",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-022",
    rare: Rarity.R,
    mainEffect: "เมื่อการ์ดใบนี้ถูกอัญเชิญ เลือกการ์ดในนรกของฝ่ายตรงข้าม 1 ใบ : นำการ์ดใบนั้นกลับเข้าใต้ Deck ฝ่ายตรงข้าม ถ้าทำสำเร็จ เลือก Avatar 1ใบ ของอีกฝ่าย POWER - 2",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "โลกิ เทพแอสการ์ดแห่งการหลอกลวง",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-023",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "อัตโนมัติ ในทุกๆ End Phase : การ์ดใบนี้จะย้ายไปอยู่ใน Avatar Zone ของฝ่ายตรงข้าม\n\nอัตโนมัติ เมื่อการ์ดใบนี้เปลี่ยนการควบคุม : Avatar ตัวนี้ไม่สามารถสั่งโจมตีได้",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Purple,
    customLimit: 2,
  },
  {
    name: "บัลเดอร์ เทพแสง แห่งแอสการ์ด",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-024",
    rare: Rarity.R,
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง ถ้า Avatar ตัวนี้จะถูกทำลาย : ธณีสูบ 9 ใบ แทนการทำลายได้",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.God,
    color: Color.Purple,
  },
  {
    name: "ฮามดัล เทพผู้รู้เห็น แห่งแอสการ์ด",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-025",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้อยู่บน Avatar Zone การ์ดใบบนสุดของ Deck ทั้ง2ฝ่าย จะถูกหงายหน้า",
    cost: 4,
    gem: 0,
    power: 5,
    symbol: Symbol.God,
    color: Color.Purple,
  },
  {
    name: "แบมบูจัง ไอดอลสองขั้ว",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-026",
    rare: Rarity.R,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทำลายการ์ด \"โอตะ\" ที่สวมใส่อยู่ให้กับการ์ด Avatar \"ไอดอล\" บน Avatar Zone ฝ่ายเรา 1 ใบ  : ทำลายการ์ดบนสนาม 1 ใบ",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "แมลงปอมีพิษ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-027",
    rare: Rarity.C,
    mainEffect: "คำสั่งเสีย (เมื่อAvatarตัวนี้ถูกทำลาย): ทำลาย Avatar ที่ Cost เท่ากับ 4 หรือต่ำกว่า บน Avatar Zone 1 ใบ",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: Symbol.Insect,
    color: Color.Purple,
    customLimit: 1,
  },
  {
    name: "ราชาอาณาจักรของแพง  พระเจ้านิโคไล",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-028",
    rare: Rarity.UR,
    variants: [Rarity.SCR, Rarity.PR, Rarity.CBR],
    mainEffect: "ต่อเนื่อง Avatar ใบนี้จะไม่ถูกทำลายจากการต่อสู้ กับ Avatar ที่ Cost น้อยกว่าการ์ดใบนี้",
    cost: 4,
    gem: 3,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "ทหารอาณาจักรของแพง",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-029",
    rare: Rarity.C,
    mainEffect:
      "ต่อเนื่อง Avatar ทุกตัวบนสนามอีกฝ่าย Cost -1\n\nต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี Avatar \"ราชาอาณาจักรของแพง  พระเจ้านิโคไล\" POWER ของการ์ดใบนี้จะเป็น 2",
    cost: 0,
    gem: 2,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "ช่างตัดเสื้อ อาณาจักรของแพง",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-030",
    rare: Rarity.R,
    mainEffect: "จุติ เลือก Avatar \"ราชาอาณาจักรของแพง พระเจ้านิโคไล\" บน Avatar Zone ฝ่ายเรา 1 ใบ : Avatar ตัวนั้นได้รับ Cost +1 และ POWER +1",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "จอมเวทย์ดอคู่",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-031",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ : ทำลาย Modification Magic บน Magic Zone 1 ใบ",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "ตั๊กแตนพันธ์ุ X",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-032",
    rare: Rarity.R,
    mainEffect:
      "ต่อเนื่อง ตราบเท่า Avatar ใบนี้อยู่บน Avatar Zone จะนับเป็น Avatar {symbol แมลง} ด้วย\n\nต่อเนื่อง Avatar ใบนี้จะ เพื่ม POWER ตามจำนวน Avatar {symbol แมลง} บน Avatar Zone ใบละ 1",
    cost: 5,
    gem: 3,
    power: 3,
    symbol: Symbol.Alien,
    color: Color.Green,
  },
  {
    name: "แมลงปอ บรรพบุรุษ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-033",
    rare: Rarity.C,
    mainEffect: "คำสั่งเสีย (เมื่อAvatarใบนี้ถูกทำลาย) เลือก Avatar {symbol แมลง} Cost ไม่เกิน 4 และไม่ได้ชื่อ แมลงปอ บรรพบุรุษ จากนรกของฝ่ายเรา : อัญเชิญแบบ จุติ บน Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 3,
    gemColor: Color.Blue,
    power: 1,
    symbol: Symbol.Insect,
    color: Color.Green,
  },
  {
    name: "พาลี",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-034",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ต่อสู้ : Avatar ที่ต่อสู้ด้วย POWER - 2 และ Avatar ตัวนี้ POWER + 2 จนจบการต่อสู้นั้น",
    cost: 7,
    gem: 2,
    power: 4,
    symbol: Symbol.Animal,
    color: Color.Green,
  },
  {
    name: "นางมณโฑ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-035",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ เลือก Avatar {symbol ยักษ์} ที่ POWER ไม่เกิน 3 ในนรกฝ่ายเรา 1 ใบ : อัญเชิญ Avatar ใบนั้นลงบน Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "จอน ชาวดาวอังคาร",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-036",
    rare: Rarity.C,
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 4,
    symbol: Symbol.Alien,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "แมลงปอนา",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-037",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "ตัวอ่อนรัททาทุย",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-038",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 3,
    power: 0,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "จอมเวทย์ดำ",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-039",
    rare: Rarity.R,
    mainEffect: "",
    cost: 3,
    gem: 1,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "มหิตัน",
    type: CardType.Avatar,
    soi: 1,
    print: "BT03-040",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 3,
    gem: 3,
    power: 3,
    symbol: Symbol.Giant,
    color: Color.Green,
  },
  {
    name: "เก็บค่าคุ้มครอง",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-041",
    rare: Rarity.R,
    mainEffect: "เมื่อมีการ์ด Land Magic หงายหน้าอยู่บน Land Magic Zone ทิ้งการ์ดบนมือ 1 ใบ : จั่วการ์ด 2 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ตู้โชว์ไอดอล",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-042",
    rare: Rarity.C,
    mainEffect: "สามารถใช้การ์ดใบนี้ได้ต่อเมื่อควบคุม Avatar \"ไอดอล\" บน Avatar Zone ฝ่ายเราเท่านั้น : นำการ์ด Avatar \"โอตะ\" จากใน Deck ฝ่ายเรา 1 ใบขึ้นมือ จากนั้นสับ Deck",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "ผมขอค้าน !!",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-043",
    rare: Rarity.C,
    mainEffect: "เลือก Avatar 1 Symbol : สุ่มเลือกการ์ดบนมือของอีกฝ่าย 1 ใบ ถ้าใบที่เลือกเป็น Avatar ที่มี Symbol ตรงกับที่ประกาศไปข้างต้นให้ทิ้งการ์ด Avatar ใบนั้นลงนรก",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "เยี่ยวรดศาล",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-044",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อ Avatar Zone ฝ่ายเรามี Avatar {symbol คน} ที่มีค่า Cost เป็น 3 หรือ มากกว่า : อัญเชิญแบบ จุติ Avatar {Symbol ผี} ค่า Cost ไม่เกิน 4 จาก Deck เรา ลงบน Avatar Zone ฝ่ายเรา หลังจากนั้นสับ Deck",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Ghost,
  },
  {
    name: "ซุปเปอร์สแน็ค !!",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-045",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เลือก Avatar {symbol สัตว์} 1 ใบ : POWER + 6 แล้วทำลาย Avatar ตัวนั้นในช่วง End phase",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Animal,
  },
  {
    name: "จมน้ำ",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-046",
    rare: Rarity.C,
    mainEffect: "ผู้เล่นทุกคนต่างเลือก Avatar บน Avatar Zone ของตนเอง 1 ใบ นำกลับเข้าใต้ Deck เจ้าของ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ไม่เจ้ายังไม่พร้อม",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-047",
    rare: Rarity.R,
    mainEffect: "เมื่อมี Avatar อัญเชิญลงมาบน Avatar Zone : เปลี่ยน Avatar ใบนั้นเป็นสภาพนอน",
    subtype: MagicSubtype.React,
    cost: 2,
    symbol: Symbol.Hermit,
  },
  {
    name: "เอาเสื้อมาหมุนๆแล้วตบ",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-048",
    rare: Rarity.C,
    mainEffect: "นำการ์ด 1 ใบจากบนมือกลับเข้า Deck จากนั้นสับ Deck : ทำลาย Avatar {Symbol แมลง} บนสนามอีกฝ่าย 1 ใบ",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "คว้าปืนมายิงหมี",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-049",
    rare: Rarity.C,
    mainEffect: "เมื่อ Avatar ฝ่ายเราต่อสู้ เลือก Modification Magic จากในนรกฝ่ายเรา 1 ใบ : นำการ์ดใบนั้นขึ้นมือ และ Avatar ที่ต่อสู้ด้วย POWER - 1",
    subtype: MagicSubtype.React,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "งับ",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-050",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อ Avatar ฝ่ายตรงข้ามโจมตี : สอดแนม (เปิดการ์ดใบบนสุดของ Deck) 2 ใบ : เลือกการ์ด Avatar {Symbol กะปอม} 1 ใบ จากที่สอดแนม และนำขึ้นมือ ถ้ามีการนำการ์ดจากความสามารถข้างต้นขึ้นมือ ทำลาย Avatar ที่สั่งโจมตีอยู่ ณ ขณะนั้น และ นำการ์ดที่เหลือกลับเข้า Deck แล้วสับ",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Lizard,
  },
  {
    name: "อาวุธหุ่นนักรบผู้กล้า \"อีโบล่า ซอร์ด\"",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-051",
    rare: Rarity.C,
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar {Symbol หุ่นยนต์} เท่านั้น\n\nAvatar ที่สวมใส่การ์ดใบนี้ POWER + 1 แต่ถ้า Avatar ที่สวมใส่การ์ดใบนี้ชื่อ \"หุ่นนักรบผู้กล้า\" POWER + 3 แทน",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Robot,
  },
  {
    name: "แผนการ : แกงส้มตะปูเสียบ",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-052",
    rare: Rarity.C,
    mainEffect:
      "Avatar ที่สวมใส่การ์ดใบนี้ POWER - 2\n\nถ้า Avatar ที่สวมใส่การ์ดใบนี้ POWER = 0 ทำลาย Avatar ตัวที่สวมใส่ การ์ดใบนี้",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ยาแก้ไอน้ำดำ",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-053",
    rare: Rarity.C,
    mainEffect: "Avatar ที่่สวมใส่การ์ดใบนี้จะไม่รับผลความสามารถในการลด POWER หาก Avatar ที่สวมใส่การ์ดใบนี้ถูกลด POWER อยู่ก่อนหน้า จะเพิ่ม POWER เท่ากับที่ลดไปทั้งหมด",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ขวานไม้เน่าๆเหม็นๆ",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-054",
    rare: Rarity.C,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ Cost -1",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Tree,
  },
  {
    name: "ขวานทอง",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-055",
    rare: Rarity.R,
    mainEffect: "เมื่อ Avatar ที่สวมใส่การ์ดใบนี้ สั่งโจมตี : ผู้ควบคุม Avatar ตัวนั้นๆ จั่วการ์ดจาก Deck  1 ใบ",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.God,
  },
  {
    name: "สายฟ้า วัชระ",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-056",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อ Avatar ที่สวมใส่ โจมตี : ทำลาย Avatar ใบที่ต่อสู้ด้วย",
    subtype: MagicSubtype.Modification,
    cost: 4,
    symbol: Symbol.God,
    ex: "Only #1",
  },
  {
    name: "อาณาจักรของแพง",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-057",
    rare: Rarity.R,
    mainEffect: "สั่งใช้ เมื่อ ผลรวมของ Cost ของ Avatar บน Avatar Zone ของฝ่ายตรงข้ามรวมกันเป็น 4 หรือ น้อยกว่า ทิ้งการ์ดจากบนมือเรา 1 ใบ : นำ \"ราชาอาณาจักรของแพง  พระเจ้านิโคไล\" จากใน Deck ขึ้นมือเรา 1 ใบ หลังจากนั้น สับ Deck",
    subtype: MagicSubtype.Land,
    cost: 4,
    symbol: Symbol.Mage,
  },
  {
    name: "ยุคกาฬสินธุ์โซอิค",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-058",
    rare: Rarity.C,
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ทิ้ง Gem รวมกันให้ได้ 3 หรือมากกว่า : สอดแนม 5 ใบ เลือกหยิบการ์ด Avatar {symbol กะปอม} 1 ใบขึ้นมือ หาก Avatar ใบนั้นมี Cost 3 หรือต่ำกว่า สามารถอัญเชิญลงสนามแทนได้ นำที่เหลือกลับเข้ากองแล้วสับ Deck\n\nถ้าการ์ดนี้ถูก \"สอดแนม\" (ดูการ์ดใบบนสุดของDeck) จาก Avatar {symbol กะปอม} สามารถใช้งานการ์ดใบนี้บน Land Magic Zone",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Tree,
  },
  {
    name: "ราชธานีสามัคคี",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-059",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เลือก Avatar 1 ใบบน Avatar Zone : ได้รับความสามารถ สามัคคี จนจบเทิร์น",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "ปราสาทแดรก",
    type: CardType.Magic,
    soi: 1,
    print: "BT03-060",
    rare: Rarity.R,
    mainEffect:
      "Avatar ชื่อ แดรกคูลา บน Avatar Zone POWER +1\n\nเทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดจากบนมือเรา 1 ใบ และ เลือก แดรกคูลา 1 ใบจากในนรกฝ่ายเรา 1 ใบ : อัญเชิญการ์ดใบนั้นมาบน Avatar Zone ฝ่ายเรา",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Ghost,
  }
]);
