import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_BT05: Card[] = createCards([
  {
    name: "กุ่ย นักเอาตัวรอด",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-001",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "พอดี (จะได้รับความสามารถดังต่อไปนี้เมื่อ Avatar ใบนี้ถูกอัญเชิญมาด้วยการทิ้ง Gem พอดีกับ Cost เท่านั้น)\nสั่งใช้ เมื่อ Avatar ใบนี้จะถูกทำลาย ทิ้งการ์ดบนมือ 1 ใบ : การ์ดใบนี้จะไม่ถูกทำลาย",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "แมลงปอนางพญา",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-002",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "Cost บนมือการ์ดนี้ลดตาม Avatar \"แมลงปอ\" ในนรกเราใบละ 1 \nต่อเนื่อง Avatar ใบนี้เพิ่ม POWER ตามจำนวน Avatar \"แมลงปอ\" ใบอื่น ในสนามใบละ 1\nเทิร์นละครั้ง  เซ่นไหว้  Avatar \"แมลงปอ\" ใบอื่น 1 ใบ : เลือก Avatar \"แมลงปอ\" 1 ใบ ที่ชื่อไม่ซ้ำกับ Avatar ที่ เซ่นไหว้ ด้วยความสามารถนี้ ในนรกเรา อัญเชิญ  จุติ  Avatar ใบนั้นลง Avatar Zone ฝ่ายเรา",
    cost: 10,
    gem: 2,
    power: 5,
    symbol: Symbol.Insect,
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "เบดิเวียร์ อัศวินโต๊ะกลมแห่งความภักดี",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-003",
    rare: Rarity.SR,
    mainEffect: "จุติ : นำการ์ด Magic \"ดาบศักดิ์สิทธิ์\" 1 ใบ จาก Deck เรา ส่งลงนรกเราจากนั้น สับ Deck และสามารถนำ Avatar \"อัศวินโต๊ะกลม\" 1 ใบ จากนรกเรา วางไว้บนสุดของ Deck เรา จากนั้น Avatar ใบนี้ POWER +1 จนจบเทิร์น",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Foreigner,
    color: Color.Red,
  },
  {
    name: "ทริสทัน อัศวินโต๊ะกลมแห่งความแม่นยำ",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-004",
    rare: Rarity.C,
    mainEffect:
      "ถ้า Avatar ใบนี้ ถูกอัญเชิญ ลง Avatar Zone ด้วยความสามารถของ Avatar \"อัศวินโต๊ะกลม\" ทำลายการ์ด 1 ใบ บนสนามฝ่ายตรงข้าม\nต่อเนื่อง ถ้าใน Avatar Zone ฝ่ายเรามี \"อัศวินโต๊ะกลม\" ใบอื่น Avatar ใบนี้ ได้รับ สามัคคี",
    cost: 2,
    gem: 4,
    power: 1,
    symbol: Symbol.Foreigner,
    color: Color.Red,
  },
  {
    name: "เทพารักษ์งมขวาน",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-005",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ : นำ Modification Magic \"ขวาน\" จากใน นรกเรา 1 ใบ ขึ้นมือ",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "หมาแพนดี้",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-006",
    rare: Rarity.C,
    mainEffect:
      "โล่มนุษย์ สามัคคี \nต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้ อยู่ในสภาพนอน POWER ของ Avatar ใบนี้จะเพิ่มขึ้นเท่ากับ Avatar \"\"หมา\"\" และ \"\"แมว\"\" ที่เป็น Symbol สัตว์ ใบอื่น บน Avatar Zone ฝ่ายเรา ใบละ 1",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Red,
  },
  {
    name: "สหายหุ่นผู้กล้า โฟเบีย",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-007",
    rare: Rarity.R,
    mainEffect:
      "จุติ นำ \"โดรนสอดแนมผู้กล้า : เก๊าท์\" , \"ยานเกราะผู้กล้า : ไดบาเรีย\" และ \"อากาศยานผู้กล้า : แอร์ซิด รีฟลักซ์\" \nอย่างละ 1 ใบ จาก นรกเรา กลับเข้า Deck : อัญเชิญ  \"ไมเกรน\" ที่ Cost ไม่เกิน 5 จากใน Deck เรา 1 ใบ ลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck และนำการ์ดใบนี้ไปสวมใส่ให้ Avatar ที่ถูกอัญเชิญมาด้วยความสามารถนี้\nAvatar ที่สวมใส่การ์ดใบนี้ POWER +1",
    cost: 3,
    gem: 2,
    power: 0,
    symbol: Symbol.Foreigner,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "โจอี้ นักบอลขาหัก",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-008",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost ในการอัญเชิญ Avatar สีแดง : POWER +1 ให้กับ Avatar ที่ถูกอัญเชิญจนจบเทิร์น",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Foreigner,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "น้องส้ม ชู้วันชัย",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-009",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost ในการอัญเชิญ Avatar {Symbol เปรต} : Avatar ใบนั้นจะไม่ถูกนำออกจากสนาม ด้วยความสามารถของ Magic Card จนจบเทิร์นถัดไปของ ฝ่ายตรงข้าม",
    cost: 1,
    gem: 4,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "น้องนาว ชู้วันชัย",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-010",
    rare: Rarity.R,
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : หงาย LIFE Card ของเราได้สูงสุด 2 ใบ \nเมื่อจบเทิร์น คว่ำ LIFE Card ที่หงายด้วยความสามารถนี้ \n#ตราบเท่าที่เราควบคุม Avatar {Symbol เปรต} อยู่บน Avatar Zone การ์ดใบนี้จะถือว่ามี Cost 0",
    cost: 2,
    gem: 2,
    gemColor: Color.Red,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "ฤๅษี ภฤคุ",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-011",
    rare: Rarity.UR,
    variants: [Rarity.SCR, Rarity.PR, Rarity.CBR],
    mainEffect:
      "ต่อเนื่อง ตราบเท่าที่อยู่บน Avatar Zone เราสามารถใช้ Normal Magic, Modification Magic และ Land Magic ที่เป็น Symbol ฤษี ในเทิร์นฝ่ายตรงข้ามได้ \nต่อเนื่อง ตราบเท่าที่อยู่บน Avatar Zone ในเทิร์นฝ่ายตรงข้าม เพิ่มเงื่อนไขการใช้  React Magic Symbol ฤษี ในมือเราเป็น \"เมื่อฝ่ายตรงข้าม ประกาศโจมตี , ใช้ความสามารถของ Avatar หรือ ใช้การ์ด Magic สามารถใช้การ์ดนี้ได้\" โดยที่เงื่อนไขเดิมยังคงอยู่",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.Hermit,
    color: Color.Red,
  },
  {
    name: "เจนนี่ อย่าบู้บี้เลขา",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-012",
    rare: Rarity.SR,
    mainEffect: "ต่อเนื่อง ตราบเท่าที่อยู่บน Avatar Zone ผู้เล่นทุกคนไม่สามารถ อัญเชิญ Avatar จากนรกได้",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Red,
    ex: "โดนใจ",
  },
  {
    name: "ผู้เจริญ นาย",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-013",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง ตราบเท่าที่อยู่บน Avatar Zone Avatar {Symbol คน} และ Avatar {Symbol ต้นไม้} ฝ่ายเราทุกใบ ได้รับ สามัคคี",
    cost: 3,
    gem: 4,
    gemColor: Color.Blue,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ลานเซลอต อัศวินโต๊ะกลมแห่งการปฏิวัติ",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-014",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ สอดแนม 2 ใบ : เลือก Avatar \"อัศวินโต๊ะกลม\" 1 ใบ อัญเชิญลง Avatar Zone ฝ่ายเรา นำการ์ดที่เหลือกลับเข้า Deck แล้วสับ\nถ้า Avatar ที่ถูกอัญเชิญด้วยความสามารถนี้ เป็น Avatar สีแดง Avatar \"อัศวินโต๊ะกลม\" ทุกใบบน Avatar Zone เรา POWER +1 จนจบเทิร์น\nถ้า Avatar ที่ถูกอัญเชิญด้วยความสามารถนี้ เป็น Avatar สีฟ้า เราจั่วการ์ด 1 ใบ",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.Foreigner,
    color: Color.Blue,
  },
  {
    name: "กาเวน อัศวินโต๊ะกลมแห่งแสงอาทิตย์",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-015",
    rare: Rarity.C,
    mainEffect:
      "โล่มนุษย์\nต่อเนื่อง POWER +2 ในเทิร์นฝ่ายตรงข้าม",
    cost: 5,
    gem: 3,
    power: 4,
    symbol: Symbol.Foreigner,
    color: Color.Blue,
  },
  {
    name: "โคลัมบัส นักท่องเรือ",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-016",
    rare: Rarity.R,
    mainEffect: "#Avatar ใบนี้ถือเป็น Avatar ทุกสี",
    cost: 2,
    gem: 1,
    power: 4,
    symbol: Symbol.Foreigner,
    color: Color.Blue,
  },
  {
    name: "เจค นักฆ่ามือเก๋า",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-017",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "ลูกฮึด (เมื่อ Avatar ใบนี้ ต่อสู้กับ Avatar ที่มี POWER เท่ากัน และ ไม่มี ลูกฮึด Avatar ใบนี้จะเป็นฝ่ายชนะ)\nอัตโนมัติ เมื่อ Avatar ใบนี้ประกาศโจมตี และ ในนรกเรามีการ์ด ของขวัญที่เมียทิ้งไว้ให้ : สุ่มทิ้งการ์ด 1 ใบบนมือของฝ่ายตรงข้าม\n#เราสามารถควบคุม เจค นักฆ่ามือเก๋า ใน Avatar Zone ได้เพียง 1 ใบเท่านั้น",
    cost: 4,
    gem: 1,
    power: 6,
    symbol: Symbol.Foreigner,
    color: Color.Blue,
    customLimit: 2,
  },
  {
    name: "ของขวัญที่เมียทิ้งไว้ให้",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-018",
    rare: Rarity.C,
    mainEffect: "ถ้าเราควบคุม เจค นักฆ่ามือเก๋า และ ไม่มี Avatar ชื่อของขวัญที่เมียทิ้งไว้ให้ ใน Avatar Zone ฝ่ายเรา สามารถอัญเชิญการ์ดใบนี้จากมือ ได้โดยที่ไม่ต้องจ่าย Cost",
    cost: 2,
    gem: 0,
    power: 1,
    symbol: Symbol.Animal,
    color: Color.Blue,
  },
  {
    name: "บอสทุเรียน",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-019",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost เพื่ออัญเชิญ Avatar สีฟ้า : สอดแนม 1 ใบ ถ้าการ์ดใบนั้นเป็น Avatar Symbol เดียวกับ Avatar ที่ถูกอัญเชิญ นำการ์ดใบนั้นขึ้นมือ ถ้าไม่ใช่นำการ์ดใบนั้นไว้ที่เดิม",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Tree,
    color: Color.Blue,
  },
  {
    name: "บึงทมิฬ  People - คุณเงือกมาวิน",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-020",
    rare: Rarity.UR,
    mainEffect: "จุติ นำ Avatar {Symbol ปลา} ใบอื่นบน Avatar Zone ฝ่ายเรา 1 ใบกลับเข้าใต้ Deck : สอดแนม 5 ใบ อัญเชิญ Avatar {Symbol ปลา} 2 ใบจาก ที่สอดแนม ลง Avatar Zone ฝ่ายเรา นำการ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck",
    cost: 5,
    gem: 3,
    power: 4,
    symbol: Symbol.Fish,
    color: Color.Blue,
  },
  {
    name: "นีโม่ นรกสเลเยอร์",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-021",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar {symbol นรก} : ทำลาย Avatar ใบที่เป้าการโจมตี",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "แมว-น้ำมะลิ",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-022",
    rare: Rarity.R,
    mainEffect: "จุติ : สอดแนม 3 ใบ เลือก การ์ด Avatar \"หมา\" หรือ \"แมว\" ที่เป็น Symbol สัตว์ 1 ใบ จากที่ สอดแนม และนำขึ้นมือ ถ้าการ์ดที่เลือกคือ หมานมเย็น อัญเชิญ จุติ ลงบน Avatar Zone ฝ่ายเราแทนการนำขึ้นมือ จากนั้นนำการ์ดที่เหลือกลับ Deck แล้วสับ",
    cost: 2,
    gem: 1,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Blue,
  },
  {
    name: "นักรบ ฮอล",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-023",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "เมื่อฝ่ายตรงข้ามประกาศโจมตี : สามารถแสดงการ์ดใบนี้จากบนมือและอัญเชิญ Avatar ใบนี้โดยการจ่าย Cost \nเมื่อ Avatar ใบนี้ถูกอัญเชิญในช่วง Battle Phase ด้วยความสามารถของการ์ดใบนี้ เปลี่ยนเป้าหมายการโจมตีมาที่ Avatar ใบนี้ \nคำสั่งเสีย : จั่วการ์ด 1 ใบ",
    cost: 3,
    gem: 0,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "มีมมิ ผู้ร่วงหล่น",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-024",
    rare: Rarity.R,
    mainEffect: "จุติ : ถ้า Avatar Zone ฝ่ายเรา มี แดรกคูลา นำ Land Magic ปราสาทแดรก 1 ใบ จาก Deck เรา ขึ้นมือ จากนั้น สับ Deck",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Ghost,
    color: Color.Purple,
    gemColor: "ม่วง",
  },
  {
    name: "เฟรย่า แม่ทุกสถาบันแอสการ์ด",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-025",
    rare: Rarity.SR,
    mainEffect:
      "พอดี (จะได้รับความสามารถดังต่อไปนี้เมื่อ Avatar ใบนี้ถูกอัญเชิญมาด้วยการทิ้ง Gem พอดีกับ Cost เท่านั้น)\n   จุติ : นำ Avatar {Symbol เทพ} สีม่วง 3 ใบ จากในนรกเรากลับเข้า Deck เราแล้วสับ จากนั้น จั่วการ์ด 1 ใบ",
    cost: 4,
    gem: 3,
    power: 3,
    symbol: Symbol.God,
    color: Color.Purple,
    gemColor: "ม่วง",
  },
  {
    name: "เฮล่า เทพแอสการ์ดแห่งความตาย",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-026",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "ถ้าการ์ดใบนี้ถูกนำขึ้นมือหรือถูก ธรณีสูบ ด้วยการ์ด Avatar {symbol เทพ} สีม่วง และบน Land Magic Zone มี แอสการ์ดคือสถานที่ไม่ใช่ผู้คน และ ฝ่ายเราควบคุม Avatar {symbol เทพ} สีม่วง อยู่บน Avatar Zone จะสามารถ อัญเชิญ Avatar ใบนี้ออกมาได้ทันทีโดยไม่ต้องจ่าย Cost\nเทิร์นละครั้ง สั่งใช้ ธรณีสูบ ได้สูงสุด 5 ใบ : เลือก Avatar {symbol เทพ} สีม่วง 1 ใบ ใน Avatar Zone ฝ่ายเรา POWER เพิ่มขึ้นตามจำนวนการ์ดที่ ธรณีสูบ ด้วยความสามารถนี้ จนจบเทิร์น",
    cost: 5,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Purple,
    gemColor: "ม่วง",
  },
  {
    name: "บรุนฮิลด์  เทพธิดาแห่งวัลฮัลลา",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-027",
    rare: Rarity.R,
    mainEffect: "ถ้าการ์ดใบนี้ถูก ธรณีสูบ ด้วยการ์ด Avatar {symbol เทพ} สีม่วง หรือ Magic card : สามารถอัญเชิญการ์ดใบนี้จากนรกได้",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Purple,
    gemColor: "ม่วง",
  },
  {
    name: "Ecycle",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-028",
    rare: Rarity.R,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดจากบนมือ 1 ใบ : เลือกการ์ดในนรกเรา 1 ใบ นำกลับเข้าใต้ Deck จากนั้น จั่วการ์ด 1 ใบ",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: Symbol.Robot,
    color: Color.Purple,
  },
  {
    name: "จาบับวา",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-029",
    rare: Rarity.SR,
    mainEffect: "คำสั่งเสีย : สอดแนม 5 ใบ เลือก การ์ด Avatar {symbol คน} 1 ใบ จากที่ สอดแนม และนำขึ้นมือ จากนั้นนำการ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck",
    cost: 4,
    gem: 0,
    power: 4,
    symbol: Symbol.Foreigner,
    color: Color.Purple,
  },
  {
    name: "หมาชาไทย",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-030",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ นำ Avatar {symbol สัตว์} 1 ใบ ใน Avatar Zone ฝ่ายเรา ขึ้นมือ : Avatar ใบนี้ POWER +2",
    cost: 2,
    gem: 3,
    power: 0,
    symbol: Symbol.Animal,
    color: Color.Purple,
  },
  {
    name: "ทัตดนัยซัง โปรดิวเซอร์มือทอง",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-031",
    rare: Rarity.R,
    mainEffect:
      "โล่มนุษย์\nพอดี (จะได้รับความสามารถดังต่อไปนี้เมื่อ Avatar ใบนี้ถูกอัญเชิญมาด้วยการทิ้ง Gem พอดีกับ Cost เท่านั้น)\n  - จุติ : เลือก Avatar ของฝ่ายตรงข้าม 1 ใบ เปลี่ยน ชื่อ ของ Avatar ใบนั้นเป็น \"โอตะ\" และ นำมาสวมใส่ให้ Avatar \"ไอดอล\" บน Avatar Zone ของเรา และถ้าบน Avatar Zone ฝ่ายเรา มี มยุราซัง ไอดอลยุค 80 สามารถนำ Avatar \" ไอดอล \" 1 ใบจากใน Deck เรา ขึ้นมือ จากนั้นสับ Deck",
    cost: 6,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Purple,
    ex: "Only #1",
  },
  {
    name: "เจ๊หมวย เจ้าของร้านหม่าล่า",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-032",
    rare: Rarity.C,
    mainEffect:
      "อัตโนมัติ เมื่อ Avatar ใบนี้ ประกาศโจมตี : POWER +3 \nอัตโนมัติ เมื่อ Avatar ใบนี้ ถูกเล็งเป็นเป้าหมายโจมตี : POWER -3",
    cost: 1,
    gem: 1,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Purple,
  },
  {
    name: "ลุงไนท์ ราชาวานร",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-033",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ : สอดแนม 5 ใบ อัญเชิญ Avatar \"วานร\" Cost ไม่เกิน 4  1 ใบ จากที่สอดแนมลง Avatar Zone ฝ่ายเรา นำการ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck \nสั่งใช้ เมื่อ Avatar ใบนี้อยู่ในนรกและเราควบคุม Avatar \"วานร\" 3 ใบ ใน Avatar Zone : ทิ้งการ์ดจากมือ 1 ใบ : อัญเชิญ Avatar ใบนี้จากนรกลง Avatar Zone ฝ่ายเรา",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: Symbol.Animal,
    color: Color.Green,
    ex: "โดนใจ",
  },
  {
    name: "วานรช่องแชท",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-034",
    rare: Rarity.R,
    mainEffect: "ต่อเนื่อง ตราบเท่าที่อยู่บน Avatar Zone  POWER +1 ให้ Avatar \"วานร\" ใบอื่นบน Avatar Zone ฝ่ายเรา",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Green,
    ex: "โดนใจ",
  },
  {
    name: "คุณเชิดชัย Super Air",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-035",
    rare: Rarity.R,
    mainEffect: "จุติ : สอดแนม 5 ใบ เลือกการ์ด เครื่องบิน Super Air หรือ รหัสดำ จากที่ สอดแนม 1 ใบ และ/หรือ เลือกการ์ด Avatar \"Super Air\" ที่เป็น Symbol คน จากที่สอดแนม 1 ใบ นำขึ้นมือ จากนั้นนำการ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck",
    cost: 2,
    gem: 1,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "กระเป๋าเครื่องบิน Super Air",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-036",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ : นำ Magic Card \"ตั๋วยืน\" 1 ใบ จากใน Deck เรา ขึ้นมือ จากนั้นสับ Deck",
    cost: 1,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Green,
    gemColor: "เขียว",
  },
  {
    name: "หมาเครื่องบิน Super Air",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-037",
    rare: Rarity.C,
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ควบคุม เครื่องบิน Super Air บน Avatar Zone Avatar ใบนี้ได้รับความสามารถ \"เตะไข่",
    cost: 2,
    gem: 0,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Green,
  },
  {
    name: "ผู้โดยสาร Super Air",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-038",
    rare: Rarity.C,
    mainEffect:
      "สั่งใช้ เมื่อ เครื่องบิน Super Air จะถูกทำลายจากการต่อสู้และความสามารถของการ์ด สามารถทำลายการ์ดใบนี้ที่อยู่บนสนามแทนได้\n ต่อเนื่อง ตราบเท่าที่ เครื่องบิน Super Air อยู่บน Avatar Zone ฝ่ายเรา Avatar ใบนี้จะไม่สามารถถูก เลือกเป็นเป้าหมายการโจมตีได้",
    cost: 0,
    gem: 2,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Green,
    gemColor: "เขียว",
  },
  {
    name: "กุมภกรรณ ทดน้ำ",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-039",
    rare: Rarity.SR,
    mainEffect: "ต่อเนื่อง ตราบเท่าที่อยู่บน Avatar Zone Avatar ฝ่ายตรงข้าม ทุกใบ POWER -1",
    cost: 6,
    gem: 2,
    power: 3,
    symbol: Symbol.Giant,
    color: Color.Green,
    gemColor: "เขียว",
  },
  {
    name: "วานรแบงค์",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-040",
    rare: Rarity.R,
    mainEffect: "ลูกฮึด (เมื่อ Avatar ใบนี้ ต่อสู้กับ Avatar ที่มี POWER เท่ากัน และ ไม่มี ลูกฮึด Avatar ใบนี้จะเป็นฝ่ายชนะ)",
    cost: 2,
    gem: 1,
    power: 3,
    symbol: Symbol.Animal,
    color: Color.Green,
  },
  {
    name: "จ่ายุทธ Tank Ranger",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-041",
    rare: Rarity.C,
    mainEffect:
      "จุติ ถ้ามี Avatar \"รถถัง\" บนสนามฝ่ายเรา : ทำลาย Avatar {symbol ต่างชาติ} 1 ใบ\nเทิร์นละครั้ง สั่งใช้ : นำ Avatar ใบนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา \nเมื่อ Avatar \"รถถัง\" ที่สวมใส่ การ์ดใบนี้ ต่อสู้กับ Avatar {symbol ต่างชาติ} : นำ Avatar ที่ต่อสู้กับรถถังที่สวมใส่การ์ดนี้เข้าใต้ Deck",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "วีรชนชีวภาพ",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-042",
    rare: Rarity.C,
    mainEffect:
      "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost เพื่ออัญเชิญ Avatar สีเขียว : \nAvatar ที่ถูกอัญเชิญจะไม่รับผลจากความสามารถ Magic Card ของฝ่ายตรงข้าม จนจบเทิร์นต่อไปของฝ่ายตรงข้าม",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Green,
    gemColor: "เขียว",
  },
  {
    name: "มยุราซัง  ไอดอลยุค 80",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-043",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : นำ Avatar \"โอตะ\" 1 ใบจากนรกเรามาสวมใส่ให้ Avatar \"ไอดอล\" ใบอื่น 1 ใบบน Avatar Zone ฝ่ายเรา\nถ้าบน Avatar Zon e ฝ่ายเรามี ทัตดนัยซัง โปรดิวเซอร์มือทอง สามารถเลือก Avatar \"โอตะ\" จากใน Deck ฝ่ายเราแทนได้ ถ้าเลือกจาก Deck ให้สับ Deck",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "อาจารย์หลี ปรมาจารย์มวยจีน",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-044",
    rare: Rarity.R,
    mainEffect:
      "อัตโนมัติ เมื่อ Avatar ใบนี้ โจมตี POWER +1 จนจบเทิร์น\nเทิร์นละครั้ง สั่งใช้ เมื่อ Avatar ฝ่ายตรงข้ามประกาศโจมตี : สามารถย้ายเป้าหมายการโจมตีมาที่การ์ดใบนี้ได้",
    cost: 3,
    gem: 0,
    power: 3,
    symbol: Symbol.Foreigner,
    color: Color.Green,
  },
  {
    name: "นินจาไร้นาม",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-045",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 2,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "ง่อวซอรัส",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-046",
    rare: Rarity.C,
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 5,
    symbol: Symbol.Lizard,
    color: Color.Blue,
  },
  {
    name: "แมลงปอปีกเหล็ก",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-047",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 0,
    power: 4,
    symbol: Symbol.Insect,
    color: Color.Purple,
  },
  {
    name: "รถถัง A003",
    type: CardType.Avatar,
    soi: 2,
    print: "BT05-048",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: Symbol.Robot,
    color: Color.Green,
  },
  {
    name: "รับซื้อของโจร",
    type: CardType.Magic,
    soi: 1,
    print: "BT05-049",
    rare: Rarity.C,
    mainEffect: "สุ่มหยิบการ์ด 1 ใบ จากมือฝ่ายตรงข้าม ขึ้นมือเรา การ์ดใบนั้น สามารถใช้ได้แค่เป็น Cost เพื่อการอัญเชิญ Avatar เท่านั้นเมื่อจบเทิร์นถ้าการ์ดใบนั้นยังอยู่บนมือเรา คืนการ์ดใบนั้นให้ฝ่ายตรงข้าม",
    subtype: MagicSubtype.Normal,
    cost: 0,
    symbol: Symbol.Mage,
  },
  {
    name: "พูดไทยได้ 5 คำ",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-050",
    rare: Rarity.R,
    mainEffect: "สอดแนม 5 ใบ เลือกการ์ด Avatar {symbol ต่างชาติ} 1 ใบ จากที่ สอดแนม และนำขึ้นมือ ถ้าการ์ดใบนั้นมี Cost 2 หรือต่ำกว่า สามารถอัญเชิญลง Avatar Zone ฝ่ายเราแทนได้ นำการ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Foreigner,
  },
  {
    name: "ง่วงมากก็ไปนอน !!!",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-051",
    rare: Rarity.C,
    mainEffect: "เลือก Avatar ที่อยู่ในสภาพ นอน 1 ใบ นำกลับเข้า Deck จากนั้นสับ Deck เจ้าของ Avatar ที่ถูกนำกลับเข้า Deck จั่วการ์ด 1 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "Jump Scare",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-052",
    rare: Rarity.C,
    mainEffect: "ทิ้งการ์ดจากมือ 1 ใบ : ฝ่ายตรงข้าม สุ่มเลือกการ์ด จาก Deck เรา 1 ใบ ถ้าการ์ดใบนั้น เป็น Avatar ที่มี Cost 5 หรือต่ำกว่า อัญเชิญ Avatar ใบนั้น ลงบน  Avatar Zone ฝ่ายเรา ถ้าไม่ใช่ Avatar นำการ์ดใบนั้นลงนรก จากนั้น สับ Deck",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "บ่อนแตก",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-053",
    rare: Rarity.C,
    mainEffect: "สามารถใช้การ์ดนี้ได้เมื่อฝ่ายตรงข้ามควบคุม Avatar ในสนาม ตั้งแต่ 5 ใบ ขึ้นไป : ทำลาย Avatar ทุกใบบนสนามฝ่ายตรงข้าม",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "เครื่องบิน Super Air",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-054",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "สามารถใช้การ์ดนี้ได้ถ้าในเทิร์นนี้เรายังไม่ได้อัญเชิญ Avatar หรือ อัญเชิญแค่ Avatar \"Super Air\" เท่านั้น : อัญเชิญการ์ดใบนี้เข้าสู่ Avatar Zone ฝ่ายเราโดยจะเปลี่ยนการ์ดใบนี้เป็น Avatar {Symbol หุ่นยนต์} Cost 5 GEM 0 POWER 5 หลังจากใช้การ์ดใบนี้ จนกว่าจะจบเทิร์นนี้เราจะไม่สามารถอัญเชิญ Avatar ได้ ยกเว้น Avatar \"Super Air",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Robot,
  },
  {
    name: "ตั๋วยืน",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-055",
    rare: Rarity.C,
    mainEffect: "ถ้าบน Avatar Zone ฝ่ายเรามี เครื่องบิน Super Air ทิ้งการ์ดบนมือ 1 ใบ : อัญเชิญ \"ผู้โดยสาร Super Air\" จากใน Deck สูงสุด 2 ใบ จากนั้นสับ Deck",
    subtype: MagicSubtype.Normal,
    cost: 3,
    symbol: Symbol.Mage,
  },
  {
    name: "พลังแห่งการตีพ่อตีแม่",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-056",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "เลือกปฏิบัติ :\n1) เลือก Avatar {Symbol เปรต} 1 ใบบน Avatar Zone ฝ่ายเรา นำ Modification Magic \"\"ตีพ่อ\"\" และ \"\"ตีแม่\"\" จากใน Deck มาสวมใส่ ให้ Avatar {Symbol เปรต} ใบที่เลือก\n2) นำ Avatar {Symbol เปรต} 1 ใบ จากใน Deck เรา ขึ้นมือจากนั้นสับ Deck\nถ้าเราอยู่ในสถานะ สาหัส สามารถ ทำความสามารถ 1) และ 2)",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Pret,
  },
  {
    name: "พระคุ้มครอง",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-057",
    rare: Rarity.C,
    mainEffect: "สามารถใช้การ์ดนี้ได้ในช่วง เริ่มต้น Battle Phase ของฝ่ายตรงข้ามเท่านั้น  ส่ง Avatar บน Avatar Zone ฝ่ายเรา 1 ใบ ลงนรก : Avatar ทุกใบ บน Avatar Zone ฝ่ายเรา จะไม่ถูกทำลายจากการต่อสู้ในเทิร์นนี้",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "อย่าให้มีครั้งที่ 2",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-058",
    rare: Rarity.R,
    mainEffect:
      "เมื่อฝ่ายตรงข้ามใช้ {react} : ยกเลิกผลของการ์ดใบนั้น \nการ์ดใบนี้สามารถใช้ได้แม้ว่าในเทิร์นนี้เราใช้ การ์ด {react} ไปแล้ว#สามารถใช้การ์ด อย่าให้มีครั้งที่ 2 ได้ 1 ใบ ต่อเทิร์น เท่านั้น",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "รหัสดำ",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-059",
    rare: Rarity.R,
    mainEffect: "ส่งการ์ด คุณเชิดชัย Super Air , เครื่องบิน Super Air และ Avatar \"Super Air\" 2 ใบ จาก Avatar Zone ฝ่ายเรา โดยที่ Avatar ทั้ง 4 ใบ จะต้องชื่อไม่ซ้ำกัน ลงนรก : หงาย LIFE Card ฝ่ายตรงข้าม 3 ใบ แต่ถ้าฝ่ายตรงข้ามมี LIFE Card ที่คว่ำอยู่ 2 ใบ หรือต่ำกว่า ขณะใช้การ์ดใบนี้ จะถือว่าเราชนะเกมทันที",
    subtype: MagicSubtype.React,
    cost: 4,
    symbol: Symbol.Robot,
    ex: "Only #1",
  },
  {
    name: "เหน็บกินมือ",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-060",
    rare: Rarity.C,
    mainEffect: "เมื่อฝ่ายตรงข้ามจะนำการ์ดจาก Deck ขึ้นมือ ด้วยความสามารถของ Avatar หรือ Magic : ยกเลิกผลความสามารถนั้น",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "แผนการ : เพดานถล่ม",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-061",
    rare: Rarity.R,
    mainEffect: "เมื่อ Avatar เปลี่ยนสภาพเป็นสภาพนอน และ ใน Avatar Zone ของฝ่ายตรงข้าม มี Avatar ที่อยู่ใน สภาพนอน 2 ใบ ขึ้นไป : ทำลาย Avatar 1 ใบ ที่อยู่ในสภาพนอน",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ฮึบบบบบบบบบบบบ",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-062",
    rare: Rarity.C,
    mainEffect: "Avatar 1 ใบ ได้รับ ลูกฮึด (เมื่อ Avatar ใบนี้ ต่อสู้กับ Avatar ที่มี POWER เท่ากัน และ ไม่มี ลูกฮึด Avatar ใบนี้จะเป็นฝ่ายชนะ) จนจบเทิร์น",
    subtype: MagicSubtype.React,
    cost: 3,
    symbol: Symbol.Mage,
  },
  {
    name: "อาวุธหุ่นนักรบผู้กล้า \"GHD โคลค\"",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-063",
    rare: Rarity.C,
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar {symbol หุ่นยนต์} เท่านั้น\nAvatar ที่สวมใส่การ์ดใบนี้ จะไม่ถูกเปลี่ยน Symbol",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Robot,
  },
  {
    name: "ดาบศักดิ์สิทธิ์ อาลอนไดร์ท",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-064",
    rare: Rarity.C,
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar \"\"อัศวินโต๊ะกลม\"\" เท่านั้น \nAvatar ที่สวมใส่การ์ดใบนี้ POWER +1 เมื่อ Avatar ที่สวมใส่การ์ดใบนี้โจมตี ฝ่ายตรงข้ามจะไม่สามารถสั่งใช้ โล่มนุษย์ ได้\nถ้าในเทิร์นนี้ ยังไม่ได้ใช้ Modification Magic สามารถ ธรณีสูบ 1 ใบ และนำการ์ดใบนี้ที่อยู่ในนรก ไปสวมใส่ให้ \"\"อัศวินโต๊ะกลม\"\" ใน Avatar Zone ฝ่ายเรา และนับว่าเป็นการใช้ Modification Magic",
    subtype: MagicSubtype.Modification,
    cost: 3,
    symbol: Symbol.Mage,
  },
  {
    name: "กระบองแสง คทาวุธ",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-065",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "เมื่อ Avatar ที่สวมใส่การ์ดใบนี้โจมตี อีกฝ่ายจะไม่สามารถใช้งาน React Magic จนจบการต่อสู้นั้น\nเมื่อ Avatar ที่สวมใส่การ์ดใบนี้ โจมตีและทำลาย Avatar ฝ่ายตรงข้ามสำเร็จจากการต่อสู้ : ถ้า Avatar Zone ของอีกฝ่ายมี Avatar อยู่ เปลี่ยนสภาพ Avatar ที่สวมใส่การ์ดใบนี้อยู่เป็นสภาพตื่น",
    subtype: MagicSubtype.Modification,
    cost: 0,
    symbol: Symbol.Giant,
    ex: "Only #1",
  },
  {
    name: "มนุษย์ดัดแปลง",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-066",
    rare: Rarity.R,
    mainEffect:
      "เลือก Avatar 1 ใบ ในนรกเรา ที่ Cost ไม่เกิน 3 จากนั้น ทิ้งการ์ดบนมือ 1 ใบ : อัญเชิญ Avatar ที่เลือกลง Avatar Zone ฝ่ายเรา จากนั้นนำการ์ดใบนี้ไปสวมใส่ Avatar ใบนั้น\nAvatar ที่สวมใส่การ์ดใบนี้ จะถูกเปลี่ยน Symbol เป็นเครื่องจักร\nถ้าการ์ดใบนี้ถูกนำออกจากสนาม ส่ง Avatar ที่สวมใส่การ์ดใบนี้ลงนรก",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Robot,
  },
  {
    name: "Hot Zone",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-067",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เทิร์นละครั้ง สั่งใช้ : สามารถนำ Avatar \"Tank Ranger\" ที่เป็น Symbol คน บนมือเรา 1 ใบ ไปสวมใส่ให้ Avatar \"รถถัง\" บน Avatar Zone ฝ่ายเรา",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Soldier,
  },
  {
    name: "ทรายดูด",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-068",
    rare: Rarity.C,
    mainEffect: "Avatar ที่ POWER เท่ากับ 0 จะถูกทำลาย",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "กรุงลงกา",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-069",
    rare: Rarity.SR,
    mainEffect: "เมื่อจะทำการอัญเชิญ Avatar {Symbol ยักษ์} จากมือ สามารถใช้ POWER ของ Avatar {Symbol ยักษ์} บนมือ แทนค่า GEM ได้ โดยที่ 1 POWER  จะมีค่าเท่ากับ 1 GEM",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Giant,
  },
  {
    name: "ฐานหุ่นนักรบผู้กล้า ซีทันยาน",
    type: CardType.Magic,
    soi: 2,
    print: "BT05-070",
    rare: Rarity.R,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ถ้าในเทิร์นนี้ยังไม่ได้ใช้ Modification Magic : ในเทิร์นนี้สามารถใช้ Modification Magic \"อาวุธหุ่นนักรบผู้กล้า\" ได้ 2 ใบ และจะไม่สามารถใช้ Modification Magic ที่ไม่ใช่ \"อาวุธหุ่นนักรบผู้กล้า\" ได้",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Robot,
  },
  {
    name: "ไม่นะ อู๊ด !",
    type: CardType.Life,
    soi: 2,
    print: "BT05-071",
    rare: Rarity.C,
    mainEffect: "ใน Main Phase ถัดไป นำ Normal Magic 1 ใบ จาก นรกฝ่ายเราขึ้นมือ",
    favorText: "อู๊ดประธานแห่งชมรมผู้รู้ความจริง จริงๆแล้วพวกเขาก็แค่คนไร้บ้านที่ประทังชีวิตด้วยการขายตรงและกินหมา... โอเคกุจำได้ละ มันเลว เอาใหม่... \nแต้งกิ้ว คุณเพิ่งฆ่าไอ้แดกหมาที่ชั่วร้าย และต่อไปนี้ฉายาคุณคือ \"แดกหมาslayer",
  },
  {
    name: "ไม่นะ ไมเกรน !",
    type: CardType.Life,
    soi: 2,
    print: "BT05-072",
    rare: Rarity.C,
    mainEffect: "ในช่วงเริ่มต้น Battle Phase ถัดไป Avatar ทุกใบ บน Avatar Zone ฝ่ายเรา POWER+1",
    favorText: "แม่งเอ๊ยเหลือแต่นอต ลูกคนโปรดโดมตายอนาถชิบเป๋ง อันนี้กุด่าทีม 2D ละ ทำไมมึงใจร้ายกับไมเกรนจังวะ คนเล่นคุณก็เคยเห็นใช่ปะ\nการ์ดไมเกรน ? มันโคตรเท่เลยหุ่นเหล็กแสนสง่า ไม่มีละ เหลือแต่นอต โอ้โน",
  },
  {
    name: "ไม่นะ มีมมิจัง !",
    type: CardType.Life,
    soi: 2,
    print: "BT05-073",
    rare: Rarity.C,
    mainEffect: "ใน Main Phase ถัดไป สอดแนม 5 ใบ นำ Avatar 1 ใบ จากที่สอดแนม ขึ้นมือ นำการ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck",
    favorText: "มีมมิจังไอดอลผู้ส่งความสุขให้แก่แฟนๆทั่วประเทศ แต่กลับไม่เคยมีเวลาให้ตัวเธอเอง หรือผัวของเธอ และตอนนี้เธอตายแล้ว\nเพราะฉะนั้น...ไปตามไอ้นัทมาที",
  },
  {
    name: "เฮ้ย รัททาทุย ตาย !",
    type: CardType.Life,
    soi: 2,
    print: "BT05-074",
    rare: Rarity.C,
    mainEffect: "ใน Main Phase ถัดไป สามารถ อัญเชิญ Avatar ที่ Cost 4 หรือต่ำกว่า 1 ใบ จากมือลงบน Avatar Zone ฝ่ายเรา",
    favorText: "รัททาทุยแพร่พันธุ์อย่างรวดเร็วเมื่อพ่อพันธุ์ได้ make love กับราชินี กลายเป็นสัตว์ที่อันตรายที่สุดในโลก \nเอาจริงกุลืมไปละว่ามันเคยเป็นแค่หนูแฮมสเตอร์ ตอนนี้มันกลายเป็นไรก็ไม่รู้ เอาเป็นว่าโชคดีที่มันตาย",
  },
  {
    name: "ไม่นะ โดม !",
    type: CardType.Life,
    soi: 2,
    print: "BT05-075",
    rare: Rarity.C,
    mainEffect: "ใน Main Phase ถัดไป นำ Avatar 1 ใบจาก นรกฝ่ายเรา ที่มี GEM 3 หรือมากกว่า ขึ้นมือ",
    favorText: "โดมคือเสาหลักแห่งการ์ดตลิ่งชัน โดมต้องเจออุปสรรคและแรงกดดันมาตลอดแต่เขาก็ไม่เคยยอมแพ้ \nการ์ดตลิ่งชันมาถึงจุดนี้ได้ก็เพราะโดมและทีมงานทุกคน และถึงแม่หลายๆครั้งจะเกิดเรื่องพลาดทำให้คนโมโห\nผมก็อยากให้ทุกคนรู้ว่า...ไอ้โดมมันทำ ด่ามันซะ",
  }
]);
