import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_CC01: Card[] = createCards([
  {
    name: "พระอิศวร เทพผู้ทำลาย",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-001",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ : ทำลาย การ์ด บนสนาม 1 ใบ\nเทิร์นละครั้ง สั่งใช้ : สามารถทำลาย การ์ด บนสนาม 1 ใบ",
    cost: 8,
    gem: 1,
    gemColor: Color.Red,
    power: 7,
    symbol: Symbol.God,
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "พระนารายณ์ เทพผู้พิทักษ์",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-002",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "โล่มนุษย์ เตะไข่\nอัตโนมัติ เมื่อ Avatar ใบนี้จะถูกทำลายสามารถปรับ POWER ตั้งต้นของ Avatar ใบนี้ลดลงครึ่งหนึ่งแทนการถูกทำลาย ความสามารถนี้ ใช้ได้เพียง 1 ครั้งต่อการอัญเชิญ",
    cost: 8,
    gem: 1,
    gemColor: Color.Red,
    power: 8,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "พระพรหม เทพผู้สร้าง",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-003",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ ถ้าใน นรก ฝ่ายเรา มี Avatar ชื่อไม่ซ้ำกัน 5 ใบ ขึ้นไป สอดแนม 7 ใบ : นำ Avatar ที่มีชื่อไม่ซ้ำกัน จากในนั้น และใน Avatar Zone ฝ่ายเรา\nกี่ใบก็ได้ลง Avatar Zone ฝ่ายเรา  นำที่เหลือกลับเข้า Deck แล้วสับ ความสามารถนี้ไม่สามารถถูกยกเลิกได้",
    cost: 8,
    gem: 2,
    gemColor: Color.Red,
    power: 6,
    symbol: "เทพ",
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "พระอินทร์ เทพขยัน",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-004",
    rare: Rarity.SR,
    mainEffect: "จุติ : สอดแนม 3 ใบ เลือก การ์ด Symbol เทพ 1 ใบ จากที่สอดแนม และนำขึ้นมือ การ์ดที่เหลือนำไปไว้ใต้ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "ปื๊ดเปรตกังฟู",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-005",
    rare: Rarity.SR,
    mainEffect:
      "ต่อเนื่อง POWER ของการ์ดใบนี้จะเพิ่มขึ้นเท่ากับจำนวน Life Card ฝ่ายเรา ที่คว่ำอยู่ ใบละ 1\nเมื่อ Avatar ใบนี้ออกจากสนาม : หงาย Life Card ใบบนสุดของฝ่ายเรา 1 ใบ",
    cost: 5,
    gem: 2,
    power: 3,
    symbol: Symbol.Pret,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "ไตรตัน เจ้าสมุทร",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-006",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ : อัญเชิญ Avatar {symbol ปลา} กี่ใบก็ได้ที่ Cost รวมกันไม่เกิน 7 จาก นรกฝ่ายเรา ลงบน Avatar Zone ฝ่ายเรา\nต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้อยู่บน Avatar Zone Avatar {symbol ปลา} ใน Avatar Zone ฝ่ายเรา ทุกใบ POWER +1 และได้รับ สามัคคี",
    cost: 6,
    gem: 2,
    power: 6,
    symbol: Symbol.God,
    color: Color.Blue,
    ex: "Only #1",
    gemColor: "ฟ้า",
  },
  {
    name: "วีรบุรุษสุดซอย",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-007",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ : นำ Avatar \"กุ่ย\" , \"ฮอล\" และ \"นาย\" จากในนรกอย่างละ 1 ใบ มาสวมใส่ให้ Avatar ใบนี้ \nหลังจบการต่อสู้ที่ Avatar ใบนี้สั่งโจมตี นำ Avatar ใบนี้ ที่มี \"กุ่ย\" , \"ฮอล\" และ \"นาย\" สวมใส่อยู่ ส่งลงนรก : \nอัญเชิญ จุติ วีรบุรุษปากซอย จากบนมือ หรือ Deck 1 ใบ ลง Avatar Zone ฝ่ายเรา หากอัญเชิญจาก Deck ให้สับ Deck",
    cost: 6,
    gem: 3,
    power: 5,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "คนอีสาน ยุคครีเตเชียส",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-008",
    rare: Rarity.SR,
    mainEffect: "จุติ : นำการ์ด \"แมลงปอทอด\" 1 ใบ จากใน Deck เราขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ชู้รักรัททาทุย",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-009",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "ถ้าในเกมนี้ เราได้อัญเชิญ Avatar ชื่อ \"รัททาทุย นางพญา\" ไปแล้ว Avatar ใบนี้ จะนับเป็นชื่อ \"รัททาทุย นางพญา\" เมื่ออยู่บน Avatar Zone",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "ลุงบุญโชค",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-010",
    rare: Rarity.SR,
    mainEffect: "จุติ : นำ Magic \"สมชายห้องเช่า\"  1 ใบ จากใน Deck  ฝ่ายเราขึ้นมือจากนั้นสับ Deck",
    cost: 2,
    gem: 3,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "พญายม With The Shotgun",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-011",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "ในช่วงขั้นตอนจัด Deck ถ้าใส่การ์ดใบนี้ใน Deck จะต้องใส่ {only} สุวาน ใน Deck อีก 1 ใบ\nเมื่อ Avatar ใบนี้อยู่บน Avatar Zone Avatar {symbol นรก} ทุกใบ ใน นรกฝ่ายเราได้รับชื่อ \"นายนิรยบาล\"\nเทิร์นละครั้ง สั่งใช้ : สามารถอัญเชิญ Avatar \"นายนิรบาล\" ในนรกฝ่ายเรา 1 ใบ ลง Avatar Zone ฝ่ายเรา\n#ในช่วงขั้นตอนจัด Deck ถ้าใส่การ์ดใบนี้ใน Deck จะต้องใส่ {only} สุวาน ใน Deck อีก 1 ใบ",
    cost: 7,
    gem: 3,
    gemColor: Color.Purple,
    power: 6,
    symbol: Symbol.Hell,
    color: Color.Purple,
    ex: "Only #1",
  },
  {
    name: "เฟรนชี่",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-012",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "คำสั่งเสีย : จั่วการ์ด 2 ใบ จาก Deck ฝ่ายเรา จากนั้น นำการ์ด 1 ใบในมือเรา วางไว้ล่างสุดของ Deck ฝ่ายเรา",
    cost: 2,
    gem: 1,
    power: 1,
    symbol: Symbol.Fish,
    color: Color.Purple,
  },
  {
    name: "เจนนี่",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-013",
    rare: Rarity.SR,
    mainEffect:
      "ต่อเนื่อง การ์ดใบนี้โจมตีไม่ได้ \nในทุก End Phase ของทั้ง 2 ฝ่าย : ทอยลูกเต๋า 1 ครั้ง ถ้าออก 4 ทำลาย Avatar ใบนี้ และ หงาย Life Card ใบบนสุดของผู้ควบคุมปัจจุบันของการ์ดใบนี้ 1 ใบ หากออกเลขอื่น เปลี่ยนการควบคุม Avatar ใบนี้ไปให้อีกฝ่าย",
    cost: 2,
    gem: 0,
    power: 3,
    symbol: Symbol.Robot,
    color: Color.Purple,
  },
  {
    name: "วูตาตู",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-014",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : สามารถนำ Avatar ใบนี้ที่อยู่ใน Avatar Zone ไปสวมใส่ให้ Avatar 1 ใบ บนสนามฝ่ายเรา \nAvatar ใบที่สวมใส่การ์ดใบนี้ จะถูกเปลี่ยน Symbol เป็น {Symbol ผี} POWER ของ Avatar ที่สวมใส่ POWER + 3 \nเมื่อ Avatar ที่สวมใส่ถูกทำลาย นำการ์ดใบนี้ไปสวมใส่ให้ Avatar ใบอื่นของฝ่ายเราแทน",
    cost: 5,
    gem: 0,
    power: 3,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "HR ผู้รู้ความจริง",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-015",
    rare: Rarity.SR,
    mainEffect: "จุติ : สอดแนม 2 ใบ นำการ์ด 1 ใบจากที่สอดแนมขึ้นมือ และ นำการ์ดที่เหลือไปไว้บนสุด หรือ ล่างสุดของ Deck ฝ่ายเรา",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Purple,
    gemColor: "ม่วง",
  },
  {
    name: "แมวนิค",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-016",
    rare: Rarity.SR,
    mainEffect:
      "เทิร์นละครั้ง อัตโนมัติ เมื่อมีการ อัญเชิญ Avatar : Avatar ใบนี้จะถูกเปลี่ยนการควบคุมไปยัง Avatar Zone ของฝ่ายตรงข้าม\nต่อเนื่อง ผู้ที่ควบคุม Avatar ใบนี้ จะไม่สามารถ นำการ์ดขึ้นมือจาก Deck ด้วยความสามารถของ Avatar และ Magic",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Purple,
  },
  {
    name: "ยักษ์หินแผ่นดินใหญ่",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-017",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "โล่มนุษย์ \nอัตโนมัติ สั่งใช้ เมื่อ Avatar {Symbol ยักษ์} บน Avatar Zone ฝ่ายเราตกเป็นเป้าหมายของ Magic Card \nสามารถเปลี่ยนสภาพ Avatar ใบนี้เป็น สภาพนอน : เปลี่ยนเป้าหมายของผล Magic Card ใบนั้นมาที่ Avatar ใบนี้แทน",
    cost: 3,
    gem: 0,
    power: 3,
    symbol: Symbol.Giant,
    color: Color.Green,
  },
  {
    name: "เสามงคล ทรงจีน",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-018",
    rare: Rarity.UR,
    mainEffect:
      "ต่อเนื่อง การ์ดใบนี้โจมตีไม่ได้\nจุติ : อัญเชิญ \"ผู้เจริญ\" 1 ใบ จากใน Deck ฝ่ายเรา เมื่อจบเทิร์นนำ Avatar ที่อัญเชิญจากความสามารถของการ์ดใบนี้กลับขึ้นมือ",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: Symbol.Tree,
    color: Color.Green,
  },
  {
    name: "หมวดเงียบ ทหารรับจ้าง",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-019",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ สามารถเลือก Avatar บน Avatar Zone ของฝ่ายตรงข้าม 1 ใบ : \nถ้า Avatar ที่เลือก อยู่ในสภาพตื่น ให้เปลี่ยนสภาพ Avatar ใบนั้นเป็นสภาพนอน Avatar ที่เลือกจะไม่สามารถเปลี่ยนเป็นสภาพตื่น ได้จนกว่า Avatar ใบนี้จะออกจาก Avatar Zone",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Green,
    gemColor: "เขียว",
  },
  {
    name: "ผู้กองอึ่งอ่าง",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-020",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้อยู่บน Avatar Zone  Avatar ใบนี้จะนับเป็นทุก Symbol",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "อินทรีย์แมน",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-021",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ : นำ Modification Magic จากใน Deck ฝ่ายเรา 1 ใบมาสวมให้กับ Avatar ใบนี้หลังจากนั้นสับ Deck \nPOWER ของ Avatar ใบนี้จะเพิ่มตาม Modification Magic ทั้งหมดบนสนาม ใบละ 1",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "นนทก นิ้วเพชร",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-022",
    rare: Rarity.SR,
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar {symbol เทพ} : ทำลาย Avatar ใบที่เป้าการโจมตี",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Giant,
    color: Color.Red,
  },
  {
    name: "ตำรวจไซบอร์ค จ่าคอป",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-023",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง เมื่อ Avatar ใบนี้ประกาศโจมตี ทิ้งการ์ดบนมือ 1 ใบ : สอดแนม (แสดงการ์ดใบบนสุดของ Deck) 3 ใบ นำการ์ด Symbol เครื่องจักร 1 ใบ จากที่สอดแนม ขึ้นมือ การ์ดที่เหลือเรียงและนำไปไว้ใต้ Deck",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "รัททาทุย",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-024",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "สามัคคี (เปลี่ยนการ์ดนี้เป็นสภาพนอนและนำ POWER การ์ดนี้ไปเพิ่มให้กับ Avatar ที่สั่งโจมตี) \n#การ์ดใบนี้ สามารถใส่ใน Deck จำนวนได้มากสุด 50 ใบ",
    cost: 1,
    gem: 1,
    power: 1,
    symbol: Symbol.Rat,
    color: Color.Blue,
    customLimit: 50,
  },
  {
    name: "รัททาทุย พ่อพันธุ์",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-025",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : ถ้าบน Avatar Zone ฝ่ายเรามี \n\"รัททาทุย นางพญา\" สามารถอัญเชิญ Avatar ที่มีชื่อ \"รัททาทุย\" \nจากใน Deck เรา ลงบน Avatar Zone ฝ่ายเรากี่ใบก็ได้ โดย Cost รวมกันไม่เกิน 5 จากนั้นสับ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "แมลงปอเลื่อยยนต์",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-026",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) :  ทำลาย MAGIC บนสนาม 1ใบ",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "แมลงปอแจ็ค",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-027",
    rare: Rarity.SR,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : ทำลายการ์ด Land Magic 1 ใบบน Land Magic Zone หลังจากนั้นนำ Land Magic 1 ใบจาก Deck เรามาเล่นบน Land Magic Zone หลังจากนั้นสับ Deck",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "นายนิรยบาล พ่อจีจ้า",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-028",
    rare: Rarity.SR,
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้เป็นเป้าหมายโจมตีหรือสั่งโจมตี : ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 2 ใบ POWER +1 จนจบเทิร์น",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "นายนิรยบาล แว่น",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-029",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "ถ้าการ์ดใบนี้ถูกส่งลงนรกด้วยผลของ ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) : สามารถอัญเชิญการ์ดใบนี้ลง Avatar Zone จากนรกได้\n#การ์ดใบนี้ไม่สามารถลงสนามจากบนมือได้",
    cost: 0,
    gem: 1,
    power: 4,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "แบงค์ ผู้รู้ความจริง",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-030",
    rare: Rarity.SR,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สอดแนม (แสดงการ์ดใบบนสุดของ Deck ) 3 ใบของเรา เรียงลำดับตามใจชอบ",
    cost: 2,
    gem: 1,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "เสามงคล",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-031",
    rare: Rarity.SR,
    mainEffect:
      "ต่อเนื่อง การ์ดใบนี้โจมตีไม่ได้ \nต่อเนื่อง ในช่วง Draw Phase หลังจากการจั่วการ์ดปกติใน Draw Phase : จั่วการ์ด 1 ใบ",
    cost: 5,
    gem: 2,
    power: 3,
    symbol: Symbol.Tree,
    color: Color.Green,
  },
  {
    name: "ซินแส",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-032",
    rare: Rarity.SR,
    mainEffect: "จุติ  (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : นำ Avatar \"เสามงคล\" 1 ใบ จาก Deck เรา ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 3,
    gem: 3,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "จ่ามะนาว Tank Ranger",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-033",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ (เมื่อ Avatar ตัวนี้ลงสนามแบบจ่ายCost) ถ้ามี Avatar \"รถถัง\" บนสนามฝ่ายเรา สุ่มคว่ำ LIFE Card ฝ่ายเรา 1 ใบ \nเทิร์นละครั้ง สั่งใช้ : นำ Avatar ใบนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา \nเมื่อAvatar \"รถถัง\"ที่สวมใส่การ์ดใบนี้จะถูกทำลาย : ทำลายการ์ดใบนี้แทน",
    cost: 3,
    gem: 3,
    gemColor: Color.Blue,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "จ่าแดงเดือด Tank Ranger",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-034",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : นำ Avatar ใบนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา\nAvatar รถถังที่สวมใบนี้ POWER +1 \nสั่งใช้ เมื่อ Avatar ที่สวมใส่การ์ดนี้ทำลาย Avatar อีกฝ่ายจากการต่อสู้สำเร็จ ทำลายการ์ดใบนี้ที่สวมใส่อยู่  : Avatar ที่เคยสวมใส่การ์ดใบนี้จะกลับมาในสภาพตื่น",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "เทวดาตัวเปิด",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-035",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ตึก",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-036",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "",
    cost: 6,
    gem: 4,
    power: 9,
    symbol: Symbol.Robot,
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "เด็กไม่ชอบแมลงสาบ",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-037",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ลูกค้าชาบู",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-038",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "",
    cost: 2,
    gem: 4,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "จอมมังการ์ด",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-039",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "",
    cost: 5,
    gem: 1,
    power: 6,
    symbol: Symbol.Animal,
    color: Color.Purple,
  },
  {
    name: "จอมเวทย์ดำ",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-040",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 3,
    gem: 1,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "ไอ้หนุ่มรด.",
    type: CardType.Avatar,
    soi: 1,
    print: "CC01-041",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "",
    cost: 1,
    gem: 3,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "พรของอิศวร",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-042",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "เลือกปฏิบัติ \n1) จั่วการ์ด ให้การ์ดบนมือมีครบ 5 ใบ \n2) ทำลาย Avatar อีกฝ่ายไม่เกิน 2 ตัว \n3) นำการ์ดประเภทใดก็ได้จากนรกฝ่ายเราขึ้นมือ 2 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.God,
    ex: "Only #1",
  },
  {
    name: "รู้สึกเหมือนโดนแย่งเมีย",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-043",
    rare: Rarity.SR,
    mainEffect: "นำ Avatar ทั้งหมดที่ถูกเปลี่ยนการควบคุมใน Avatar Zone กลับมาที่ Avatar Zone ของเจ้าของเดิม",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.God,
  },
  {
    name: "ซ่อมบำรุงประจำปี",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-044",
    rare: Rarity.SR,
    mainEffect:
      "เมื่อฝ่ายตรงข้ามควบคุม Avatar บน Avatar Zone และเราไม่มี Avatar ควบคุมอยู่ เลือก Avatar \"รถถัง\" และ \"Tank Ranger\" ที่มีค่า Cost เป็น 3 \nในนรกของเรา อย่างละ 1 ใบ : อัญเชิญ Avatar \"รถถัง\" ใบที่เลือก ลง Avatar Zone ฝ่ายเรา และนำ Avatar \"Tank Ranger\" ใบที่เลือกมาสวมใส่ ให้กับ Avatar \"รถถัง\" ที่ถูกอัญเชิญ มาด้วยความสามารถของการ์ดใบนี้",
    subtype: MagicSubtype.Normal,
    cost: 4,
    symbol: Symbol.Soldier,
  },
  {
    name: "กฎร้าน",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-045",
    rare: Rarity.SR,
    mainEffect:
      "เมื่อทั้ง 2 ฝ่าย ควบคุม Avatar บน Avatar Zone : \nแสดงการ์ดใบล่างสุดของ Deck แต่ละฝ่าย ให้นำ Cost ของ Avatar ที่แสดงมาเทียบกัน ถ้าไม่ใช่การ์ด Avatar จะถือว่าค่า Cost เป็น 0\nฝ่ายไหนที่มี Cost เยอะกว่า ได้สิทธิ์เลือกปฏิบัติ : \n1) ส่ง Avatar 1 ใบ บน Avatar Zone ฝ่ายตรงข้าม ลงนรก\n2) นำ Avatar 1 ใบ บนสนามกลับเข้า Deck เจ้าของ แล้วสับ \nหากเท่ากันจะไม่มีผลใดเกิดขึ้น",
    subtype: MagicSubtype.React,
    cost: 2,
    symbol: Symbol.Mage,
    customLimit: 2,
  },
  {
    name: "ขอให้ทั้งตัวมีแต่---",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-046",
    rare: Rarity.UR,
    mainEffect: "เลือก Avatar ที่กำลังต่อสู้ 1 ใบ : ปรับ POWER ตั้งต้นของ Avatar ที่เลือก ให้กลายเป็น 0 จนจบ Battle Phase",
    subtype: MagicSubtype.React,
    cost: 0,
    symbol: Symbol.Hermit,
  },
  {
    name: "ตุ๊กตางูพันคอ",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-047",
    rare: Rarity.SR,
    mainEffect:
      "Avatar ที่สวมใส่การ์ดใบนี้ POWER +2  \nหาก Avatar ที่สวมใส่การ์ดใบนี้ โจมตีได้ ต้องสั่งโจมตี",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "น้ำซุปชาบู",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-048",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "Avatar ที่สวมใส่การ์ดใบนี้ POWER +3 \nเมื่อ Avatar ที่สวมใส่การ์ดใบนี้โจมตี หลังจากโจมตี จนกว่าจะจบ End Phase ถัดไปของเราจะไม่เปลี่ยนเป็นสภาพตื่นทุกกรณี",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Mage,
    customLimit: 1,
  },
  {
    name: "Micro Plaza สะพานพลาสติก",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-049",
    rare: Rarity.SR,
    mainEffect: "เทิร์นละครั้งใน Main Phase : สามารถ ทิ้งการ์ดจากบนมือ 1 ใบ  นำ Modification Magic 1 ใบ จาก ใน Deck ฝ่ายเราขึ้นมือ จากนั้น สับ Deck",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Robot,
    customLimit: 1,
  },
  {
    name: "SD Plaza สายเหนือเก่า",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-050",
    rare: Rarity.SR,
    mainEffect:
      "เทิร์นละครั้ง เลือกปฏิบัติ\n1) ทิ้งการ์ดจากบนมือเรา 1 ใบ : สอดแนม Deck ฝ่ายเรา 3 ใบ เลือก Avatar 1 ใบ จากการ์ดที่สอดแนม มาวางไว้ที่ Magic Zone ฝ่ายเราในสภาพตื่น การ์ดที่เหลือนำไว้ใต้ Deck\n2) เลือก Avatar ใน Magic Zone ฝ่ายเรา 1 ใบ : อัญเชิญ การ์ดใบนั้น มาบน Avatar Zone ฝ่ายเราในสภาพตื่น",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Robot,
    customLimit: 1,
  },
  {
    name: "สมชายห้องเช่าพันล้าน",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-051",
    rare: Rarity.UR,
    mainEffect:
      "เทิร์นละครั้งใน Main Phase สามารถทิ้งการ์ดจากมือ 1 ใบ : สามารถอัญเชิญ Avatar \"\"เสามงคล\"\" 1 ใบ จากใน Deck ลง Avatar Zone จากนั้นสับ Deck\nก่อนเริ่ม Main Phase จั่วการ์ดตามจำนวนการ์ด \"\"เสามงคล\"\" ที่อยู่บนสนามของตนเอง ใบละ 1 ใบ",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Mage,
    customLimit: 1,
  },
  {
    name: "อุบัติเหตุ!!!",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-052",
    rare: Rarity.UR,
    mainEffect: "เมื่อมี Avatar อัญเชิญลงมาบนสนาม : ทำลาย Avatar ตัวนั้น",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ไม้เกาหลัง",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-053",
    rare: Rarity.SR,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ได้รับความสามารถ เตะไข่ (Avatar ใบนี้สามารถโจมตีไปที่ LIFE Card ได้โดยตรง แม้ว่า Avatar Zone ของอีกฝ่ายจะมี Avatar อยู่ก็ตาม)",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Rat,
    customLimit: 2,
  },
  {
    name: "รถถังลงถนน",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-054",
    rare: Rarity.UR,
    mainEffect: "อัญเชิญ Avatar \"รถถัง\" ที่มีค่า Cost ไม่เกิน 5 จาก Deck เราลงสนามฝั่งเรา 1 ตัว และ อีกฝ่ายอัญเชิญ Avatar ที่มีค่า Cost ไม่เกิน 5 จาก Deck อีกฝ่ายลงสนามอีกฝ่าย 1 ตัว",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Soldier,
  },
  {
    name: "ถาดหลุม",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-055",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง ใน Main phase เรา : ทอยเหรียญ ถ้าออกหัว Avatar ที่สวมใส่การ์ดใบนี้ POWER +2  , ถ้าออกก้อย Avatar ที่สวมการ์ดใบนี้ POWER -2",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Soldier,
  },
  {
    name: "ความเจริญ",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-056",
    rare: Rarity.UR,
    variants: [Rarity.PR],
    mainEffect: "จั่วการ์ดจาก Deck เรา 2 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
    customLimit: 2,
  },
  {
    name: "เมตตาระยะยาว",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-057",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "ทำลาย Avatar บนสนามอีกฝ่ายทุกใบ",
    subtype: MagicSubtype.Normal,
    cost: 0,
    symbol: Symbol.God,
    ex: "Only #1",
  },
  {
    name: "ริกกี้ นักปลอมแปลง",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-058",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อ Avatar บนสนามของเราถูกทำลายจากการต่อสู้ สามารถใช้การ์ดใบนี้ได้ : เปลี่ยนการควบคุม Avatar ที่อยู่ในสภาพนอน จากบนสนามอีกฝ่ายมาบนสนามฝ่ายเรา แล้วนำการ์ดใบนี้ไปเป็นModification Magic ถ้าการ์ดใบนี้ถูกทำลาย ส่ง Avatar กลับขึ้นมือเจ้าของ",
    subtype: MagicSubtype.React,
    cost: 0,
    symbol: Symbol.Insect,
    customLimit: 1,
  },
  {
    name: "โรงบาล",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-059",
    rare: Rarity.SR,
    mainEffect: "เทิร์นละครั้ง สามารถทิ้งการ์ดจากมือ 1 ใบ : เลือกการ์ด Avatar จากในนรก 1 ใบที่ Cost ไม่เกิน 3 ขึ้นมือได้ ในเทิร์นนี้การ์ดที่ขึ้นมือจากความสามารถ \"โรงบาล\" จะไม่สามารถอัญเชิญ,ไม่สามารถใช้ความสามารถและโจมตีไม่ได้ รวมถึงการ์ดชื่อเดียวกันกับที่ขึ้นมือทั้งหมด",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "ประตูนรก",
    type: CardType.Magic,
    soi: 1,
    print: "CC01-060",
    rare: Rarity.UR,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้ง Avatar {Symbol นรก} 1 ใบจากบนมือ : อัญเชิญ Avatar \"นายนิรยบาล\" ค่า Cost ไม่เกิน 4 จาก นรกฝ่ายเรา 1 ใบ ลงบน Avatar Zone ฝ่ายเรา",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Hell,
  }
]);
