import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_CC02: Card[] = createCards([
  {
    name: "มหาราชาสีนิล",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-001",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "ลูกฮึด โล่มนุษย์ \nอัตโนมัติ เมื่อ Avatar ใบนี้ต่อสู้ : POWER +2 จนจบการต่อสู้ \nอัตโนมัติ เมื่อ Avatar ใบนี้จะถูกทำลายจากการต่อสู้ สามารถนำ Modification ที่สวมใส่การ์ดนี้อยู่ทั้งหมดลงนรก : Avatar ใบนี้จะไม่ถูกทำลาย\nคำสั่งเสีย : Avatar บน Avatar Zone ฝ่ายเรา POWER +1",
    cost: 6,
    gem: 2,
    power: 6,
    symbol: Symbol.Human,
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "บัมเบิ้ลแบงค์",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-002",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เทิร์นละครั้ง สั่งใช้ จากในนรก หากบน Avatar Zone ฝ่ายเราไม่มี Avatar ชื่อนี้อยู่ ทิ้งการ์ดบนมือ 1 ใบ : อัญเชิญ Avatar ใบนี้ จากในนรก ลงบน Avatar Zone ฝ่ายเรา",
    cost: 3,
    gem: 0,
    power: 2,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "คุณโดม ผู้จัดการทีมการ์ด",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-003",
    rare: Rarity.UR,
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : ทอยลูกเต๋า 1 ครั้ง POWER ของ Avatar ใบนี้จะเพิ่มขึ้นตามผลลัพธ์ของลูกเต๋าที่ออกจนจบเทิร์น\nคำสั่งเสีย : นำการ์ดนี้จากนรกกลับเข้า Deck แล้วสับ",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "นักดาบตะวันแดง",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-004",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "อัตโนมัติ เมื่อ Avatar ใบนี้ไม่ถูกทำลายจากการถูกโจมตี : ทำลาย Avatar บน Avatar Zone ของฝ่ายตรงข้าม 1 ใบ \n#Avatar ใบนี้นับเป็น Symbol หุ่นยนต์ ด้วย",
    cost: 5,
    gem: 2,
    power: 5,
    symbol: Symbol.Human,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "หมีบราซิล",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-005",
    rare: Rarity.SR,
    mainEffect:
      "จุติ แสดงการ์ด Avatar สีแดง จากบนมือ 1 ใบ : เลือกปฏิบัติ \n1) เลือก Avatar บน Avatar Zone ฝ่ายเรา 1 ใบ POWER +2\n2) จั่วการ์ด 2 ใบ ทิ้งการ์ด 1 ใบ",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "ซุส เทพเจ้าสูงสุดแห่งโอลิมปัส",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-006",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ : เลือกการ์ดที่ชอบ 2 ใบ จากใน Deck เรา และนำขึ้นมือ จากนั้นสับ Deck",
    cost: 7,
    gem: 2,
    power: 6,
    symbol: Symbol.God,
    color: Color.Blue,
    ex: "Only #1",
  },
  {
    name: "ไอ้ชนหมา",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-007",
    rare: Rarity.SR,
    mainEffect: "จุติ เซ่นไหว้ Avatar {symbol สัตว์} 1 ใบ : สอดแนม 7 ใบ นำ Avatar Cost 5 หรือ ต่ำกว่า 1 ใบ จากที่ สอดแนม ขึ้นมือ ถ้า Avatar ที่เลือก Cost 2 หรือต่ำกว่า สามารถ อัญเชิญ Avatar ใบนั้นลงบน Avatar Zone แทนได้ จากนั้นสับ Deck",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ลุงน้อย พ่อค้าไก่ย่าง",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-008",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "พอดี จุติ : จั่วการ์ด 3 ใบ จากนั้น นำการ์ดบนมือ 2 ใบ กลับเข้า Deck จากนั้น สับ Deck",
    cost: 3,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "บึงทมิฬ  People - คุณปลาชด",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-009",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ Land Magic Zone มี \"บึงทมิฬ\" อยู่ ผู้เล่นทุกคน จะสามารถ ควบคุม Avatar ที่ไม่ใช่ Symbol ปลา ใน Avatar Zone ได้เพียง 1 ใบ",
    cost: 6,
    gem: 1,
    power: 4,
    symbol: Symbol.Fish,
    color: Color.Blue,
  },
  {
    name: "หมีขาว",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-010",
    rare: Rarity.SR,
    mainEffect:
      "จุติ แสดงการ์ด Avatar สีฟ้า จากบนมือ 1 ใบ : เลือกปฏิบัติ \n1) สอดแนม 5 ใบ อัญเชิญ Avatar Cost ไม่เกิน 3 จากที่สอดแนม ลง Avatar Zone การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ\n2) สอดแนม 5 ใบ นำ Avatar 1 ใบ จากที่ สอดแนม ขึ้นมือ การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Blue,
  },
  {
    name: "ตุตันคาเมน ฟาโรห์ทองคำ",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-011",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ : เลือกปฏิบัติ\n1) อัญเชิญ จุติ Avatar ที่ไม่ใช่ {only} กี่ใบก็ได้ แต่ Cost ของทุกใบรวมกัน ไม่เกิน 8 จากนรกใครก็ได้ ลงบน Avatar Zone ฝ่ายเรา\n2) อัญเชิญ จุติ Avatar 1 ใบ จากนรกใครก็ได้ ลงบน Avatar Zone ฝ่ายเรา\n#Avatar ใบนี้ไม่สามารถถูกอัญเชิญจากนรกได้",
    cost: 5,
    gem: 2,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Purple,
    ex: "Only #1",
  },
  {
    name: "เตียวเสียน จันทร์หลบโฉมสุดา",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-012",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "ต่อเนื่อง ตราบเท่าที่มี  Avatar \"ขุนพล\" สีม่วง ที่เป็น Symbol ชาวต่างชาติ ใน Avatar Zone ฝ่ายเรา Avatar ใบนี้ จะไม่สามารถถูกโจมตี\nเทิร์นละครั้ง สั่งใช้ : เปลี่ยนสภาพ Avatar บน Avatar Zone ของฝ่ายตรงข้ามทั้งหมด เป็นสภาพตื่น",
    cost: 2,
    gem: 4,
    power: 1,
    symbol: Symbol.Foreigner,
    color: Color.Purple,
  },
  {
    name: "ตั๋งโต๊ะ ขุนพลฮ่องเต้ทรราช",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-013",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ : นำ Avatar \"ขุนพล\" สีม่วง ที่เป็น Symbol ชาวต่างชาติ 1 ใบ ที่ไม่ได้ชื่อ ตั๋งโต๊ะ ขุนพลฮ่องเต้ทรราช จาก นรกเราขึ้นมือ จากนั้น Avatar ใบนั้นได้รับ \"Cost บนมือ ของการ์ดใบนี้ -3\" จนจบเทิร์น\nอัตโนมัติ เทิร์นละครั้ง ในเทิร์นฝ่ายเรา เมื่อ Avatar ฝ่ายตรงข้าม เปลี่ยนสภาพ : จั่วการ์ด 1 ใบ",
    cost: 4,
    gem: 0,
    gemColor: Color.Purple,
    power: 5,
    symbol: Symbol.Foreigner,
    color: Color.Purple,
  },
  {
    name: "แร้งทึ้งศพ",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-014",
    rare: Rarity.SR,
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง เมื่อมีการ ธรณีสูบ : จั่วการ์ด 1 ใบ",
    cost: 2,
    gem: 1,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Purple,
  },
  {
    name: "หมีดำ",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-015",
    rare: Rarity.SR,
    mainEffect:
      "จุติ แสดงการ์ด Avatar สีม่วง จากบนมือ 1 ใบ : เลือกปฏิบัติ \n1) ธรณีสูบ 2 ใบ : อัญเชิญ Avatar จากในนรก POWER ไม่เกิน 2 ที่ไม่ใช่ {only} 1 ใบ\n2) ธรณีสูบ 2 ใบ : เลือกการ์ดจากในนรก ที่ไม่ใช่ {only} 1 ใบ กลับเข้าใต้ Deck",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Purple,
    gemColor: "ม่วง",
  },
  {
    name: "อินาริ โอคามิ แห่งการเก็บเกี่ยว",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-016",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "จุติ : นำ Avatar ใบนี้ไปไว้ใน Magic Zone\nต่อเนื่อง Avatar ทุกใบบน Avatar Zone ฝ่ายเรา POWER +1 และ POWER +1 อีก ต่อจำนวนการ์ดในนรกเราทุกๆ 15 ใบ \nอัตโนมัติ ในช่วง End Phase ของเรา : จั่วการ์ด 1 ใบ และต่อจำนวนการ์ดในนรกเราทุกๆ 15 ใบ จั่วการ์ดเพิ่ม 1 ใบ \n#Avatar ใบนี้ สามารถใช้ความสามารถจาก Magic Zone ได้",
    cost: 6,
    gem: 4,
    power: 0,
    symbol: Symbol.God,
    color: Color.Green,
    ex: "Only #1",
  },
  {
    name: "มอร์ฟีน Overdose",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-017",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "ต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรา มี Avatar \"Overdose\" ชื่อไม่ซ้ำกัน 4 ใบ ฝ่ายตรงข้าม ไม่สามารถใช้ React Magic และ Normal Magic ได้ \nเทิร์นละครั้ง สั่งใช้ หงาย LIFE Card ของเรา 1 ใบ : เลือก Avatar 1 ใบ ในนรกของผู้เล่นใดก็ได้ อัญเชิญ Avatar ใบนั้นลงบน Avatar Zone ของเจ้าของใบนั้น หาก Avatar ใบนั้น เป็น Avatar ของฝ่ายตรงข้าม Avatar ใบนั้นจะไม่สามารถสั่งใช้ความสามารถได้",
    cost: 6,
    gem: 4,
    power: 6,
    symbol: Symbol.Robot,
    color: Color.Green,
    ex: "Only #1",
  },
  {
    name: "หุ่นพิฆาต 300%",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-018",
    rare: Rarity.SR,
    mainEffect: "ต่อเนื่อง ผู้เล่นทุกคนไม่สามารถ อัญเชิญ Avatar จาก Deck ได้",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Robot,
    color: Color.Green,
  },
  {
    name: "ราชาใบก้อน",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-019",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "โล่มนุษย์ \nเทิร์นละครั้ง สั่งใช้ Avatar ใบนี้ Cost -1 : ทำลาย Avatar Cost เท่ากับหรือต่ำกว่า Avatar ใบนี้ 1 ใบ บน Avatar Zone ฝ่ายตรงข้าม",
    cost: 5,
    gem: 3,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Green,
    gemColor: "เขียว",
  },
  {
    name: "หมีเหลือง",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-020",
    rare: Rarity.SR,
    mainEffect:
      "จุติ แสดงการ์ด Avatar สีเขียว จากบนมือ 1 ใบ : เลือกปฏิบัติ \n1) เลือก Avatar 1 ใบ จนกว่าจะจบเทิร์นถัดไปของฝ่ายตรงข้าม Avatar ใบนั้นไม่ถูกทำลายจากการต่อสู้ \n2) เลือก Avatar 1 ใบ จนกว่าจะจบเทิร์นถัดไปของฝ่ายตรงข้าม Avatar ใบนั้นไม่ได้รับผลของ Magic Card ฝ่ายตรงข้าม",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Green,
    gemColor: "เขียว",
  },
  {
    name: "ปื้ด เด็กเปรต",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-021",
    rare: Rarity.SR,
    mainEffect: "ต่อเนื่อง การ์ดใบนี้ เพิ่ม POWER  ตามจำนวน LIFE Card ฝ่ายเรา ที่ถูกหงายอยู่ ใบละ 2",
    cost: 4,
    gem: 0,
    power: 0,
    symbol: Symbol.Pret,
    color: Color.Red,
  },
  {
    name: "คนรวย",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-022",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง ในเทิร์นใครก็ได้ เมื่ออีกฝ่ายใช้ความสามารถการ์ด นำการ์ด 1 ใบ บนมือเราให้อีกฝ่าย : ยกเลิกความสามารถของการ์ดนั้น ความสามารถนี้นับเป็นการใช้ React Magic",
    cost: 5,
    gem: 4,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "นางอัปสร",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-023",
    rare: Rarity.SR,
    mainEffect:
      "อัตโนมัติ เมื่อการ์ดใบนี้สั่งโจมตี : ฝ่ายตรงข้ามไม่สามารถสั่งใช้งาน React Magic จนจบการต่อสู้ \n#การ์ดใบนี้นับเป็นชื่อ \"พระนารายณ์",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "จอมหักกระดูก",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-024",
    rare: Rarity.SR,
    mainEffect:
      "โล่มนุษย์\nอัตโนมัติ เมื่อ Avatar ใบนี้ต่อสู้กับ Avatar ของฝ่ายตรงข้าม : POWER ของ Avatar ที่ต่อสู้ด้วยจะถูกปรับเป็น POWER ตั้งต้น จนจบการต่อสู้นั้น",
    cost: 6,
    gem: 2,
    power: 5,
    symbol: Symbol.Alien,
    color: Color.Red,
  },
  {
    name: "โจอี้ นักบอลขาหัก",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-025",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost ในการอัญเชิญ Avatar สีแดง : POWER +1 ให้กับ Avatar ที่ถูกอัญเชิญจนจบเทิร์น",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Foreigner,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "ซันนี่",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-026",
    rare: Rarity.SR,
    mainEffect: "ต่อเนื่อง Avatar \"กุ่ย\" \"ฮอล\" \"นาย\" บน Avatar Zone ฝ่ายเรา POWER+1",
    cost: 2,
    gem: 4,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "จ่างู อสรพิษพิฆาตจักรกล",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-027",
    rare: Rarity.SR,
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar {symbol หุ่นยนต์} : ทำลาย Avatar ใบที่เป็นเป้าการโจมตี",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ไดโนกาฬสินธุ์ - กินรีมิมัส",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-028",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ สอดแนม 5 ใบ : เลือก Avatar {symbol กะปอม} 1 ใบที่มี Cost 3 หรือต่ำกว่าอัญเชิญลง Avatar zone ฝ่ายเรานำที่เหลือกลับเข้า Deck แล้วสับ",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Lizard,
    color: Color.Blue,
  },
  {
    name: "ริกกี้ คุณตาใจดี",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-029",
    rare: Rarity.SR,
    mainEffect: "ต่อเนื่อง Avatar ใบนี้ไม่รับผลจากความสามารถของการ์ด Magic ฝ่ายตรงข้าม",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "มนุษย์รัททาทุย",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-030",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง POWER ของการ์ดใบนี้จะเพิ่มขึ้นตามจำนวน Avatar {symbol รัททาทุย} บน Avatar Zone ฝ่ายเราใบละ 1",
    cost: 4,
    gem: 1,
    power: 1,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "บอสทุเรียน",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-031",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost เพื่ออัญเชิญ Avatar สีฟ้า : สอดแนม 1 ใบ ถ้าการ์ดใบนั้นเป็น Avatar Symbol เดียวกับ Avatar ที่ถูกอัญเชิญ นำการ์ดใบนั้นขึ้นมือ ถ้าไม่ใช่นำการ์ดใบนั้นไว้ที่เดิม",
    cost: 0,
    gem: 4,
    gemColor: Color.Blue,
    power: 0,
    symbol: Symbol.Tree,
    color: Color.Blue,
  },
  {
    name: "ศาลพระภูมิ",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-032",
    rare: Rarity.UR,
    mainEffect:
      "จุติ : อัญเชิญ Avatar {symbol ผี} จากใน Deck 1 ใบ ลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck\nต่อเนื่อง ตราบเท่าที่มีการ์ด Avatar {symbol ผี} ใบอื่นบน Avatar Zone ฝ่ายเรา อีกฝ่ายจะไม่สามารถเลือก Avatar \"ศาลพระภูมิ\" เป็นเป้าหมายการโจมตีได้",
    cost: 4,
    gem: 1,
    power: 2,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "สารวัตร ตำรวจสัมภเวสี",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-033",
    rare: Rarity.UR,
    mainEffect: "จุติ : สามารถนำการ์ด \"ตำรวจสัมภเวสี\" 1  ใบ จาก Deck เราขึ้นมือ จากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "แดรกคูลา",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-034",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ : Avatar ใบนี้ ได้รับ \"เมื่อ Avatar ใบนี้ ถูกทำลาย ในเทิร์นถัดมาของเรา อัญเชิญ Avatar ใบนี้จากนรกลงบน Avatar Zone ฝ่ายเราในช่วง Battle Phase ของเทิร์นนั้น",
    cost: 6,
    gem: 2,
    power: 4,
    symbol: Symbol.Ghost,
    color: Color.Purple,
    ex: "Only #1",
  },
  {
    name: "Ecycle",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-035",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดจากบนมือ 1 ใบ : เลือกการ์ดในนรกเรา 1 ใบ นำกลับเข้าใต้ Deck จากนั้น จั่วการ์ด 1 ใบ",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: Symbol.Robot,
    color: Color.Purple,
  },
  {
    name: "วิไลวรรณ แม่แบงค์",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-036",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็น Cost เพื่ออัญเชิญ Avatar สีม่วง : สอดแนม 1 ใบ หลังจากนั้นเลือกนำการ์ดใบนั้นไว้บนสุดของ Deck หรือ ส่งลงนรก",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Purple,
    gemColor: "ม่วง",
  },
  {
    name: "รถถัง B66 - เอ็กซ์เซลเซอร์",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-037",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง ถ้าไม่มี Avatar สวมใส่ Avatar ใบนี้ จะไม่สามารถโจมตีได้ และ ไม่สามารถใช้ Avatar ชื่อซ้ำกันในการสวมใส่การ์ดใบนี้",
    cost: 4,
    gem: 1,
    power: 5,
    symbol: Symbol.Robot,
    color: Color.Green,
  },
  {
    name: "พาลี",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-038",
    rare: Rarity.SR,
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ต่อสู้ : Avatar ที่ต่อสู้ด้วย POWER - 2 และ Avatar ตัวนี้ POWER + 2 จนจบการต่อสู้นั้น",
    cost: 7,
    gem: 2,
    power: 4,
    symbol: Symbol.Animal,
    color: Color.Green,
  },
  {
    name: "พญายักษ์ ทศกัณฐ์",
    type: CardType.Avatar,
    soi: 1,
    print: "CC02-039",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดบนมือ 1 ใบ : อัญเชิญ Avatar {symbol ยักษ์} ที่มี POWER 3 ยกเว้น \"ทศกัณฐ์\" จาก Deck ฝ่ายเรา 1 ใบลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 5,
    symbol: Symbol.Giant,
    color: Color.Green,
  },
  {
    name: "วีรชนชีวภาพ",
    type: CardType.Avatar,
    soi: 2,
    print: "CC02-040",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect:
      "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost เพื่ออัญเชิญ Avatar สีเขียว : \nAvatar ที่ถูกอัญเชิญจะไม่รับผลจากความสามารถ Magic Card ของฝ่ายตรงข้าม จนจบเทิร์นต่อไปของฝ่ายตรงข้าม",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Green,
    gemColor: "เขียว",
  },
  {
    name: "มรดกของพระอิศวร",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-041",
    rare: Rarity.SR,
    mainEffect:
      "สอดแนม 2 ใบ : เลือก การ์ด สีแดง จากที่ สอดแนม 1 ใบ ขึ้นมือ ที่เหลือนำไปไว้ใต้ Deck\nจากนั้นนำการ์ดใบนี้ วางไว้บน Magic Zone \nสามารถสั่งใช้ได้หลังจากการ์ดใบนี้ถูกวางไว้ใน Magic Zone แล้ว 1 เทิร์น\nสั่งใช้ จาก Magic Zone ทำลายการ์ดใบนี้ : อัญเชิญ Avatar สีแดง 1 ใบ จากมือทันที โดยที่ Avatar ใบนั้นจะค่า Cost ลด 2",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.God,
  },
  {
    name: "หนังสือเอาตัวรอดของกุ่ย",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-042",
    rare: Rarity.SR,
    mainEffect:
      "สอดแนม 2 ใบ : เลือก การ์ด  สีฟ้า จากที่ สอดแนม 1 ใบ ขึ้นมือ ที่เหลือนำไปไว้ใต้ Deck\nจากนั้นนำการ์ดใบนี้ วางไว้บน Magic Zone \nสามารถสั่งใช้ได้หลังจากการ์ดใบนี้ถูกวางไว้ใน Magic Zone แล้ว 1 เทิร์น\nสั่งใช้ จาก Magic Zone ทำลายการ์ดใบนี้ : อัญเชิญ Avatar สีฟ้า 1 ใบ จากมือทันที โดยที่ Avatar ใบนั้นจะค่า Cost ลด 2",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Human,
  },
  {
    name: "หมอนข้างมฤตยูเทวี",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-043",
    rare: Rarity.SR,
    mainEffect:
      "สอดแนม 2 ใบ : เลือก การ์ด สีม่วง จากที่ สอดแนม 1 ใบ ขึ้นมือ ที่เหลือนำไปไว้ใต้ Deck\nจากนั้นนำการ์ดใบนี้ วางไว้บน Magic Zone \nสามารถสั่งใช้ได้หลังจากการ์ดใบนี้ถูกวางไว้ใน Magic Zone แล้ว 1 เทิร์น\nสั่งใช้ จาก Magic Zone ทำลายการ์ดใบนี้ : อัญเชิญ Avatar สีม่วง 1 ใบ จากมือทันที โดยที่ Avatar ใบนั้นจะค่า Cost ลด 2",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Hell,
  },
  {
    name: "ใบรับสมัครพนักงานลงกา",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-044",
    rare: Rarity.SR,
    mainEffect:
      "สอดแนม 2 ใบ : เลือก การ์ด สีเขียว จากที่ สอดแนม 1 ใบ ขึ้นมือ ที่เหลือนำไปไว้ใต้ Deck\nจากนั้นนำการ์ดใบนี้ วางไว้บน Magic Zone \nสามารถสั่งใช้ได้หลังจากการ์ดใบนี้ถูกวางไว้ใน Magic Zone แล้ว 1 เทิร์น\nสั่งใช้ จาก Magic Zone ทำลายการ์ดใบนี้ : อัญเชิญ Avatar สีเขียว1 ใบ จากมือทันที โดยที่ Avatar ใบนั้นจะค่า Cost ลด 2",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Giant,
  },
  {
    name: "สิงสู่เพื่อสู่สม",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-045",
    rare: Rarity.UR,
    mainEffect:
      "เซ่นไหว้ Avatar ที่มี Cost ตั้งแต่ 3 ขึ้นไป 1 ใบ : ฝ่ายตรงข้ามเลือก Avatar 1 ใบ บน Avatar Zone ตนเอง นำการ์ดใบนี้ไปสวมใส่ให้ Avatar ที่เลือกและเปลี่ยนการควบคุมมาบน Avatar Zone ฝ่ายเรา จากนั้นเปลี่ยนประเภท Magic ของการ์ดใบนี้เป็น Modification Magic \nหากการ์ดใบนี้ ออกจากสนาม เปลี่ยนการควบคุม ของ Avatar ที่สวมใส่กลับไปที่เจ้าของเดิม",
    subtype: MagicSubtype.Normal,
    cost: 0,
    symbol: Symbol.Giant,
  },
  {
    name: "กาจอก",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-046",
    rare: Rarity.SR,
    mainEffect: "เลือก Avatar ของเราที่กำลังต่อสู้อยู่ 1 ใบ : หาก Avatar ที่ต่อสู้กับ Avatar ที่เลือก อยู่ในสภาพตื่น ทำลาย Avatar ใบนั้น",
    subtype: MagicSubtype.React,
    cost: 2,
    symbol: Symbol.God,
  },
  {
    name: "เราจะตายแล้วท่านหยุดเถอะ",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-047",
    rare: Rarity.UR,
    mainEffect: "เมื่อ Avatar ฝ่ายตรงข้ามโจมตีเข้ามาที่ LIFE Card และในเทิร์นนี้มี Avatar ฝ่ายเราถูกทำลายจากการต่อสู้ : การโจมตีครั้งนี้จะไม่ทำความเสียหาย LIFE Card",
    subtype: MagicSubtype.React,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "ปืนจักรวุทธ",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-048",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "เมื่อ Avatar ที่สวมใส่การ์ดใบนี้โจมตี POWER +4 จนจบการต่อสู้นั้น และ Avatar ที่สวมใส่การ์ดใบนี้จะต้องโจมตีเสมอ ถ้าทำได้\nเทิร์นละครั้ง อัตโนมัติ เมื่อ Avatar ที่สวมใส่การ์ดใบนี้โจมตีและทำลาย Avatar ของฝ่ายตรงข้ามสำเร็จ เปลี่ยน Avatar ใบนี้เป็นสภาพตื่น หลังจบ Battle Phase ที่ใช้ความสามารถนี้ Avatar ที่สวมใส่การ์ดใบนี้จะไม่เปลี่ยนเป็นสภาพตื่นทุกกรณี ยกเว้นความสามารถของการ์ดใบนี้\nเทิร์นละครั้ง สั่งใช้ นำการ์ดใบนี้ในสภาพสวมใส่ขึ้นมือ เปลี่ยน Avatar ที่เคยสวมใส่การ์ดใบนี้เป็นสภาพตื่น",
    subtype: MagicSubtype.Modification,
    cost: 0,
    symbol: Symbol.God,
    ex: "Only #1",
  },
  {
    name: "ดินแดนแห่งความหลากหลาย",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-049",
    rare: Rarity.SR,
    mainEffect: "ถ้าบน Avatar Zone ฝ่ายเรา มี Avatar ตั้งแต่ 2 ใบ ขึ้นไป และไม่มี Avatar ที่มี Symbol เหมือนกัน Avatar ทุกใบ POWER +1",
    subtype: MagicSubtype.Land,
    cost: 3,
    symbol: Symbol.WonderAnimal,
  },
  {
    name: "วิหารเจ้าสมุทร",
    type: CardType.Magic,
    soi: 2,
    print: "CC02-050",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ เปลี่ยนสภาพ Avatar {symbol ปลา} 1 ใบบน Avatar Zone เป็น สภาพนอน สอดแนม 3 ใบ เลือกการ์ด Symbol ปลา 1 ใบ ขึ้นมือ ที่เหลือ ทิ้งลงนรก\n#การ์ดใบนี้นับเป็นชื่อ บึงทมิฬ",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Fish,
  },
  {
    name: "ช่วยโลกใบนี้ไว้",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-051",
    rare: Rarity.SR,
    mainEffect: "หงาย LIFE Card ของเราทุกใบ : ในเทิร์นนี้ Avatar {symbol เปรต} ที่อัญเชิญในเทิร์นนี้จะได้รับความสามารถ ไม่รับผลจากความสามารถของการ์ดทุกประเภท , ได้รับความสามารถ เตะไข่ โดยที่ความสามารถ \"โล่มนุษย์\" จะไม่สามารถใช้ได้",
    subtype: MagicSubtype.Normal,
    cost: 4,
    symbol: Symbol.Pret,
  },
  {
    name: "จมน้ำ",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-052",
    rare: Rarity.UR,
    mainEffect: "ผู้เล่นทุกคน เลือก Avatar บน Avatar Zone ของตนเอง 1 ใบ นำกลับเข้าใต้ Deck เจ้าของ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ล้มโต๊ะ",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-053",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "นำการ์ดบนมือของผู้เล่นทุกคนทั้งหมดกลับเข้า Deck ตนเองแล้วสับ จากนั้นแต่ละฝ่ายจั่วการ์ดจาก Deck คนละ 4 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "เอากล้วยมานี่ย์ !!!!!!",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-054",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อ Avatar อีกฝ่ายประกาศโจมตี Avatar ฝ่ายเรา เลือก Avatar อีกฝ่าย 1 ใบ : POWER -2 จนจบเทิร์น",
    subtype: MagicSubtype.React,
    cost: 3,
    symbol: Symbol.Mage,
  },
  {
    name: "งับ",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-055",
    rare: Rarity.UR,
    mainEffect: "เมื่อ Avatar ฝ่ายตรงข้ามโจมตี : สอดแนม  2 ใบ : เลือกการ์ด Avatar {Symbol กะปอม} 1 ใบ จากที่ สอดแนม ขึ้นมือ ถ้ามีการนำการ์ดจากความสามารถข้างต้นขึ้นมือ ทำลาย Avatar ที่โจมตีอยู่ ณ ขณะนั้น และ นำการ์ดที่เหลือกลับเข้า Deck แล้วสับ",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Lizard,
  },
  {
    name: "เหน็บกินมือ",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-056",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เมื่อฝ่ายตรงข้ามจะนำการ์ดจาก Deck ขึ้นมือ ด้วยความสามารถของ Avatar หรือ Magic : ยกเลิกผลความสามารถนั้น",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "แผนการ : แกงส้มตะปูเสียบ",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-057",
    rare: Rarity.SR,
    mainEffect:
      "Avatar ที่สวมใส่การ์ดใบนี้ POWER - 2 \nถ้า Avatar ที่สวมใส่การ์ดใบนี้ POWER = 0 ทำลาย Avatar ตัวที่สวมใส่ การ์ดใบนี้",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ขวานทอง",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-058",
    rare: Rarity.SR,
    mainEffect: "เมื่อ Avatar ที่สวมใส่การ์ดใบนี้ สั่งโจมตี : ผู้ควบคุม Avatar ที่สวมใส่การ์ดใบนี้ จั่วการ์ดจาก Deck  1 ใบ",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.God,
  },
  {
    name: "เขาไกรลาสเอียง",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-059",
    rare: Rarity.SR,
    mainEffect: "เมื่อมีการประกาศโจมตี : ฝ่ายที่ประกาศโจมตี ธรณีสูบ 2 ใบ",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.God,
  },
  {
    name: "มวยทะเลลลลลล",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-060",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "ผู้เล่นทุกคนสั่ง Avatar โจมตีได้แค่ 1 ใบต่อเทิร์น โดยที่การ์ดใบนี้จะอยู่บนสนามได้แค่ 4 เทิร์น",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Hermit,
  },
  {
    name: "ชายจากอนาคต",
    type: CardType.Magic,
    soi: 1,
    print: "CC02-061",
    rare: Rarity.PR,
    mainEffect: "เมื่อมีการใช้ Magic Card : ยกเลิกการใช้ Magic Card ใบนั้น",
    subtype: MagicSubtype.Normal,
    cost: 0,
    symbol: Symbol.Mage,
  }
]);
