import { Card, CardType, Rarity, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_KD01: Card[] = createCards([
  {
    name: "พระนารายณ์ เทพผดุงธรรม",
    type: CardType.Avatar,
    soi: 3,
    print: "KD01-001",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "สั่งใช้ จากบนมือ หลังจากจบการต่อสู้ ที่ Avatar \"พระนารายณ์\" ทำลาย Avatar อีกฝ่ายจากการต่อสู้ : อัญเชิญการ์ดใบนี้โดย ส่ง Avatar \"พระนารายณ์\" 1 ใบ บน Avatar Zone เราลงนรก ถ้าอัญเชิญด้วยความสามารถนี้ สอดแนม 2 ใบ นำการ์ดที่ สอดแนม ทั้งหมดขึ้นมือจากนั้น เนรเทศ Avatar อีกฝ่าย 1 ใบที่มีค่า Cost เท่ากับหรือน้อยกว่าผลรวมของ Cost การ์ดที่ สอดแนม ด้วยความสามารถนี้",
    cost: 8,
    gem: 0,
    power: 8,
    symbol: Symbol.God,
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "ร่างอวตารพระนารายณ์ - นรสิง",
    type: CardType.Avatar,
    soi: 3,
    print: "KD01-002",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "สั่งใช้ จากบนมือ หลังจากจบการต่อสู้ ที่ Avatar \"พระนารายณ์\" ทำลาย Avatar อีกฝ่ายจากการต่อสู้ : อัญเชิญการ์ดใบนี้โดย ส่ง Avatar \"พระนารายณ์\" 1 ใบ บน Avatar Zone เราลงนรก ถ้าอัญเชิญด้วยความสามารถนี้ ทำลาย Avatar บนสนาม ฝ่ายตรงข้าม 1 ใบที่ Cost ไม่เกิน 4 จากนั้นในช่วง End Phase ส่งการ์ดนี้ลงนรกและอัญเชิญ Avatar \"พระนารายณ์\" ชื่ออื่น 1 ใบ จากนรกลงบน Avatar Zone ฝ่ายเรา #สามารถใช้ความสามารถของ Avatar ชื่อ ร่างอวตารพระนารายณ์ - นรสิง ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ร่างอวตารพระนารายณ์ - เกษียรสมุทร",
    type: CardType.Avatar,
    soi: 3,
    print: "KD01-003",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "สั่งใช้ จากบนมือ หลังจากจบการต่อสู้ ที่ Avatar \"พระนารายณ์\" ทำลาย Avatar อีกฝ่ายจากการต่อสู้ : อัญเชิญการ์ดใบนี้โดย ส่ง Avatar \"พระนารายณ์\" 1 ใบ บน Avatar Zone เราลงนรก ถ้าอัญเชิญด้วยความสามารถนี้ เลือก Avatar {symbol เทพ} 1 ใบ ที่อยู่ในสภาพนอน บน Avatar Zone ฝ่ายเรา เปลี่ยนเป็นสภาพตื่น จากนั้นช่วง End Phase ส่งการ์ดนี้ลงนรกและอัญเชิญ Avatar \"พระนารายณ์\" ชื่ออื่น 1 ใบ จากนรกลงบน Avatar Zone ฝ่ายเรา #สามารถใช้ความสามารถของ Avatar ชื่อ ร่างอวตารพระนารายณ์ - เกษียรสมุทร ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "พระอินทร์ เทพขยัน",
    type: CardType.Avatar,
    soi: 1,
    print: "KD01-007",
    rare: Rarity.SCR,
    mainEffect: "จุติ : สอดแนม 3 ใบ เลือก การ์ด Symbol เทพ 1 ใบ จากที่สอดแนม และนำขึ้นมือ การ์ดที่เหลือนำไปไว้ใต้ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ช่างแอร์ดวงซวย",
    type: CardType.Avatar,
    soi: 1,
    print: "KD01-012",
    rare: Rarity.SCR,
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "4 / กล่อง",
  }
]);