import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_KD02: Card[] = createCards([
  {
    name: "ปีศาจแห่งพันรเลือด เมฟิสโตเฟเลส",
    type: CardType.Avatar,
    soi: 3,
    print: "KD02-001",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "สั่งใช้ จากมือ ถ้าในนรกฝ่ายเรา มี Avatar {symbol นรก} ที่ชื่อไม่ซ้ำกันตั้งแต่ 7 ชื่อขึ้นไป ทั้งการ์ดจากบนมือ 2 ใบ : อัญเชิญ Avatar ใบนี้ ลง Avatar Zone \n เทิร์นละครั้ง สั่งใช้ ธรณีสูบ 5 ใบ : ทำลาย Avatar ทุกใบบนสนามของผู้เล่นทุกคน ยกเว้นการ์ดใบนี้ \n อัตโนมัติ ถ้าการ์ดใบนี้ ถูก สอดแนม ด้วย ความสามารถของ \"สุวรรณ\" : สามารถนำการ์ดใบนี้ขึ้นมือได้ #Avatar ใบนี้ไม่สามารถ อัญเชิญ ได้ นอกจาก ความสามารถ ของ Avatar ใบนี้",
    cost: 8,
    gem: 2,
    power: 7,
    symbol: Symbol.Hell,
    color: Color.Purple,
    ex: "Only #1",
  },
  {
    name: "ลิลิธ ปีศาจสาวตนแรก",
    type: CardType.Avatar,
    soi: 3,
    print: "KD02-002",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ถ้าในนรกฝ่ายเรามี Avatar {symbol นรก} ที่ชื่อไม่ซ้ำกันตั้งแต่ 4 ใบขึ้นไป เนรเทศ การ์ดในนรกฝ่ายเรา 2 ใบ : เลือกการ์ด {symbol นรก} จาก ในนรก 1 ใบ และนำขึ้นมือ #Avatar ใบนี้ นับเป็นชื่อ \"นายนิรยบาล\"",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "นายนิรยบาล พ่อจีจ้า",
    type: CardType.Avatar,
    soi: 1,
    print: "KD02-006",
    rare: Rarity.SCR,
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้เป็นเป้าหมายโจมตีหรือสั่งโจมตี : ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 2 ใบ POWER +1 จนจบเทิร์น",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "สัญญาเลือด",
    type: CardType.Magic,
    soi: 3,
    print: "KD02-014",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "ธรณีสูบ 3 ใบ หลังจากนั้น จั่วการ์ด 1 ใบ ถ้าในนรกของเรามี Avatar {symbol นรก} ที่ชื่อไม่ซ้ำกันตั้งแต่ 5 ใบขึ้นไป จั่วการ์ด 2 ใบ แทน ถ้าการ์ดใบนี้ถูก ธรณีสูบ : สามารถ เนรเทศ การ์ดใบนี้ อัญเชิญ \"นายนิรยบาล\" 1 ใบ จากนรก ลง Avatar Zone ฝ่ายเรา",
    subtype: MagicSubtype.Normal,
    cost: 0,
    symbol: Symbol.Mage,
  },
  {
    name: "ประตูนรก",
    type: CardType.Magic,
    soi: 1,
    print: "KD02-020",
    rare: Rarity.SCR,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้ง Avatar {Symbol นรก} 1 ใบจากบนมือ : อัญเชิญ Avatar \"นายนิรยบาล\" ค่า Cost ไม่เกิน 4 จาก นรกฝ่ายเรา 1 ใบ ลงบน Avatar Zone ฝ่ายเรา",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Hell,
  }
]);