import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_KD04: Card[] = createCards([
  {
    name: "ราชันย์หุ่นนักรบผู้กล้า : คริติคอล ไมเกรน",
    type: CardType.Avatar,
    soi: 3,
    print: "KD04-001",
    rare: Rarity.UR,
    variants: [Rarity.SCR],
    mainEffect: "ต่อเนื่อง Avatar ใบนี้ไม่สามารถถูกเปลี่ยนการควบคุมได้ เทิร์นละครั้ง สั่งใช้ เนรเทศ Avatar \"ไมเกรน\" ที่ชื่อ แตกต่างกัน 3 ใบจากนรก : เลือกปฏิบัติ \n1) เลือก {mod} \"อาวุรหุ่นนักรบผู้กล้า\" จากนรกได้มากสุด 2 ใบมาสวมใส่ให้ Avatar ใบนี้ \n2) ได้รับ \" อัตโนมัติ เมื่อ Avatar ใบนี้ทำลาย Avatar ฝ่ายตรงข้ามจากการต่อสู้ : ทำความเสียหายต่อ LIFE Card ฝ่ายตรงข้าม 1 ครั้ง\" จนจบเทิร์น",
    cost: 5,
    gem: 2,
    power: 5,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "ด็อกเตอร์ เพน",
    type: CardType.Avatar,
    soi: 3,
    print: "KD04-002",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "จุติ : สอดแนม 5 ใบ เลือก Avatar \"ไมเกรน\" 1 ใบจากที่ สอดแนม และนำขึ้นมือ การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ \n เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดบนมือ 1 ใบ : นำ {mod} \"อาวุรหุ่นนักรบผู้กล้า\" 1 ใบจากนรกขึ้นมือ",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Red,
  },
  {
    name: "ยานเกราะผู้กล้า : ไดบาเรีย",
    type: CardType.Avatar,
    soi: 1,
    print: "KD04-005",
    rare: Rarity.SCR,
    mainEffect:
      "ถ้าการ์ดใบนี้ถูกใช้เป็น Cost ในการอัญเชิญ : จั่วการ์ด 1 ใบ\n\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {Symbol หุ่นยนต์}  ที่มีสีของ Avatar เป็นสีแดงเท่านั้น",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "สุดยอดท่าไม้ตายผู้กล้า THE END",
    type: CardType.Magic,
    soi: 3,
    print: "KD04-012",
    rare: Rarity.SR,
    variants: [Rarity.SCR],
    mainEffect: "เลือก Avatar \"ไมเกรน\" 1 ใบ บน Avatar Zone ฝ่ายเรา : Avatar ใบที่เลือก ได้รับ \" อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : Avatar ใบนี้จะทำการต่อสู้กับ Avatar บน Avatar Zone ฝ่ายตรงข้าม ทุกใบพร้อมกัน\" จนจบเทิร์น \n สั่งใช้ เนรเทศ การ์ดใบนี้ในนรก : นำ {mod}\"อาวุรหุ่นนักรบผู้กล้า\" จากนรกชื่อ แตกต่างกันกี่ใบก็ได้ มาสวมใส่ให้ Avatar \"ไมเกรน\" 1 ใบ บน Avatar Zone ฝ่ายเรา ถ้าการ์ดใบนี้ถูก ธรณีสูบ หรือ สอดแนม ด้วย Avatar \"ไมเกรน\" : นำการ์ดใบนี้ ขึ้นมือ",
    subtype: MagicSubtype.Normal,
    cost: 4,
    symbol: Symbol.Robot,
  },
  {
    name: "อาวุธหุ่นนักรบผู้กล้า \"อีโบล่า ซอร์ด\"",
    type: CardType.Magic,
    soi: 1,
    print: "KD04-013",
    rare: Rarity.SCR,
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar {Symbol หุ่นยนต์} เท่านั้น\n\nAvatar ที่สวมใส่การ์ดใบนี้ POWER + 1 แต่ถ้า Avatar ที่สวมใส่การ์ดใบนี้ชื่อ \"หุ่นนักรบผู้กล้า\" POWER + 3 แทน",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Robot,
  }
]);