import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_ODY1: Card[] = createCards([
  {
    name: "ทาโกะซัง สูตรสวรรค์",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-001",
    rare: Rarity.UR,
    mainEffect: "จุติ : นำ Avatar ชื่อ ทาโกะซัง สูตรมนุษย์ 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 3,
    gem: 0,
    power: 4,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ทาโกะซัง สูตรมนุษย์",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-002",
    rare: Rarity.UR,
    mainEffect: "จุติ : นำ Avatar ชื่อ ทาโกะซัง สูตรนรก 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ทาโกะซัง สูตรนรก",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-003",
    rare: Rarity.UR,
    mainEffect: "จุติ : นำ Avatar ชื่อ ทาโกะซัง สูตรสวรรค์ 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "ทาโกะจัง พนักงานดีเด่น",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-004",
    rare: Rarity.C,
    mainEffect: "จุติ นำ Avatar \"ทาโกะซัง\" 3 ใบ ที่มีชื่อแตกต่างกัน จากนรกเรา กลับเข้า Deck แล้วสับ Deck : จั่วการ์ด 1 ใบ",
    cost: 4,
    gem: 3,
    power: 1,
    symbol: Symbol.Fish,
    color: Color.Blue,
  },
  {
    name: "โอเดนย่ากาย",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-005",
    rare: Rarity.C,
    mainEffect: "การ์ดใบนี้จะโจมตีได้เมื่อใน Avatar Zone ฝ่ายเรา มี \"ทาโกะ\" เท่านั้น",
    cost: 3,
    gem: 2,
    power: 5,
    symbol: Symbol.Alien,
    color: Color.Red,
  },
  {
    name: "พระอิศวร",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-006",
    rare: Rarity.SR,
    mainEffect: "จุติ : เลือก Avatar 1 ใบ POWER - 4 จนจบเทิร์น",
    cost: 6,
    gem: 2,
    power: 5,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "นนทก นิ้วเพชร",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-007",
    rare: Rarity.SR,
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้สั่งโจมตี Avatar {symbol เทพ} : ทำลาย Avatar ตัวที่ต่อสู้ด้วย",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Giant,
    color: Color.Red,
  },
  {
    name: "พระเวสสุกรรม",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-008",
    rare: Rarity.C,
    mainEffect: "จุติ : สอดแนม  5 ใบ นำการ์ด Land Magic 1 ใบ จากที่ สอดแนม ขึ้นมือ นำการ์ดที่เหลือเรียงไว้ใต้ Deck",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ปื้ด เด็กเปรต",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-009",
    rare: Rarity.SR,
    mainEffect: "ต่อเนื่อง การ์ดใบนี้ เพิ่ม POWER  ตามจำนวน LIFE Card ของเรา ที่ถูกหงายอยู่ ใบละ 2",
    cost: 4,
    gem: 0,
    power: 0,
    symbol: Symbol.Pret,
    color: Color.Red,
  },
  {
    name: "หนุมาน",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-010",
    rare: Rarity.C,
    mainEffect: "ต่อเนื่อง การ์ดใบนี้ เพิ่ม POWER  ตามจำนวน Avatar {symbol เทพ} บนสนามฝ่ายเรา ใบละ 1",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Animal,
    color: Color.Red,
  },
  {
    name: "ชาวบ้านขายน้ำ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-011",
    rare: Rarity.C,
    mainEffect: "จุติ : นำ Modification Magic ที่มีชื่อ \"น้ำ\" จากใน Deck ฝ่ายเรา 1 ใบ ขึ้นมือ จากนั้นสับ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "แม่กบ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-012",
    rare: Rarity.C,
    mainEffect: "อัตโนมัติ ในช่วง End Phase ของเรา Avatar ใบนี้ POWER +1",
    cost: 3,
    gem: 1,
    power: 1,
    symbol: Symbol.Animal,
    color: Color.Red,
  },
  {
    name: "วันชัย พ่อบุญลือ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-013",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost ในการอัญเชิญ Avatar {Symbol เปรต} : Avatar ตัวนั้นจะไม่ถูกทำลายในเทิร์นนี้",
    cost: 5,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "กัญญา แม่บุญลือ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-014",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost ในการอัญเชิญ Avatar {Symbol เปรต} : จั่วการ์ด 1 ใบ หลังจากนั้น ทิ้งการ์ด 1 ใบ",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "พระอินทร์",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-015",
    rare: Rarity.SR,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : เลือก Avatar 1 ใบ POWER +3 จนจบเทิร์น",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "นนทก",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-016",
    rare: Rarity.C,
    mainEffect: "ต่อเนื่อง เมื่อ Avatar ตัวนี้อยู่บนสนาม POWER +1 ให้ Avatar {symbol เทพ} ทุกใบบนสนามฝ่ายเรา",
    cost: 1,
    gem: 2,
    power: 1,
    symbol: Symbol.Giant,
    color: Color.Red,
  },
  {
    name: "รัททาทุย นางพญา",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-017",
    rare: Rarity.C,
    mainEffect: "ในช่วง Draw Phase แรกของเรา เราสามารถนำการ์ดใบนี้จาก Deck ขึ้นมือแทนการจั่วได้ จากนั้นสับ Deck",
    cost: 2,
    gem: 2,
    power: 4,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "รัททาทุย พ่อพันธุ์",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-018",
    rare: Rarity.C,
    mainEffect:
      "จุติ  : ถ้าบน Avatar Zone ฝ่ายเรามี \"รัททาทุย นางพญา\" สามารถอัญเชิญ Avatar ที่มีชื่อ \"รัททาทุย\" \nจากใน Deck ลง Avatar Zone ฝ่ายเรากี่ใบก็ได้ โดย Cost รวมกันไม่เกิน 5 จากนั้นสับ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "รัททาทุย",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-019",
    rare: Rarity.C,
    mainEffect: "สามัคคี  การ์ดใบนี้ สามารถใส่ใน Deck จำนวนได้มากสุด 50 ใบ",
    cost: 1,
    gem: 1,
    power: 1,
    symbol: Symbol.Rat,
    color: Color.Blue,
    customLimit: 50,
  },
  {
    name: "แมลงปอเลื่อยยนต์",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-020",
    rare: Rarity.C,
    mainEffect: "จุติ :  ทำลาย Magic Card บนสนาม 1ใบ",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "ลูกแม่ศรีนวล",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-021",
    rare: Rarity.C,
    mainEffect: "คำสั่งเสีย : นำ LIFE Card ที่หงายอยู่ใบบนสุด กลับมาคว่ำ 1 ใบ",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: Symbol.Animal,
    color: Color.Blue,
  },
  {
    name: "พ่อบุญใหญ่",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-022",
    rare: Rarity.SR,
    mainEffect: "คำสั่งเสีย : นำ Avatar {symbol สัตว์} ที่มี Cost ไม่เกิน 4  1 ใบ จากนรกฝ่ายเรา กลับขึ้นมือ",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Blue,
  },
  {
    name: "จ่ามะนาว",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-023",
    rare: Rarity.SR,
    mainEffect: "โล่มนุษย์",
    cost: 3,
    gem: 2,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "แมลงปอแจ็ค",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-024",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : ทำลายการ์ด Land MAGIC 1 ใบบนสนาม หลังจากนั้นนำ Land MAGIC 1 ใบจาก Deck เรามาเล่นบนสนาม หลังจากนั้นสับ Deck",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "เอเลี่ยนแสงสีฟ้า",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-025",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) ทิ้งการ์ดบนมือ 1 ใบ เลือก Avatar บนสนามอีกฝ่าย 1 ตัว : ทอยเหรียญ 1 ครั้ง ออกหัว ทำลาย Avatar ตัวนั้น , ออกก้อย ทำลาย Avatar ตัวนี้",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: Symbol.Alien,
    color: Color.Blue,
  },
  {
    name: "ริกกี้ เพื่อนรัก",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-026",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำการ์ดชื่อ \"กุ่ย\" \"ฮอล\" หรือ \"นาย\" สูงสุด3ใบ จากนรก เข้า Deck หลังจากนั้นสับ Deck แล้วจั่วการ์ด 1 ใบ",
    cost: 3,
    gem: 2,
    power: 1,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "สุวรรณ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-027",
    rare: Rarity.SR,
    mainEffect: "จุติ : สอดแนม 5 ใบ  นำการ์ด \"พญายม\" หรือ \"นายนิรยบาล\" 1 ใบ จากที่ สอดแนม ขึ้นมือ นำการ์ดที่เหลือเรียงไว้ใต้ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "ทศกัณฑ์ยักษ์ที่---เมียพระอิศวร",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-028",
    rare: Rarity.SR,
    mainEffect: "จุติ : สามารถเลือก Avatar ใน Avatar Zone ฝ่ายตรงข้าม 1 ใบ เปลี่ยนการควบคุมมาบน Avatar Zone ฝ่ายเราในสภาพนอน",
    cost: 4,
    gem: 3,
    power: 5,
    symbol: Symbol.Alien,
    color: Color.Purple,
  },
  {
    name: "ศาลพระภูมิ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-029",
    rare: Rarity.SR,
    mainEffect:
      "จุติ : อัญเชิญ Avatar {symbol ผี} จากใน Deck 1 ใบ ลง Avatar Zone ฝ่ายเรา \nต่อเนื่อง  เมื่อมีการ์ด Avatar {symbol ผี}ใบอื่นบน Avatar Zone ฝ่ายเรา อีกฝ่ายจะไม่สามารถเลือก Avatar \"ศาลพระภูมิ\" เป็นเป้าหมายโจมตีได้",
    cost: 4,
    gem: 1,
    power: 2,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "นายนิรยบาล \"เต๋า\"",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-030",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ตกนรกด้วยผลของ ธรณีสูบ : ทั้งสองฝ่าย ธรณีสูบ 2ใบ",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "นีโม่",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-031",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ตกนรกด้วยผลของ ธรณีสูบ: นำการ์ดใบนี้กลับ Deck แล้วสับ",
    cost: 0,
    gem: 3,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "ยมทูต",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-032",
    rare: Rarity.C,
    mainEffect: "จุติ : สอดแนม 5 ใบ  นำการ์ด \"สิมพลีนรก\" 1 ใบ จากที่ สอดแนม ขึ้นมือ นำการ์ดที่เหลือเรียงไว้ใต้ Deck",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "สารวัตร ตำรวจสัมภเวสี",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-033",
    rare: Rarity.C,
    mainEffect: "จุติ : สามารถนำการ์ด \"ตำรวจสัมภเวสี\" 1 ใบ จากใน Deck ฝ่ายเราขึ้นมือ จากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "แรงงานทาสออฟฟิศ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-034",
    rare: Rarity.C,
    mainEffect: "ในช่วง End Phase นำ Avatar ตัวนี้จากสนาม ไปไว้ใต้ Deck",
    cost: 1,
    gem: 3,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "กัปตัน ไกร",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-035",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) ทิ้งการ์ดทั้งหมดบนมือของเรา เลือก Avatar 1 ใบบนสนามฝ่ายตรงข้าม : นำ Avatar ตัวนั้นกลับขึ้นมือ",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "นายนิรยบาล พ่อจีจ้า",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-036",
    rare: Rarity.C,
    mainEffect: "เมื่อ Avatar ตัวนี้ เป็นเป้าหมายโจมตีหรือสั่งโจมตี : ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 2 ใบ POWER +1 จนจบเทิร์น",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "เด็กหนวด โอเดนย่า",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-037",
    rare: Rarity.C,
    mainEffect: "",
    cost: 2,
    gem: 4,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "กัปตันโซเดียม",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-038",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "ตึก",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-039",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 6,
    gem: 4,
    power: 9,
    symbol: Symbol.Robot,
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "พี่โด 2.0",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-040",
    rare: Rarity.C,
    mainEffect: "",
    cost: 8,
    gem: 2,
    power: 8,
    symbol: Symbol.Robot,
    color: Color.Red
  },
  {
    name: "ลูกกบ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-041",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 1,
    power: 1,
    symbol: Symbol.Animal,
    color: Color.Red,
  },
  {
    name: "เทวดาตำรวจ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-042",
    rare: Rarity.C,
    mainEffect: "",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ช่างแอร์ดวงซวย",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-043",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "เทวดาแบงค์",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-044",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 1,
    gem: 0,
    power: 4,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ลูกค้าชาบู",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-045",
    rare: Rarity.R,
    mainEffect: "",
    cost: 2,
    gem: 4,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "เจ้าของร้านชาบู",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-046",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ครูวีรชัย",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-047",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 3,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "จ่าแดงเดือด",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-048",
    rare: Rarity.C,
    mainEffect: "",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ครูภาษาไทย",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-049",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "เด็กไม่ชอบแมลงสาบมากๆ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-050",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 0,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "รัททาทุย ผู้พิทักษ์ราชีนี",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-051",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 5,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "เฟนริล",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-052",
    rare: Rarity.C,
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 5,
    symbol: Symbol.Animal,
    color: Color.Purple,
  },
  {
    name: "จอมมังการ์ด",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-053",
    rare: Rarity.C,
    mainEffect: "",
    cost: 5,
    gem: 1,
    power: 6,
    symbol: Symbol.Animal,
    color: Color.Purple,
  },
  {
    name: "นายนิรยบาล ตัวใหญ่พิเศษ",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-054",
    rare: Rarity.C,
    mainEffect: "",
    cost: 9,
    gem: 4,
    power: 3,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "แบงค์ เทคนิคประทุมทู",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-055",
    rare: Rarity.C,
    mainEffect: "",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "นายนิรยบาล ปฎิรูป",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-056",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 4,
    power: 1,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "นายนิรยบาล ชาวนา",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-057",
    rare: Rarity.C,
    mainEffect: "",
    cost: 2,
    gem: 3,
    power: 3,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "นายนิรยบาล กล้าม",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-058",
    rare: Rarity.C,
    mainEffect: "",
    cost: 4,
    gem: 3,
    power: 4,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "กาลจักร",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-059",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: Symbol.Giant,
    color: Color.Green,
  },
  {
    name: "โลทัน",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-060",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 2,
    gem: 2,
    power: 3,
    symbol: Symbol.Giant,
    color: Color.Green,
  },
  {
    name: "มหิตัน",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-061",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 3,
    gem: 3,
    power: 3,
    symbol: Symbol.Giant,
    color: Color.Green,
  },
  {
    name: "พัทธกาล",
    type: CardType.Avatar,
    soi: 1,
    print: "ODY1-062",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: Symbol.Giant,
    color: Color.Green,
  },
  {
    name: "เอาแค่การ์ด !!!",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-063",
    rare: Rarity.C,
    mainEffect: "ทิ้งการ์ด \"โอเดนย่า\" หรือ \"ทาโกะ\" บนมือเรา 1 ใบ : เลือก Avatar 1 ใบบนสนาม ขึ้นมือ เจ้าของ",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "โอเดนย่า อร่อยมัก",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-064",
    rare: Rarity.C,
    mainEffect: "เมื่อ Avatar \"ทาโกะ\" ตกเป็นเป้าหมายการโจมตี : Avatar ใบนั้น POWER +2 จนจบเทิร์น",
    subtype: MagicSubtype.Normal,
    cost: 3,
    symbol: Symbol.Mage,
  },
  {
    name: "ถุงเกราะโอเดนย่า",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-065",
    rare: Rarity.SR,
    mainEffect: "ทำลายการ์ดใบนี้ในสภาพสวมใส่: Avatar ที่เคยสวมใส่การ์ดใบนี้ POWER +2 จนจบเทิร์นถัดไปของฝ่ายตรงข้าม",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ดาว O.D.Y 88",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-066",
    rare: Rarity.SR,
    mainEffect: "POWER +1 ให้ Avatar \"ทาโกะ\" บนสนามทุกใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Robot,
  },
  {
    name: "เมตตาระยะยาว",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-067",
    rare: Rarity.SR,
    mainEffect: "ทำลาย Avatar บนสนามอีกฝ่ายทุกใบ",
    subtype: MagicSubtype.Normal,
    cost: 0,
    symbol: Symbol.God,
    ex: "Only #1",
  },
  {
    name: "ความเจริญ",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-068",
    rare: Rarity.SR,
    mainEffect: "จั่วการ์ดจาก Deck 2 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ชายจากอนาคต",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-069",
    rare: Rarity.SR,
    mainEffect: "เมื่อมีการสั่งใช้ Magic Card : ยกเลิกความสามารถ Magic Card ใบนั้น",
    subtype: MagicSubtype.React,
    cost: 0,
    symbol: Symbol.Mage,
  },
  {
    name: "ริกกี้ นักปลอมแปลง",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-070",
    rare: Rarity.SR,
    mainEffect: "เมื่อ Avatar บนสนามของเราถูกทำลายจากการต่อสู้ สามารถใช้การ์ดใบนี้ได้ : เปลี่ยนการควบคุม Avatar ที่อยู่ในสภาพนอน จากบนสนามอีกฝ่ายมาบนสนามฝ่ายเรา แล้วนำการ์ดใบนี้ไปเป็นModification Magic ถ้าการ์ดใบนี้ถูกทำลาย ส่ง Avatar กลับขึ้นมือเจ้าของ",
    subtype: MagicSubtype.React,
    cost: 0,
    symbol: Symbol.Insect,
  },
  {
    name: "ตีแม่",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-071",
    rare: Rarity.C,
    mainEffect: "POWER +2 ให้กับ Avatar ที่สวมใส่การ์ดใบนี้ เมื่อการ์ดใบนี้ตกลงสู่นรก หงาย LIFE Card ใบบนสุดของเรา 1 ใบ",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Human,
  },
  {
    name: "ตีพ่อ",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-072",
    rare: Rarity.C,
    mainEffect: "ใน Battle Phase ถ้า Avatar ที่สวมใส่การ์ดใบนี้ทำลาย Avatar อีกฝ่ายสำเร็จ : สามารถกลับมาสภาพตื่นได้ 1 ครั้ง เมื่อการ์ดใบนี้ตกลงสู่นรก หงาย LIFE Card ใบบนสุดของเรา 1 ใบ",
    subtype: MagicSubtype.Modification,
    cost: 3,
    symbol: Symbol.Human,
  },
  {
    name: "หมอมาแล้วววว",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-073",
    rare: Rarity.C,
    mainEffect: "เมื่อ Avatar จะถูกทำลาย : Avatar ตัวนั้นจะไม่ถูกทำลาย",
    subtype: MagicSubtype.React,
    cost: 3,
    symbol: Symbol.Mage,
  },
  {
    name: "โรงบาล",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-074",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สามารถทิ้งการ์ดจากมือ 1 ใบ : เลือกการ์ด Avatar จากในนรก 1 ใบที่ Cost ไม่เกิน 3 ขึ้นมือได้    ในเทิร์นนี้การ์ดที่ขึ้นมือจากความสามารถ\"โรงบาล\"จะไม่สามารถอัญเชิญและไม่สามารถใช้ความสามารถได้ รวมถึงการ์ดชื่อเดียวกันกับที่ขึ้นมือทั้งหมด",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "น้ำแดง",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-075",
    rare: Rarity.SR,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ POWER +1",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ไม้เกาหลัง",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-076",
    rare: Rarity.SR,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ได้รับความสามรถ เตะไข่",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Rat,
  },
  {
    name: "หอกแหลมแทงทุกวัน ทุกวัน",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-077",
    rare: Rarity.SR,
    mainEffect:
      "POWER +1 ให้ Avatar {symbol นรก} ที่สวมใส่\nถ้าการ์ดใบนี้ถูกส่งลงนรกด้วยผลของ ธรณีสูบ : สามารถใช้งานการ์ดใบนี้จากนรกได้",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: Symbol.Hell,
  },
  {
    name: "เพื่อลูกค้า",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-078",
    rare: Rarity.C,
    mainEffect: "เซ่นไหว์ Avatar {symbol สัตว์} บนสนามเรา 1 ใบ : จั่วการ์ดจาก Deck 3 ใบ แต่เทิร์นนี้จะอัญเชิญได้แค่ Avatar {symbol สัตว์}",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage
  },
  {
    name: "น้ำชูกำลัง",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-079",
    rare: Rarity.C,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้จะกลับมาเป็นสภาพตื่น ตอน End Phase",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: Symbol.Mage
  },
  {
    name: "รั้วของชาติ",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-080",
    rare: Rarity.C,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ได้รับความสามารถ โล่มนุษย์",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "เขาไกรลาสเอียง",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-081",
    rare: Rarity.C,
    mainEffect: "เมื่อมีการประกาศโจมตี : ฝ่ายที่ประกาศโจมตี ธรณีสูบ 2 ใบ",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.God,
  },
  {
    name: "ทุ่งนาแดนนี้(ไม่มีความหมาย)",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-082",
    rare: Rarity.C,
    mainEffect: "Avatar เผ่าแมลง สัตว์ รัททาทุย และมนุษย์ POWER +1",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "มวยทะเลลลลลล",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-083",
    rare: Rarity.C,
    mainEffect: "ต่างฝ่ายต่างสั่ง Avatar โจมตีได้แค่ 1 ตัวต่อเทิร์น โดยที่การ์ดใบนี้จะอยู่บนสนามได้แค่ 4 เทิร์น",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Hermit,
  },
  {
    name: "เจ้ากล้าดียังไง",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-084",
    rare: Rarity.C,
    mainEffect: "เมื่อฝ่ายตรงข้ามประกาศโจมตี : เลือก Avatar ที่ประกาศโจมตีและส่งลงนรก",
    subtype: MagicSubtype.React,
    cost: 2,
    symbol: Symbol.God,
  },
  {
    name: "ประมาทร่วม",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-085",
    rare: Rarity.SR,
    mainEffect: "ทั้งสองฝ่ายธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 3 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ความกล้าหาญ",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-086",
    rare: Rarity.SR,
    mainEffect: "เลือก Avatar บนสนามเรา 1 ใบ POWER +4 และจะถูกทำลายในตอน End Phase",
    subtype: MagicSubtype.Normal,
    cost: 4,
    symbol: Symbol.Mage,
  },
  {
    name: "เคี้ยวเพื่อนเธอซะ",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-087",
    rare: Rarity.C,
    mainEffect: "เมื่อมี Avatar อัญเชิญลงมาบน Avatar Zone : เซ่นไหว้ (ทำลายจาก Avatar Zone ลงนรก) Avatar บน Avatar Zone เรากี่ใบก็ได้ อัญเชิญ Avatar จากบนมือเราตามค่า GEM ของ Avatar ที่ถูกเซ่นไหว้",
    subtype: MagicSubtype.React,
    cost: 3,
    symbol: Symbol.Animal,
  },
  {
    name: "ความยุติธรรมสำหรับนนทก",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-088",
    rare: Rarity.C,
    mainEffect: "ทิ้ง Avatar {symbol เทพ} จากบนมือ 1 ใบ : จั่วการ์ด 2 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "บำเพ็ญประโยชน์",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-089",
    rare: Rarity.C,
    mainEffect: "ส่ง Avatar ชื่อ \"กุ่ย\",\"ฮอล\" หรือ \"นาย\" 1 ใบ จากบนมือลงนรก : จั่วการ์ด 2 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "กระทะทองแดง",
    type: CardType.Magic,
    soi: 1,
    print: "ODY1-090",
    rare: Rarity.C,
    mainEffect: "ส่ง Avatar {symbol นรก} 1 ใบจากมือลงนรก : ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 2 ใบ แล้ว จั่วการ์ดจาก Deck 2 ใบ",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Hell,
  }
]);
