import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_PRMO: Card[] = createCards([
  {
    name: "รัททาทุย",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-001",
    rare: Rarity.C,
    mainEffect:
      "สามัคคี (เปลี่ยนการ์ดนี้เป็นสภาพนอนและนำ POWER การ์ดนี้ไปเพิ่มให้กับ Avatar ที่สั่งโจมตี) \n#การ์ดใบนี้ สามารถใส่ในเด็คจำนวนได้มากสุด 50 ใบ",
    cost: 1,
    gem: 1,
    power: 1,
    symbol: Symbol.Rat,
    color: Color.Blue,
    customLimit: 50,
  },
  {
    name: "นายนิรยบาล ปฎิรูป",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-002",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "อุบัติเหตุ!!!",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-003",
    rare: Rarity.SR,
    mainEffect: "เมื่อมี Avatar อัญเชิญลงมาบนสนาม : ทำลาย Avatar ตัวนั้น",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "น้ำชูกำลัง",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-004",
    rare: Rarity.C,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้จะกลับมาเป็นสภาพตื่น ตอน End Phase",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "ไม้เกาหลัง",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-005",
    rare: Rarity.C,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ได้รับความสามารถ เตะไข่ (Avatar ใบนี้สามารถโจมตีไปที่ LIFE Card ได้โดยตรง แม้ว่า Avatar Zone ของอีกฝ่ายจะมี Avatar อยู่ก็ตาม)",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Rat,
  },
  {
    name: "ลูกแม่ศรีนวล",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-006",
    rare: Rarity.SR,
    mainEffect: "คำสั่งเสีย (เมื่อAvatarใบนี้ถูกทำลาย) : นำ LIFE Card ที่หงายอยู่ใบบนสุด กลับมาคว่ำ 1 ใบ",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: Symbol.Animal,
    color: Color.Blue,
  },
  {
    name: "ตีพ่อ",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-007",
    rare: Rarity.C,
    mainEffect:
      "ใน Battle Phase ถ้า Avatar ที่สวมใส่การ์ดใบนี้ทำลาย Avatar อีกฝ่ายสำเร็จ : สามารถกลับมาสภาพตื่นได้ 1 ครั้ง \nเมื่อการ์ดใบนี้ตกลงสู่นรก เมื่อการ์ดใบนี้ตกลงสู่นรก หงาย LIFE Card ใบบนสุดฝ่ายเรา 1 ใบ",
    subtype: MagicSubtype.Modification,
    cost: 3,
    symbol: Symbol.Human,
  },
  {
    name: "ตีแม่",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-008",
    rare: Rarity.C,
    mainEffect:
      "POWER +2 ให้กับ Avatar ที่สวมใส่การ์ดใบนี้ \nเมื่อการ์ดใบนี้ตกลงสู่นรก หงาย LIFE Card ใบบนสุดฝ่ายเรา 1 ใบ",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Human,
  },
  {
    name: "พระอิศวร",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-009",
    rare: Rarity.SR,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : เลือก Avatar 1 ใบ POWER -4 จนจบเทิร์น",
    cost: 6,
    gem: 2,
    power: 5,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ช่วยโลกใบนี้ไว้",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-010",
    rare: Rarity.R,
    mainEffect: "หงาย LIFE ของเราทุกใบ : เงื่อนไขการแพ้เมื่อ Life Card ของเราโดนหงายทั้งหมด จะไม่ทำงานจนจบเทิร์น ในเทิร์นนี้ Avatar {symbol เปรต} ที่อัญเชิญในเทิร์นนี้จะได้รับความสามารถ ไม่รับผลจากความสามารถของการ์ดทุกประเภท , ได้รับความสามารถ เตะไข่ โดยที่ความสามารถ \"โล่มนุษย์\" จะไม่สามารถใช้ได้",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Pret,
  },
  {
    name: "มีมมิจัง ไอดอลหน้าใหม่",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-011",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : เลือก Avatar ที่ติดชื่อ \"โอตะ\" จาก Deck 1 ใบ มาสวมใส่ให้ Avatar ใบนี้ จากนั้นสับ Deck",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "แบงค์ ผู้รู้ความจริง",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-012",
    rare: Rarity.SR,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สอดแนม (แสดงการ์ดใบบนสุดของ Deck ) 3 ใบของเรา เรียงลำดับตามใจชอบ",
    cost: 2,
    gem: 1,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "สตีฟ Tank Ranger",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-013",
    rare: Rarity.C,
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ นำ Avatar ใบนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา \nAvatar \"รถถัง\" ที่สวมใส่การ์ดใบนี้ POWER +2 \nใน Battle Phase: Avatar ชื่อ \"รถถัง\" ที่สวมใส่การ์ดใบนี้จะต้องโจมตี ถ้าโจมตีได้",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "ฉุบสั่งตาย",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-014",
    rare: Rarity.C,
    mainEffect: "เป่ายิ้งฉุบกับฝ่ายตรงข้าม : ผู้ชนะ เลือกทำลาย Avatar บนสนาม 1 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "อรุณีย์ ข้าวมันไก่เมียจ่า",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-015",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "เอเลี่ยนแสงสีฟ้า",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-016",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) ทิ้งการ์ดบนมือ 1 ใบ เลือก Avatar บนสนามอีกฝ่าย 1 ใบ : ทอยเหรียญ 1 ครั้ง ออกหัว ทำลาย Avatar ตัวนั้น , ออกก้อย ทำลาย Avatar ใบนี้",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: Symbol.Alien,
    color: Color.Blue,
  },
  {
    name: "เสามงคล",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-017",
    rare: Rarity.C,
    mainEffect:
      "ต่อเนื่อง การ์ดใบนี้โจมตีไม่ได้ \nต่อเนื่อง ในช่วง Draw Phase หลังจากการจั่วการ์ดปกติใน Draw Phase : จั่วการ์ด 1 ใบ",
    cost: 5,
    gem: 2,
    power: 3,
    symbol: Symbol.Tree,
    color: Color.Green,
  },
  {
    name: "ไอ นีด เมดิก",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-018",
    rare: Rarity.SR,
    mainEffect: "สุ่มคว่ำ LIFE Card ของฝ่ายเราได้ 1 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 4,
    symbol: Symbol.Human,
  },
  {
    name: "ความเจริญ",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-019",
    rare: Rarity.C,
    mainEffect: "จั่วการ์ดจาก Deck เรา 2 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "พญายม",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-020",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : เลือก Avatar \"นายนิรยบาล\" ในนรกเรา 1 ใบ อัญเชิญลง Avatar Zone ฝ่ายเรา",
    cost: 5,
    gem: 1,
    power: 5,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "ใบดำใบแดง",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-021",
    rare: Rarity.C,
    mainEffect: "สอดแนม 1 ใบ : ถ้าเป็น Avatar {Symbol : คน} Cost ไม่เกิน 3 ให้นำลงบน Avatar Zone ฝ่ายเรา แต่ถ้าไม่ใช่ให้ใส่ไว้ใต้ Deck",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Soldier,
  },
  {
    name: "พระอินทร์",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-022",
    rare: Rarity.SR,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : เลือก Avatar 1 ใบ POWER +3 จนจบเทิร์น",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "พี่โด 2.0",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-023",
    rare: Rarity.C,
    mainEffect: "",
    cost: 8,
    gem: 2,
    power: 8,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "แบมบูจัง ไอดอลสองขั้ว",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-024",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทำลายการ์ด \"โอตะ\" ที่สวมใส่อยู่ให้กับการ์ด Avatar \"ไอดอล\" บน Avatar Zone ฝ่ายเรา 1 ใบ  : ทำลายการ์ดบนสนาม 1 ใบ",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "บัลเดอร์ เทพแสง แห่งแอสการ์ด",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-025",
    rare: Rarity.SR,
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง ถ้า Avatar ตัวนี้จะถูกทำลาย : ธณีสูบ 9 ใบ แทนการทำลายได้",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: Symbol.God,
    color: Color.Purple,
  },
  {
    name: "ทหารอาณาจักรของแพง",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-026",
    rare: Rarity.C,
    mainEffect:
      "ต่อเนื่อง Avatar ทุกตัวบนสนามอีกฝ่าย Cost -1\nต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี Avatar \"ราชาอาณาจักรของแพง  พระเจ้านิโคไล\" POWER ของการ์ดใบนี้จะเป็น 2",
    cost: 0,
    gem: 2,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "พระนารายณ์",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-027",
    rare: Rarity.C,
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : POWER +2 จนจบเทิร์น",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ไม่เจ้ายังไม่พร้อม",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-028",
    rare: Rarity.SR,
    mainEffect: "เมื่อมี Avatar อัญเชิญลงมาบน Avatar Zone : เปลี่ยน Avatar ใบนั้นเป็นสภาพนอน",
    subtype: MagicSubtype.React,
    cost: 2,
    symbol: Symbol.Hermit,
  },
  {
    name: "แบ่งแยกดินแดน",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-029",
    rare: Rarity.C,
    mainEffect: "เมื่อมีการ์ดใบนี้บนLand Magic Zone : ทั้ง2ฝ่ายวาง Land Magic ได้โดยไม่ทำลาย Land Magic ของอีกฝ่าย",
    subtype: MagicSubtype.Land,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "บึงทมิฬ  People - CEO คุณจิระ",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-030",
    rare: Rarity.C,
    mainEffect: "อัติโนมัติ เมื่อการ์ดใบนี้สั่งโจมตีหรือตกเป็นเป้าหมายการโจมตี : POWER ของการ์ดใบนี้จะเพิ่มขึ้นตาม Avatar ที่อยู่ในสภาพนอนบนสนามทั้ง 2 ฝ่าย ใบละ 1 จนจบเทิร์น",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: Symbol.Fish,
    color: Color.Blue,
  },
  {
    name: "ปราสาทแดรก",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-031",
    rare: Rarity.C,
    mainEffect:
      "Avatar ชื่อ แดรกคูลา บน Avatar Zone POWER +1 \nเทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดจากบนมือเรา 1 ใบ และ เลือก แดรกคูลา 1 ใบจากในนรกฝ่ายเรา 1 ใบ : อัญเชิญการ์ดใบนั้นมาบน Avatar Zone ฝ่ายเรา",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Ghost,
  },
  {
    name: "นางอัปสร",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-032",
    rare: Rarity.SR,
    mainEffect:
      "อัตโนมัติ เมื่อการ์ดใบนี้สั่งโจมตี : ฝ่ายตรงข้ามไม่สามารถสั่งใช้งาน React Magic จนจบการต่อสู้ \n#การ์ดใบนี้นับเป็นชื่อ \"พระนารายณ์",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "เทอราโนดอน จากต่างแดน",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-033",
    rare: Rarity.C,
    mainEffect: "ต่อเนื่อง ความสามารถ สอดแนม ของ Avatar {symbol กะปอม} ฝ่ายเราทุกใบ จะสอดแนมเพิ่มอีก 1 ใบ",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Lizard,
    color: Color.Blue,
    gemColor: "ฟ้า",
  },
  {
    name: "หมานมเย็น",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-034",
    rare: Rarity.C,
    mainEffect: "จุติ : อัญเชิญ Avatar  \"หมา\" หรือ \"แมว\"  ที่มี {symbol สัตว์} 1 ใบ ที่ Cost ไม่เกิน 2 จาก Deck ลง Avatar Zone ฝ่ายเรา จากนั้น สับ Deck",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Blue,
  },
  {
    name: "หมอมาแล้วววว",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-035",
    rare: Rarity.SR,
    mainEffect: "เมื่อ Avatar จะถูกทำลาย : Avatar ใบนั้นจะไม่ถูกทำลาย",
    subtype: MagicSubtype.React,
    cost: 3,
    symbol: Symbol.Mage,
  },
  {
    name: "น้องสาม ผู้รู้ความจริง",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-036",
    rare: Rarity.C,
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้โจมตี : สอดแนม 2 ใบ เพิ่ม POWER ของการ์ดใบนี้เท่ากับ POWER ของ Avatar \"ผู้รู้ความจริง\" ทั้งหมดที่สอดแนมเจอ จากนั้นสามารถนำ การ์ด Avatar \"ผู้รู้ความจริง\" 1 ใบ จากที่สอดแนมขึ้นมือ และนำการ์ดที่เหลือ วางไว้บนหรือล่างสุดของ Deck",
    cost: 3,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "โทมาโทจัง ไอดอลเด็กน้อย",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-037",
    rare: Rarity.C,
    mainEffect:
      "ต่อเนื่อง เมื่อ Avatar ตัวนี้อยู่บน Avatar Zone POWER + 2 ให้ Avatar \"ไอดอล\" ใบอื่นใน Avatar Zone ฝ่ายเรา ที่สวมใส่การ์ด \"โอตะ\" อยู่\nต่อเนื่อง ถ้า Avatar ใบนี้ สวมใส่การ์ด \"โอตะ\" อยู่ และมี Avatar \"ไอดอล\" ชื่ออื่นในสนามฝ่ายเรา Avatar ใบนี้จะไม่สามารถถูกเลือกเป็นเป้าหมายการโจมตีได้",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "รถถัง \"Tank Ranger\"",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-038",
    rare: Rarity.SR,
    mainEffect:
      "ต่อเนื่อง ถ้าไม่มี Avatar สวมใส่ Avatar ใบนี้ จะไม่สามารถโจมตีได้ \nและไม่สามารถใช้ Avatar ชื่อซ้ำกันในการสวมใส่การ์ดใบนี้",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: Symbol.Robot,
    color: Color.Green,
  },
  {
    name: "หมู่บ้านพอดี",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-039",
    rare: Rarity.C,
    mainEffect: "การ์ดทุกใบ จะต้องทิ้ง GEM ให้พอดีกับ Cost",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "เมียพระอิศวร",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-040",
    rare: Rarity.SR,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : จั่วการ์ด 3 ใบ",
    cost: 3,
    gem: 4,
    power: 5,
    symbol: Symbol.God,
    color: Color.Red,
    ex: "Only #1",
  },
  {
    name: "ขวานเงิน",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-041",
    rare: Rarity.SR,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ POWER +2 และ ความสามารถของ Avatar ที่สวมใส่การ์ดใบนี้ที่มีอยู่ทั้งหมดจะไร้ผล",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Human,
  },
  {
    name: "ครูภาษาไทย",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-042",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ไดโนกาฬสินธุ์ - ภูเวียงสิรินเน",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-043",
    rare: Rarity.R,
    mainEffect: "จุติ : เลือกหยิบการ์ด Avatar {symbol กะปอม} Cost 3 หรือต่ำกว่า สูงสุด 4 ใบจากนรกของฝ่ายเรากลับเข้า Deck แล้วสับ หลังจากนั้นจั่วการ์ด 1 ใบ และ POWER ของการ์ด ใบนี้จะเพิ่มเท่ากับจำนวนการ์ดที่นำเข้า Deck ใบละ 1 จนจบเทิร์น",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: Symbol.Lizard,
    color: Color.Blue,
  },
  {
    name: "ร้อนมากก็เปิดหน้าต่างสิว๊ากกกก",
    type: CardType.Magic,
    soi: 2,
    print: "PRMO-044",
    rare: Rarity.C,
    mainEffect: "เลือก Avatar อีกฝ่าย 1 ใบ : นำการ์ดใบนั้นขึ้นมือ",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "ทุ่งนาแดนนี้(ไม่มีความหมาย)",
    type: CardType.Magic,
    soi: 2,
    print: "PRMO-045",
    rare: Rarity.R,
    mainEffect: "Avatar เผ่าแมลง สัตว์ รัททาทุย และมนุษย์ POWER +1",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Tree,
  },
  {
    name: "นายนิรยบาล กล้าม",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-046",
    rare: Rarity.C,
    mainEffect: "",
    cost: 4,
    gem: 3,
    power: 4,
    symbol: Symbol.Hell,
    color: Color.Purple,
  },
  {
    name: "บรุนฮิลด์  เทพธิดาแห่งวัลฮัลลา",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-047",
    rare: Rarity.R,
    mainEffect: "ถ้าการ์ดใบนี้ถูก ธรณีสูบ ด้วยการ์ด Avatar {symbol เทพ} สีม่วง หรือ Magic card : สามารถอัญเชิญการ์ดใบนี้จากนรกได้",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Purple,
  },
  {
    name: "แมว-น้ำมะลิ",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-048",
    rare: Rarity.C,
    mainEffect: "จุติ : สอดแนม 3 ใบ เลือก การ์ด Avatar \"หมา\" หรือ \"แมว\" ที่เป็น Symbol สัตว์ 1 ใบ จากที่ สอดแนม และนำขึ้นมือ ถ้าการ์ดที่เลือกคือ หมานมเย็น อัญเชิญ จุติ ลงบน Avatar Zone ฝ่ายเราแทนการนำขึ้นมือ จากนั้นนำการ์ดที่เหลือกลับ Deck แล้วสับ",
    cost: 2,
    gem: 1,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Blue,
  },
  {
    name: "คุณเชิดชัย Super Air",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-049",
    rare: Rarity.C,
    mainEffect: "จุติ : สอดแนม 5 ใบ เลือกการ์ด เครื่องบิน Super Air หรือ รหัสดำ จากที่ สอดแนม 1 ใบ และ/หรือ เลือกการ์ด Avatar \"Super Air\" ที่เป็น Symbol คน จากที่สอดแนม 1 ใบ นำขึ้นมือ จากนั้นนำการ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck",
    cost: 2,
    gem: 1,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "โรงบาล",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-050",
    rare: Rarity.R,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดจากมือ 1 ใบ : เลือกการ์ด Avatar จากในนรก 1 ใบที่ Cost ไม่เกิน 3 ขึ้นมือได้ ในเทิร์นนี้การ์ดที่ขึ้นมือจากความสามารถ\"โรงบาล\"จะไม่สามารถอัญเชิญและไม่สามารถใช้ความสามารถได้ รวมถึงการ์ดชื่อเดียวกันกับที่ขึ้นมือทั้งหมด",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "บึงทมิฬ",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-051",
    rare: Rarity.SR,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เลือก Avatar 1 ใบ ใน Avatar Zone ฝ่ายเรา เปลี่ยนสภาพ Avatar ใบนั้นเป็นสภาพนอน : จั่วการ์ด 1 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Fish,
  },
  {
    name: "แม่นาค พระประแดง",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-052",
    rare: Rarity.SR,
    mainEffect: "เมื่อการ์ดใบนี้ถูกอัญเชิญ เลือกการ์ดในนรกของฝ่ายตรงข้าม 1 ใบ : นำการ์ดใบนั้นกลับเข้าใต้ Deck ฝ่ายตรงข้าม ถ้าทำสำเร็จ เลือก Avatar 1ใบ ของอีกฝ่าย POWER - 2",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "เด็กไม่ชอบแมลงสาบ",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-053",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "หมาแพนดี้",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-054",
    rare: Rarity.C,
    mainEffect:
      "โล่มนุษย์ สามัคคี \nต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้ อยู่ในสภาพนอน POWER ของ Avatar ใบนี้จะเพิ่มขึ้นเท่ากับ Avatar \"\"หมา\"\" และ \"\"แมว\"\" ที่เป็น Symbol สัตว์ ใบอื่น บน Avatar Zone ฝ่ายเรา ใบละ 1",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.Animal,
    color: Color.Red,
  },
  {
    name: "รัททาทุย ผู้พิทักษ์ราชินี",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-055",
    rare: Rarity.SR,
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 5,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "ชายจากอนาคต",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-056",
    rare: Rarity.R,
    mainEffect: "เมื่อมีการใช้ Magic Card : ยกเลิกการใช้ Magic Card ใบนั้น",
    subtype: MagicSubtype.React,
    cost: 0,
    symbol: Symbol.Mage,
  },
  {
    name: "อีช่า - สาวน้อยคนเก่ง",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-0562",
    rare: Rarity.C,
    mainEffect: "จุติ : เซ่นไหว้ Avatar ใบอื่นใน Avatar Zone 1 ใบ : เลือก Avatar {symbol คน} , {symbol เทพ} , {symbol นรก} บน Avatar Zone ของฝ่ายตรงข้าม 1 ใบ เปลี่ยนการควบคุมมาบน Avatar Zone ฝ่ายเรา",
    cost: 3,
    gem: 2,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "แมวมัทฉะ",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-057",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 1,
    power: 3,
    symbol: Symbol.Animal,
    color: Color.Green,
  },
  {
    name: "บึงทมิฬ  People - คุณดีไมส์",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-058",
    rare: Rarity.SR,
    mainEffect:
      "สามารถสั่งใช้งานความสามารถได้เมื่อมี บึงทมิฬ อยู่บน Land Magic Zone \nสั่งใช้ เมื่อ Avatar ใบนี้ทำลาย Avatar บน Avatar Zone ของฝ่ายตรงข้ามสำเร็จ สามารถทิ้งการ์ดบนมือ 1 ใบ Avatar ตัวนี้จะกลับมาเป็นสภาพ ตื่น",
    cost: 6,
    gem: 2,
    power: 4,
    symbol: Symbol.Fish,
    color: Color.Blue,
  },
  {
    name: "บีมมมมมมมมมม",
    type: CardType.Magic,
    soi: 2,
    print: "PRMO-059",
    rare: Rarity.C,
    mainEffect: "ทิ้งการ์ดบนมือ 1 ใบ : ทำลาย Avatar บนสนามฝ่ายตรงข้าม 1 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.God,
  },
  {
    name: "มีมมิ ผู้ร่วงหล่น",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-060",
    rare: Rarity.C,
    mainEffect: "จุติ : ถ้า Avatar Zone ฝ่ายเรา มี แดรกคูลา นำ Land Magic ปราสาทแดรก 1 ใบ จาก Deck เรา ขึ้นมือ จากนั้น สับ Deck",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Ghost,
    color: Color.Purple,
    gemColor: "ม่วง",
  },
  {
    name: "อามัส มนุษย์ดาว R18",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-061",
    rare: Rarity.SR,
    mainEffect: "ต่อเนื่อง POWER ของ Avatar ใบนี้ จะเพิ่มขึ้นตามจำนวน Avatar  \"ข้ารับใช้ของ มนุษย์ดาว R18\" ในสนามฝ่ายเรา ใบละ 1",
    cost: 3,
    gem: 3,
    power: 0,
    symbol: Symbol.Alien,
    color: Color.Blue,
  },
  {
    name: "สหายหุ่นผู้กล้า โฟเบีย",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-062",
    rare: Rarity.C,
    mainEffect:
      "จุติ นำ \"โดรนสอดแนมผู้กล้า : เก๊าท์\" , \"ยานเกราะผู้กล้า : ไดบาเรีย\" และ \"อากาศยานผู้กล้า : แอร์ซิด รีฟลักซ์\" \nอย่างละ 1 ใบ จาก นรกเรา กลับเข้า Deck : อัญเชิญ  \"ไมเกรน\" ที่ Cost ไม่เกิน 5 จากใน Deck เรา 1 ใบ ลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck และนำการ์ดใบนี้ไปสวมใส่ให้ Avatar ที่ถูกอัญเชิญมาด้วยความสามารถนี้\nAvatar ที่สวมใส่การ์ดใบนี้ POWER +1",
    cost: 3,
    gem: 2,
    power: 0,
    symbol: Symbol.Foreigner,
    color: Color.Red,
  },
  {
    name: "นางลักษมี",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-063",
    rare: Rarity.C,
    mainEffect:
      "การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {symbol เทพ} เท่านั้น \nเมื่อการ์ดใบนี้ถูกใช้เป็น Cost เพื่ออัญเชิญ Avatar \"พระนารายณ์\" : POWER + 3 ให้กับ Avatar ที่อัญเชิญ จนจบเทิร์น",
    cost: 1,
    gem: 4,
    power: 1,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ทัตดนัยซัง โปรดิวเซอร์มือทอง",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-064",
    rare: Rarity.SR,
    mainEffect:
      "โล่มนุษย์\nพอดี (จะได้รับความสามารถดังต่อไปนี้เมื่อ Avatar ใบนี้ถูกอัญเชิญมาด้วยการทิ้ง Gem พอดีกับ Cost เท่านั้น)\n  - จุติ : เลือก Avatar ของฝ่ายตรงข้าม 1 ใบ เปลี่ยน ชื่อ ของ Avatar ใบนั้นเป็น \"โอตะ\" และ นำมาสวมใส่ให้ Avatar \"ไอดอล\" บน Avatar Zone ของเรา และถ้าบน Avatar Zone ฝ่ายเรา มี มยุราซัง ไอดอลยุค 80 สามารถนำ Avatar \" ไอดอล \" 1 ใบจากใน Deck เรา ขึ้นมือ จากนั้นสับ Deck",
    cost: 6,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Purple,
    ex: "Only #1",
  },
  {
    name: "กุ่ย",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-065",
    rare: Rarity.SR,
    mainEffect:
      "สามัคคี (เปลี่ยนการ์ดนี้เป็นสภาพนอนและนำ POWER การ์ดนี้ไปเพิ่มให้กับ Avatar ที่สั่งโจมตี)\nจุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"ฮอล\" 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "ฮอล",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-066",
    rare: Rarity.SR,
    mainEffect:
      "สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)\nจุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"นาย\" 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "นาย",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-067",
    rare: Rarity.SR,
    mainEffect:
      "สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)\nจุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"กุ่ย\" 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "เจ้ากล้าดียังไง",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-068",
    rare: Rarity.SR,
    mainEffect: "เมื่อฝ่ายตรงข้ามประกาศโจมตี : ส่ง Avatar ที่ประกาศโจมตีลงนรก",
    subtype: MagicSubtype.React,
    cost: 2,
    symbol: Symbol.God,
  },
  {
    name: "เอาไปอยู่ด้วย",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-069",
    rare: Rarity.C,
    mainEffect: "ถ้า Avatar {Symbol ผี} บนสนามฝ่ายเราถูกทำลายโดยการ์ดฝ่ายตรงข้าม : ทำลาย Avatar บน Avatar Zone ของอีกฝ่าย 1 ใบ",
    subtype: MagicSubtype.React,
    cost: 2,
    symbol: Symbol.Ghost,
  },
  {
    name: "จอมเวทย์ดำ",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-070",
    rare: Rarity.C,
    mainEffect: "",
    cost: 3,
    gem: 1,
    power: 4,
    symbol: Symbol.Human,
    color: Color.Purple,
  },
  {
    name: "เฟรย่า แม่ทุกสถาบันแอสการ์ด",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-071",
    rare: Rarity.SR,
    mainEffect:
      "พอดี (จะได้รับความสามารถดังต่อไปนี้เมื่อ Avatar ใบนี้ถูกอัญเชิญมาด้วยการทิ้ง Gem พอดีกับ Cost เท่านั้น)\n   จุติ : นำ Avatar {Symbol เทพ} สีม่วง 3 ใบ จากในนรกเรากลับเข้า Deck เราแล้วสับ จากนั้น จั่วการ์ด 1 ใบ",
    cost: 4,
    gem: 3,
    power: 3,
    symbol: Symbol.God,
    color: Color.Purple,
    gemColor: "ม่วง",
  },
  {
    name: "จอย มนุษย์ดาว R18",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-072",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ : เลือก Avatar \"ข้ารับใช้ของ มนุษย์ดาว R18\" 1 ใบ ใน Magic Zone ฝ่ายเรา อัญเชิญ Avatar ใบนั้น ลง Avatar Zone ฝ่ายเรา ในช่วง End Phase นำ Avatar ใบนั้น กลับมาไว้ที่ Magic Zone ฝ่ายเรา",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: Symbol.Alien,
    color: Color.Blue,
  },
  {
    name: "จาบับวา",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-073",
    rare: Rarity.C,
    mainEffect: "คำสั่งเสีย : สอดแนม 5 ใบ เลือก การ์ด Avatar {symbol คน} 1 ใบ จากที่ สอดแนม และนำขึ้นมือ จากนั้นนำการ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck",
    cost: 4,
    gem: 0,
    power: 4,
    symbol: Symbol.Foreigner,
    color: Color.Purple,
  },
  {
    name: "หุ่นนักรบผู้กล้า : โปรโตไมเกรน",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-074",
    rare: Rarity.SR,
    mainEffect: "สั่งใช้ เมื่อ Avatar ใบนี้ โจมตีและทำลาย Avatar ฝ่ายตรงข้ามสำเร็จจากการต่อสู้ : ส่ง Avatar ใบนี้ลงนรก และ อัญเชิญ จุติ หุ่นนักรบผู้กล้า : ไมเกรน จาก Deck เรา จากนั้นสับ Deck ถ้า Avatar ใบนี้มีการ์ดสวมใส่อยู่ ให้นำการ์ดที่สวมใส่อยู่ทั้งหมด ไปสวมใส่ให้ Avatar ที่อัญเชิญมาด้วยความสามารถนี้แทน",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: Symbol.Robot,
    color: Color.Red,
    gemColor: "แดง",
  },
  {
    name: "แมลงปอแจ็ค",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-075",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : ทำลายการ์ด Land Magic 1 ใบบน Land Magic Zone หลังจากนั้นนำ Land Magic 1 ใบจาก Deck เรามาเล่นบน Land Magic Zone หลังจากนั้นสับ Deck",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: Symbol.Insect,
    color: Color.Blue,
  },
  {
    name: "ชาช่าจัง ไอดอลคนเก่ง",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-076",
    rare: Rarity.C,
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ไม่สามารถโจมตีได้ และ สามารถสวมใส่การ์ดได้เฉพาะการ์ด \"โอตะ\"\nเทิร์นละครั้ง สั่งใช้ ทำลาย การ์ด \"โอตะ\" ที่สวมใส่อยู่ให้กับ Avatar \"ไอดอล\" บน Avatar Zone ฝ่ายเรา 1 ใบ : ในเทิร์นนี้ Avatar ใบนี้จะสามารถโจมตีได้",
    cost: 4,
    gem: 2,
    power: 6,
    symbol: Symbol.Human,
    color: Color.Blue,
  },
  {
    name: "จ่ายุทธ Tank Ranger",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-077",
    rare: Rarity.SR,
    mainEffect:
      "จุติ ถ้ามี Avatar \"รถถัง\" บนสนามฝ่ายเรา : ทำลาย Avatar {symbol ต่างชาติ} 1 ใบ\nเทิร์นละครั้ง สั่งใช้ : นำ Avatar ใบนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา \nเมื่อ Avatar \"รถถัง\" ที่สวมใส่ การ์ดใบนี้ ต่อสู้กับ Avatar {symbol ต่างชาติ} : นำ Avatar ที่ต่อสู้กับรถถังที่สวมใส่การ์ดนี้เข้าใต้ Deck",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "หุ่นนักรบผู้กล้า : ไมเกรน",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-078",
    rare: Rarity.SR,
    mainEffect:
      "จุติ : สอดแนม 5 ใบ เลือกการ์ด \"อาวุธหุ่นนักรบผู้กล้า\" 1 ใบจากที่สอดแนม  นำขึ้นมือ การ์ดที่เหลือเรียงและนำไว้ใต้ Deck\nอัตโนมัติ เทิร์นละครั้ง เมื่อมีการใช้ Modification Magic \"อาวุธหุ่นนักรบผู้กล้า\" : จั่วการ์ด 1 ใบ",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: Symbol.Robot,
    color: Color.Red,
  },
  {
    name: "ศาลพระภูมิ",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-079",
    rare: Rarity.SR,
    mainEffect:
      "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : อัญเชิญ Avatar {symbol ผี} จากใน Deck 1 ใบ ลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck\nต่อเนื่อง ตราบเท่าที่มีการ์ด Avatar {symbol ผี} ใบอื่นบน Avatar Zone ฝ่ายเรา อีกฝ่ายจะไม่สามารถเลือก Avatar \"ศาลพระภูมิ\" เป็นเป้าหมายการโจมตีได้",
    cost: 4,
    gem: 1,
    power: 2,
    symbol: Symbol.Ghost,
    color: Color.Purple,
  },
  {
    name: "เลอติ๊ก เด็กไม่ชอบแดรคคูลา",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-083",
    rare: Rarity.R,
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ ทำลาย Avatar ฝ่ายตรงข้าม จากการต่อสู้ : Avatar ที่ถูก การ์ดใบนี้ทำลาย จะถูกส่งกลับเข้า Deck แทนการ ส่งลงนรก",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: Symbol.Foreigner,
    color: Color.Purple,
  },
  {
    name: "หมาชาไทย",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-084",
    rare: Rarity.SR,
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : นำ Avatar {symbol สัตว์} 1 ใบ ใน Avatar Zone ฝ่ายเรา ขึ้นมือ : Avatar ใบนี้ POWER +2",
    cost: 2,
    gem: 3,
    power: 0,
    symbol: Symbol.Animal,
    color: Color.Purple,
  },
  {
    name: "เบดิเวียร์ อัศวินโต๊ะกลมแห่งความภักดี",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-085",
    rare: Rarity.C,
    mainEffect: "จุติ : นำการ์ด Magic \"ดาบศักดิ์สิทธิ์\" 1 ใบ จาก Deck เรา ส่งลงนรกเราจากนั้น สับ Deck และสามารถนำ Avatar \"อัศวินโต๊ะกลม\" 1 ใบ จากนรกเรา วางไว้บนสุดของ Deck เรา จากนั้น Avatar ใบนี้ POWER +1 จนจบเทิร์น",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: Symbol.Foreigner,
    color: Color.Red,
  },
  {
    name: "ตุ๊กตารัททาทุย",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-086",
    rare: Rarity.R,
    mainEffect:
      "เมื่อการ์ดใบนี้ถูกทิ้งเป็นค่า Cost ให้กับ Avatar \"รัททาทุย\" : อัญเชิญ Avatar รัททาทุย ที่มี Cost 1 GEM 1 POWER 1 1ใบ จากใน Deck ลงบน Avatar Zone ฝ่ายเรา\n\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {symbol รัททาทุย} เท่านั้น",
    cost: 1,
    gem: 3,
    power: 0,
    symbol: Symbol.Rat,
    color: Color.Blue,
  },
  {
    name: "ไอ้นัท - คนใจเด็ด",
    type: CardType.Avatar,
    soi: 1,
    print: "PRMO-087",
    rare: Rarity.R,
    mainEffect: "ต่อเนื่อง Avatar ใบนี้จะไม่ถูกเปลี่ยนการควบคุม ยกเว้นจากความสามารถของ อีช่า - สาวน้อยคนเก่ง",
    cost: 1,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Red,
  },
  {
    name: "รถถัง A003",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-088",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: Symbol.Robot,
    color: Color.Green,
  },
  {
    name: "พลทหารหิมะ",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-089",
    rare: Rarity.C,
    mainEffect:
      "สามารถใส่การ์ดใบนี้ใน Deck ได้มากสุด 12 ใบ",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Blue,
    customLimit: 12,
  },
  {
    name: "คาถา ปลดอาวุสสิวะ",
    type: CardType.Magic,
    soi: 2,
    print: "PRMO-090",
    rare: Rarity.SR,
    mainEffect:
      "สามารถใช้ได้เมื่อมี Avatar \"จอมเวทย์\" อยู่บน Avatar Zone ฝ่ายเรา เท่านั้น เลือก Avatar ของฝ่ายตรงข้าม 1 ใบ : Avatar ใบที่เลือก POWER -3 ถ้า Avatar ใบนั้น POWER เหลือ 0 ทำลาย Avatar ใบนั้น",
    subtype: MagicSubtype.Normal,
    cost: 3,
    symbol: Symbol.Mage,
  },
  {
    name: "กวนอู ขุนพลภักดีแห่งจ๊กก๊ก",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-091",
    rare: Rarity.SR,
    mainEffect:
      "ต่อเนื่อง : Avatar ใบนี้ไม่สามารถเปลี่ยนการควบคุมได้ \n ต่อเนื่อง : ผู้เล่นฝ่ายตรงข้ามไม่สามารถเลือกเป้าหมายของความสามารถการ์ดไปที่ Avatar \"ขุนพล\" ที่เป็น {symbol ต่างชาติ} ฝ่ายเราได้ ยกเว้น \"กวนอู ขุนพลภักดีแห่งจ๊กก๊ก\" เท่านั้น",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.Foreigner,
    color: Color.Green,
  },
  {
    name: "ขวาน 7 สี",
    type: CardType.Magic,
    soi: 2,
    print: "PRMO-095",
    rare: Rarity.SR,
    mainEffect:
      "ความสามารถของการ์ดใบนี้จะทำงานตามสีของ Avatar ที่สวมใส่การ์ดใบนี้\nสีแดง เมื่อ Avatar ที่สวมใส่การ์ดนี้ โจมตี : POWER +2 จนจบการต่อสู้\nสีฟ้า เมื่อ Avatar ที่สวมใส่การ์ดนี้ โจมตี : จั่วการ์ด 1 ใบ\nสีม่วง เมื่อ Avatar ที่สวมใส่การ์ดนี้ โจมตี : ธรณีสูบ 1 ใบ POWER +1 จนจบเทิร์น\nสีเขียว Avatar ใบนี้ได้รับ ลูกฮึด",
    subtype: MagicSubtype.Modification,
    cost: 2,
    symbol: Symbol.Mage,
  },
  {
    name: "ลิโป้ ขุนพลเทพสงคราม",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-096",
    rare: Rarity.UR,
    mainEffect:
      "ต่อเนื่อง ในช่วง Battle Phase Avatar ฝ่ายตรงข้ามทุกใบได้รับ โล่มนุษย์\n\nอัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : ฝ่ายตรงข้ามจะต้องใช้ความสามารถ โล่มนุษย์ เสมอ\n\nอัตโนมัติ ในเทิร์นฝ่ายเรา เมื่อมีการเปลี่ยนเป้าหมายการโจมตี : สามารถทำลาย Avatar ฝ่ายตรงข้าม 1 ใบ",
    cost: 8,
    gem: 0,
    power: 7,
    symbol: Symbol.Foreigner,
    color: Color.Purple,
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะโอคุง!!",
    type: CardType.Life,
    soi: 2,
    print: "PRMO-097",
    rare: Rarity.C,
    mainEffect: "ใน Main Phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "คุณทำโอคุงตาย นั้นแย่..แต่ไม่แยมาก เพราะโอคุงวันๆเอาแต่อ่านการ์ตูนทะลึ่งญี่ปุ่น ไม่เคยลงมาดูพ่อแม่ที่พิการที่อดข้าวมาสามอาทิตย์กว่า อย่างน้อยการตายของโอคุงก็จะทำให้พ่อแม่ที่พิการอิ่มไปได้อีกหลายวัน ขอบคุณ",
  },
  {
    name: "ไม่นะฟุจัง!!",
    type: CardType.Life,
    soi: 2,
    print: "PRMO-098",
    rare: Rarity.C,
    mainEffect: "ใน Main Phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText:
      "ฟุจังมีงานอีกมากมายแต่เธอก็ยังหาเวลามาเที่ยวงาน CA เพื่อส่งเสริมศิลปินอิสระของประเทศไทยให้มีกินมีใช้ แล้วมึงล่ะทำอะไรให้ประเทศชาติบ้าง.. จ่ายภาษีไม่นับ",
  },
  {
    name: "อย่าให้มีครั้งที่ 2",
    type: CardType.Magic,
    soi: 2,
    print: "PRMO-100",
    rare: Rarity.R,
    mainEffect:
      "เมื่อฝ่ายตรงข้ามใช้ {react} : ยกเลิกผลของการ์ดใบนั้น \nการ์ดใบนี้สามารถใช้ได้แม้ว่าในเทิร์นนี้เราใช้ การ์ด {react} ไปแล้ว#สามารถใช้การ์ด อย่าให้มีครั้งที่ 2 ได้ 1 ใบ ต่อเทิร์น เท่านั้น",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  },
  {
    name: "เลือกมันสำหรับพวก จน !!!",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-101",
    rare: Rarity.R,
    mainEffect:
      "เลือกปฏิบัติ :\n\n1) นำ Avatar Cost 5 หรือต่ำกว่า จาก นรก ฝ่ายเรา  ขึ้นมือ 1 ใบ ยกเว้นการ์ด {only} \n\n2) นำ Avatar ที่มี Cost 5 หรือต่ำกว่า จาก Deck ฝ่ายเรา ขึ้นมือ 1 ใบ ยกเว้นการ์ด  {only} 1 แล้วสับ Deck\n\nถ้า Life Card ของเราถูกหงายตั้งแต่ 4 ใบขึ้นไปและหงายมากกว่าฝ่ายตรงข้าม ทำความสามารถ 1) และ 2)",
    subtype: MagicSubtype.Normal,
    cost: 0,
    symbol: Symbol.Mage,
  },
  {
    name: "ซุนเซ็ก ขุนพลไฟแรงแห่งง่อก๊ก",
    type: CardType.Avatar,
    soi: 2,
    print: "PRMO-102",
    rare: Rarity.C,
    mainEffect:
      "แทงหลัง (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอน และนำ POWER การ์ดนี้ +1 ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น เมื่อจบการต่อสู้ ถ้า Avatar ที่สั่งโจมตี มีสีต่างกับ Avatar นี้ ทำลาย Avatar ที่สั่งโจมตี)\n\nอัตโนมัติ เทิร์นละครั้ง เมื่อการ์ดใบนี้ใช้ความสามารถ แทงหลัง ให้ Avatar สีแดง : เปลี่ยน Avatar ใบนี้จากสภาพนอนเป็นสภาพตื่น",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: Symbol.Foreigner,
    color: Color.Red,
    dropRate: "3 / กล่อง",
  },
  {
    name: "ดินแดนหิมะสีเทา",
    type: CardType.Magic,
    soi: 2,
    print: "PRMO-103",
    rare: Rarity.C,
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เลือก Avatar \"หิมะ\" ที่เป็น Symbol ชาวต่างชาติ 1 ใบ : Avatar ใบที่เลือก POWER +1 ต่อจำนวน \"ทหารหิมะ\" ทุกๆ 2 ใบ ในนรกฝ่ายเรา จนจบเทิร์น",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Foreigner,
  },
  {
    name: "ค่ายบางระจัน",
    type: CardType.Construct,
    soi: 2,
    print: "PRMO-104",
    rare: Rarity.SR,
    mainEffect:
      "ต่อเนื่อง ตราบเท่าที่การ์ดใบนี้อยู่บน Construct Zone ฝ่ายเรา Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box ทุกใบ POWER +1 และได้รับความสามารถ \"โล่มนุษย์\" และ \"สามัคคี\"\n\nเมื่อการ์ดใบนี้ถูกทำลาย ส่ง Avatar ทุกใบบน Avatar Zone ฝ่ายเรา ลงนรก",
    cost: 4,
    gem: 0,
    power: 6,
    symbol: Symbol.Building,
    color: Color.Red,
    dropRate: "2 / กล่อง",
  },
  {
    name: "อุบัติเหตุ!!!",
    type: CardType.Magic,
    soi: 1,
    print: "PRMO-119",
    rare: Rarity.SR,
    mainEffect: "เมื่อมี Avatar อัญเชิญลงมาบนสนาม : ทำลาย Avatar ตัวนั้น",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
  }
]);
