import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_SD01: Card[] = createCards([
  {
    name: "พระอิศวร",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-001",
    rare: Rarity.SR,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : เลือก Avatar 1 ใบ POWER -4 จนจบเทิร์น",
    cost: 6,
    gem: 2,
    power: 5,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "2 / กล่อง",
  },
  {
    name: "พระนารายณ์",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-002",
    rare: Rarity.SR,
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : POWER +2 จนจบเทิร์น",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "2 / กล่อง",
  },
  {
    name: "พระอินทร์",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-003",
    rare: Rarity.C,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : เลือก Avatar 1 ใบ POWER +3 จนจบเทิร์น",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "2 / กล่อง",
  },
  {
    name: "นนทก",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-004",
    rare: Rarity.C,
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้อยู่บน Avatar Zone POWER +1 ให้ Avatar {symbol เทพ} ทุกใบบน Avatar Zone ฝ่ายเรา",
    cost: 1,
    gem: 2,
    power: 1,
    symbol: Symbol.Giant,
    color: Color.Red,
    dropRate: "2 / กล่อง",
  },
  {
    name: "เมียพระอิศวร",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-005",
    rare: Rarity.UR,
    variants: [Rarity.PR, Rarity.CBR],
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : จั่วการ์ด 3 ใบ",
    cost: 3,
    gem: 4,
    power: 5,
    symbol: Symbol.God,
    color: Color.Red,
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ช่างแอร์ดวงซวย",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-006",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "4 / กล่อง",
  },
  {
    name: "เทวดานักมวย",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-007",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 1,
    power: 3,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "4 / กล่อง",
  },
  {
    name: "เทวดาแบงค์",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-008",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 0,
    power: 4,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "4 / กล่อง",
  },
  {
    name: "เด็กถ่ายเอกสาร",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-009",
    rare: Rarity.C,
    mainEffect: "",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "4 / กล่อง",
  },
  {
    name: "เทวดาตัวเปิด",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-010",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "3 / กล่อง",
  },
  {
    name: "ยักษ์ล้างส้วม",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-011",
    rare: Rarity.C,
    mainEffect: "",
    cost: 0,
    gem: 1,
    power: 1,
    symbol: Symbol.Giant,
    color: Color.Red,
    dropRate: "3 / กล่อง",
  },
  {
    name: "ยักษ์แบกปูน",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-012",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 2,
    power: 2,
    symbol: Symbol.Giant,
    color: Color.Red,
    dropRate: "2 / กล่อง",
  },
  {
    name: "เทวดาจิตบำบัด",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-013",
    rare: Rarity.C,
    mainEffect: "",
    cost: 1,
    gem: 3,
    power: 1,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "3 / กล่อง",
  },
  {
    name: "เทวดาเลื่อยยนต์",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-014",
    rare: Rarity.C,
    mainEffect: "",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "2 / กล่อง",
  },
  {
    name: "วิรุฬหก",
    type: CardType.Avatar,
    soi: 1,
    print: "SD01-015",
    rare: Rarity.C,
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 5,
    symbol: Symbol.God,
    color: Color.Red,
    dropRate: "2 / กล่อง",
  },
  {
    name: "น้ำแดง",
    type: CardType.Magic,
    soi: 1,
    print: "SD01-016",
    rare: Rarity.C,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ POWER +1",
    subtype: MagicSubtype.Modification,
    cost: 1,
    symbol: Symbol.Mage,
    dropRate: "2 / กล่อง",
  },
  {
    name: "อุบัติเหตุ!!!",
    type: CardType.Magic,
    soi: 1,
    print: "SD01-017",
    rare: Rarity.C,
    mainEffect: "เมื่อมี Avatar อัญเชิญลงมาบนสนาม : ทำลาย Avatar ตัวนั้น",
    subtype: MagicSubtype.React,
    cost: 1,
    symbol: Symbol.Mage,
    dropRate: "2 / กล่อง",
  },
  {
    name: "ความยุติธรรมสำหรับนนทก",
    type: CardType.Magic,
    soi: 1,
    print: "SD01-018",
    rare: Rarity.C,
    mainEffect: "ทิ้ง Avatar {symbol เทพ} จากบนมือ 1 ใบ : จั่วการ์ด 2 ใบ",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
    dropRate: "2 / กล่อง",
  },
  {
    name: "ฮ่า ฮ่า ฮ่า ผมได้เลื่อนขั้น",
    type: CardType.Magic,
    soi: 1,
    print: "SD01-019",
    rare: Rarity.C,
    mainEffect: "เลือก Avatar {symbol เทพ} 1 ใบ : POWER +2 จนจบเทิร์น",
    subtype: MagicSubtype.Normal,
    cost: 2,
    symbol: Symbol.Mage,
    dropRate: "2 / กล่อง",
  },
  {
    name: "เขาไกรลาส",
    type: CardType.Magic,
    soi: 1,
    print: "SD01-020",
    rare: Rarity.C,
    mainEffect: "POWER +1 ให้ Avatar {symbol เทพ} บนสนามทุกใบ",
    subtype: MagicSubtype.Land,
    cost: 2,
    symbol: Symbol.Mage,
    dropRate: "2 / กล่อง",
  },
  {
    name: "ไม่นะ อิศวร !",
    type: CardType.Life,
    soi: 1,
    print: "SD01-021",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "คุณปล่อยให้พระอิศวรเจ้าแห่ง3โลกตาย ทำให้สมดุลเศรษฐกิจบนสวรรค์กำลังล่มสลาย ตอนนี้ปลาประเภทเดียวที่มึงจะได้บุญจากการปล่อยปลาคือปลาฉลามขาว",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ นนทก !",
    type: CardType.Life,
    soi: 1,
    print: "SD01-022",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "นนทกก็แค่ยักษ์ล้างเท้าตนนึงอ่ะเนอะ ตายไปก็แค่เท้าดำขึ้นหน่อย โลกไม่ได้แตกไร ก็เนอะในมุมชนชั้นกลางของคุณ นนทกก็เป็นแค่ตัวถ่วงGDPอยู่แล้ว",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ อัปสร !",
    type: CardType.Life,
    soi: 1,
    print: "SD01-023",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "นางอัปสรเทพธิดานางฟ้ายอดนักเต้น เมื่อขาดเธอไป บนสวงสวรรค์ก็งดงามน้อยลงแล้วคนก็คงทำบาปมากขึ้นขอบคุณเว้ยมึง",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ ซาร่า !",
    type: CardType.Life,
    soi: 1,
    print: "SD01-024",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ซาร่าแอบชอบคุณมานานแล้ว แต่ก็ไม่เคยเลยที่คุณจะหันไปยิ้มให้เธอหรือรับรู้ว่าเธอมีตัวตนซักครั้ง และวันนี้ก็คงสมใจคุณแล้วสินะที่ซาร่าจะไม่อยู่ในโลกนี้อีก",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ หลวงพ่อ !",
    type: CardType.Life,
    soi: 1,
    print: "SD01-025",
    rare: Rarity.C,
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "สั้นๆ…ผมไม่มีอะไรจะพูดกับไอ้บาปที่ปล่อยหลวงพ่อตาย",
    dropRate: "1 / กล่อง",
  }
]);
