import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_SD02: Card[] = createCards([
  {
    soi: 1,
    print: "SD02-001",
    type: CardType.Avatar,
    name: "กุ่ย",
    rare: Rarity.C,
    dropRate: "2 / กล่อง",
    color: Color.Blue,
    gem: 2,
    gemColor: Color.None,
    cost: 2,
    power: 2,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)\n\nจุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"ฮอล\" 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
  },
  {
    soi: 1,
    print: "SD02-002",
    type: CardType.Avatar,
    name: "ฮอล",
    rare: Rarity.C,
    dropRate: "2 / กล่อง",
    color: Color.Blue,
    gem: 2,
    gemColor: Color.None,
    cost: 2,
    power: 2,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)\n\nจุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"นาย\" 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
  },
  {
    soi: 1,
    print: "SD02-003",
    type: CardType.Avatar,
    name: "นาย",
    rare: Rarity.C,
    dropRate: "2 / กล่อง",
    color: Color.Blue,
    gem: 2,
    gemColor: Color.None,
    cost: 2,
    power: 2,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)\n\nจุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"กุ่ย\" 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
  },
  {
    soi: 1,
    print: "SD02-004",
    type: CardType.Avatar,
    name: "ริกกี้ เพื่อนรัก",
    rare: Rarity.SR,
    dropRate: "2 / กล่อง",
    color: Color.Blue,
    gem: 2,
    gemColor: Color.None,
    cost: 3,
    power: 1,
    symbol: Symbol.Insect,
    subtype: "",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำการ์ดชื่อ \"กุ่ย\" , \"ฮอล\" หรือ \"นาย\" ได้สูงสุด 3 ใบ จากนรกเรา กลับเข้า Deck หลังจากนั้นสับ Deck แล้วจั่วการ์ด 1 ใบ",
  },
  {
    soi: 1,
    print: "SD02-005",
    type: CardType.Avatar,
    name: "วีรบุรุษปากซอย",
    rare: Rarity.UR,
    dropRate: "1 / กล่อง",
    customLimit: 1,
    ex: "Only #1",
    color: Color.Blue,
    gem: 2,
    gemColor: Color.None,
    cost: 6,
    power: 6,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"กุ่ย\",\"ฮอล\" หรือ \"นาย\" ได้สูงสุด 3 ใบจากนรกเราขึ้นมือ",
    variants: [Rarity.PR, Rarity.CBR],
  },
  {
    soi: 1,
    print: "SD02-006",
    type: CardType.Avatar,
    name: "ครูภาษาไทย",
    rare: Rarity.C,
    dropRate: "4 / กล่อง",
    color: Color.Blue,
    gem: 4,
    gemColor: Color.None,
    cost: 0,
    power: 0,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-007",
    type: CardType.Avatar,
    name: "นักเรียน แบงค์",
    rare: Rarity.C,
    dropRate: "4 / กล่อง",
    color: Color.Blue,
    gem: 1,
    gemColor: Color.None,
    cost: 1,
    power: 3,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-008",
    type: CardType.Avatar,
    name: "เด็กไม่ชอบแมลงสาบมากๆ",
    rare: Rarity.C,
    dropRate: "4 / กล่อง",
    color: Color.Blue,
    gem: 0,
    gemColor: Color.None,
    cost: 1,
    power: 4,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-009",
    type: CardType.Avatar,
    name: "ตำรวจ",
    rare: Rarity.C,
    dropRate: "3 / กล่อง",
    color: Color.Blue,
    gem: 3,
    gemColor: Color.None,
    cost: 2,
    power: 2,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-010",
    type: CardType.Avatar,
    name: "เด็กไม่ชอบแมลงสาบ",
    rare: Rarity.C,
    dropRate: "2 / กล่อง",
    color: Color.Blue,
    gem: 0,
    gemColor: Color.None,
    cost: 0,
    power: 3,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-011",
    type: CardType.Avatar,
    name: "ลุงข้างห้อง",
    rare: Rarity.C,
    dropRate: "3 / กล่อง",
    color: Color.Blue,
    gem: 0,
    gemColor: Color.None,
    cost: 0,
    power: 1,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-012",
    type: CardType.Avatar,
    name: "แท็กซี่ตีนเปล่า",
    rare: Rarity.C,
    dropRate: "3 / กล่อง",
    color: Color.Blue,
    gem: 2,
    gemColor: Color.None,
    cost: 1,
    power: 2,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-013",
    type: CardType.Avatar,
    name: "ไอ้ดำ",
    rare: Rarity.C,
    dropRate: "3 / กล่อง",
    color: Color.Blue,
    gem: 3,
    gemColor: Color.None,
    cost: 1,
    power: 1,
    symbol: Symbol.Animal,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-014",
    type: CardType.Avatar,
    name: "ปื๊ด เด็กติดยา",
    rare: Rarity.C,
    dropRate: "3 / กล่อง",
    color: Color.Blue,
    gem: 2,
    gemColor: Color.None,
    cost: 4,
    power: 4,
    symbol: Symbol.Human,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-015",
    type: CardType.Avatar,
    name: "รัททาทุย ผู้พิทักษ์ราชินี",
    rare: Rarity.C,
    dropRate: "2 / กล่อง",
    color: Color.Blue,
    gem: 3,
    gemColor: Color.None,
    cost: 5,
    power: 5,
    symbol: Symbol.Rat,
    subtype: "",
    mainEffect: "",
  },
  {
    soi: 1,
    print: "SD02-016",
    type: CardType.Magic,
    name: "ระเบิดVery Fat Man",
    rare: Rarity.SR,
    dropRate: "2 / กล่อง",
    gem: 0,
    gemColor: Color.None,
    symbol: Symbol.Mage,
    subtype: MagicSubtype.React,
    mainEffect: "ส่ง Avatar \"กุ่ย\",\"ฮอล\" และ \"นาย\" อย่างละ 1 ใบ จากบนมือเรา และ,หรือ บนสนามเราลงนรก : ทำลาย Avatar ทุกใบบนสนามฝ่ายตรงข้าม",
  },
  {
    soi: 1,
    print: "SD02-017",
    type: CardType.Magic,
    name: "ไม้เกาหลัง",
    rare: Rarity.C,
    dropRate: "2 / กล่อง",
    gem: 2,
    gemColor: Color.None,
    symbol: Symbol.Rat,
    subtype: MagicSubtype.Modification,
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ได้รับความสามารถ เตะไข่ (Avatar ใบนี้สามารถโจมตีไปที่ LIFE Card ได้โดยตรง แม้ว่า Avatar Zone ของอีกฝ่ายจะมี Avatar อยู่ก็ตาม)",
  },
  {
    soi: 1,
    print: "SD02-018",
    type: CardType.Magic,
    name: "บำเพ็ญประโยชน์",
    rare: Rarity.C,
    dropRate: "2 / กล่อง",
    gem: 1,
    gemColor: Color.None,
    symbol: Symbol.Mage,
    subtype: MagicSubtype.Normal,
    mainEffect: "ส่ง Avatar ชื่อ \"กุ่ย\",\"ฮอล\" หรือ \"นาย\" 1 ใบ จากบนมือลงนรก : จั่วการ์ด 2 ใบ",
  },
  {
    soi: 1,
    print: "SD02-019",
    type: CardType.Magic,
    name: "สละเพื่อนเพื่อช่วยเพื่อน",
    rare: Rarity.C,
    dropRate: "2 / กล่อง",
    gem: 1,
    gemColor: Color.None,
    symbol: Symbol.Mage,
    subtype: MagicSubtype.React,
    mainEffect: "ส่ง Avatar ชื่อ \"กุ่ย\",\"ฮอล\" หรือ \"นาย\" 1 ใบ จากบนมือเรา หรือ บนสนามเราลงนรก : นำ Avatar 1 ใบบนสนามกลับขึ้นมือ",
  },
  {
    soi: 1,
    print: "SD02-020",
    type: CardType.Magic,
    name: "สมชาย ห้องเช่าถูกๆ",
    rare: Rarity.C,
    dropRate: "2 / กล่อง",
    gem: 1,
    gemColor: Color.None,
    symbol: Symbol.Mage,
    subtype: MagicSubtype.Land,
    mainEffect: "POWER +2 ให้ Avatar \"กุ่ย\",\"ฮอล\" และ \"นาย\" ที่สั่งโจมตีจนจบการต่อสู้นั้น",
  },
  {
    soi: 1,
    print: "SD02-021",
    type: CardType.Life,
    name: "ไม่นะ กุ่ย !",
    rare: Rarity.C,
    dropRate: "1 / กล่อง",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "กุ่ยเป็นเด็กที่ขี้เล่น มีจินตนาการ และเป็นตัวโปรดในการ์ตูนผม แต่มึงก็ยังปล่อยให้กุ่ยตายแล้วตอนนี้การ์ตูนกูไม่สนุกละ",
  },
  {
    soi: 1,
    print: "SD02-022",
    type: CardType.Life,
    name: "ไม่นะ ฮอล !",
    rare: Rarity.C,
    dropRate: "1 / กล่อง",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ถึงฮอลจะเป็นคนขี้กลัว แต่เขาก็พร้อมที่จะสู้เมื่อเพื่อนฝูงของเขากำลังตกอยู่ในอันตราย และโลกนี้ก็คงอบอุ่นน้อยลงที่ต้องขาดเพื่อนดีๆอย่างฮอล",
  },
  {
    soi: 1,
    print: "SD02-023",
    type: CardType.Life,
    name: "ไม่นะ นาย !",
    rare: Rarity.C,
    dropRate: "1 / กล่อง",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ไอ้นายจะเป็นคนตรงๆและคุณอาจไม่ชอบมัน แต่คำเหล่านั้นมาจากใจของคนจริงใจที่คุณเพิ่งปล่อยตายไป นั้นก็เชิญอยู่กับพวกเพื่อนเทียมคำชมปลอมๆที่ยังไงคุณก็รู้ว่ามันกลวง",
  },
  {
    soi: 1,
    print: "SD02-024",
    type: CardType.Life,
    name: "ไม่นะ ครู !",
    rare: Rarity.C,
    dropRate: "1 / กล่อง",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ครูอ้อยคือเครื่องผลิตอนาคตของชาติมายาวนานกว่า43ปีโดยไม่หยุดพัก และจุดจบของเธอครั้งนี้จะเป็นบทเรียนสุดท้ายให้ทุกคนรู้ว่า การทำดีที่ไม่มีใครเห็นค่ามันก็แบบนี้แหละ",
  },
  {
    soi: 1,
    print: "SD02-025",
    type: CardType.Life,
    name: "ไม่นะ จามาล !",
    rare: Rarity.C,
    dropRate: "1 / กล่อง",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "จามาล นักร้องนำของวงHeartz Boyz ที่ตลาดพลู จามาลใช้เงินรักษามะเร็งที่เหลือมาตั้งวงเพื่อทำตามฝันของเขา และดูเหมือนว่าตอนนี้เสียงของจามาลจะไม่ดังพอที่จะไปสู่หูของคนทั่วโลกหรือแม้แต่แม่ของเขา",
  }
]);
