import { Card, CardType, Rarity, MagicSubtype, Symbol, Color } from "@/src/types/cards";
import { createCards } from "@/src/utils/cardHelpers";

export const CARDS_SL01: Card[] = createCards([
  {
    name: "นางมณโฑ",
    type: CardType.Avatar,
    soi: 1,
    print: "SL01-001",
    rare: Rarity.USEC,
    mainEffect: "จุติ เลือก Avatar {symbol ยักษ์} ที่ POWER ไม่เกิน 3 ในนรกฝ่ายเรา 1 ใบ : อัญเชิญ Avatar ใบนั้นลงบน Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: Symbol.Human,
    color: Color.Green,
  },
  {
    name: "ทศกัณฐ์ยักษ์ที่---เมียพระอิศวร",
    type: CardType.Avatar,
    soi: 1,
    print: "SL01-002",
    rare: Rarity.USEC,
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สามารถเลือก Avatar บน Avatar Zone ฝ่ายตรงข้าม 1 ใบ เปลี่ยนการควบคุมมาบน Avatar Zone ฝ่ายเราในสภาพนอน",
    cost: 4,
    gem: 3,
    power: 5,
    symbol: Symbol.Giant,
    color: Color.Purple,
    ex: "Only #1",
  },
  {
    name: "พระอิศวร",
    type: CardType.Avatar,
    soi: 1,
    print: "SL01-003",
    rare: Rarity.USEC,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : เลือก Avatar 1 ใบ POWER -4 จนจบเทิร์น",
    cost: 6,
    gem: 2,
    power: 5,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "พระนารายณ์",
    type: CardType.Avatar,
    soi: 1,
    print: "SL01-004",
    rare: Rarity.USEC,
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : POWER +2 จนจบเทิร์น",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "พระอินทร์",
    type: CardType.Avatar,
    soi: 1,
    print: "SL01-005",
    rare: Rarity.USEC,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : เลือก Avatar 1 ใบ POWER +3 จนจบเทิร์น",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "พระพรหม",
    type: CardType.Avatar,
    soi: 1,
    print: "SL01-008",
    rare: Rarity.USEC,
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) เซ่นไหว้ (ทำลาย Avatar จาก Avatar Zone ลงนรก)  Avatar ฝ่ายเรา 1 ใบ : อัญเชิญ จุติ Avatar จากนรกของเราที่มี Symbol เดียวกับใบที่ เซ่นไหว้ ไป แต่ชื่อไม่ซ้ำกับใบที่ เซ่นไหว้ไป Cost ไม่เกิน 8 ลงบน Avatar Zone ฝ่ายเรา",
    cost: 8,
    gem: 2,
    power: 6,
    symbol: Symbol.God,
    color: Color.Red,
  },
  {
    name: "ชายจากอนาคต",
    type: CardType.Magic,
    soi: 1,
    print: "SL01-006",
    rare: Rarity.USEC,
    mainEffect: "เมื่อมีการใช้ Magic Card : ยกเลิกการใช้ Magic Card ใบนั้น",
    subtype: MagicSubtype.React,
    cost: 0,
    symbol: Symbol.Mage,
  },
  {
    name: "เลือกมันสำหรับพวก จน !!!",
    type: CardType.Magic,
    soi: 1,
    print: "SL01-007",
    rare: Rarity.USEC,
    mainEffect:
      "เลือกปฏิบัติ :\n1) นำ Avatar Cost 5 หรือต่ำกว่า จาก นรก ฝ่ายเรา  ขึ้นมือ 1 ใบ ยกเว้นการ์ด {only} \n2) นำ Avatar ที่มี Cost 5 หรือต่ำกว่า จาก Deck ฝ่ายเรา ขึ้นมือ 1 ใบ ยกเว้นการ์ด  {only} 1 แล้วสับ Deck \nถ้า Life Card ของเราถูกหงายตั้งแต่ 4 ใบขึ้นไปและหงายมากกว่าฝ่ายตรงข้าม ทำความสามารถ 1) และ 2)",
    subtype: MagicSubtype.Normal,
    cost: 1,
    symbol: Symbol.Mage,
  }
]);
